// HSK Vocabulary Data
const hsk1Words = [
  { hanzi: "爱", pinyin: "ài", meaning: "사랑하다" },
  { hanzi: "八", pinyin: "bā", meaning: "여덟" },
  { hanzi: "爸爸", pinyin: "bàba", meaning: "아빠" },
  { hanzi: "杯子", pinyin: "bēizi", meaning: "컵" },
  { hanzi: "北京", pinyin: "Běijīng", meaning: "베이징" },
  { hanzi: "本", pinyin: "běn", meaning: "권 (책을 세는 단위)" },
  { hanzi: "不客气", pinyin: "búkèqi", meaning: "천만에요" },
  { hanzi: "不", pinyin: "bù", meaning: "아니다" },
  { hanzi: "菜", pinyin: "cài", meaning: "요리, 채소" },
  { hanzi: "茶", pinyin: "chá", meaning: "차" },
  { hanzi: "吃", pinyin: "chī", meaning: "먹다" },
  { hanzi: "出租车", pinyin: "chūzūchē", meaning: "택시" },
  { hanzi: "打电话", pinyin: "dǎ diànhuà", meaning: "전화하다" },
  { hanzi: "大", pinyin: "dà", meaning: "크다" },
  { hanzi: "的", pinyin: "de", meaning: "~의" },
  { hanzi: "点", pinyin: "diǎn", meaning: "시 (시간)" },
  { hanzi: "电脑", pinyin: "diànnǎo", meaning: "컴퓨터" },
  { hanzi: "电视", pinyin: "diànshì", meaning: "TV" },
  { hanzi: "电影", pinyin: "diànyǐng", meaning: "영화" },
  { hanzi: "东西", pinyin: "dōngxi", meaning: "물건" },
  { hanzi: "都", pinyin: "dōu", meaning: "모두" },
  { hanzi: "读", pinyin: "dú", meaning: "읽다" },
  { hanzi: "对不起", pinyin: "duìbuqǐ", meaning: "미안합니다" },
  { hanzi: "多", pinyin: "duō", meaning: "많다" },
  { hanzi: "多少", pinyin: "duōshao", meaning: "얼마" },
  { hanzi: "儿子", pinyin: "érzi", meaning: "아들" },
  { hanzi: "二", pinyin: "èr", meaning: "둘" },
  { hanzi: "饭店", pinyin: "fàndiàn", meaning: "식당, 호텔" },
  { hanzi: "飞机", pinyin: "fēijī", meaning: "비행기" },
  { hanzi: "分钟", pinyin: "fēnzhōng", meaning: "분 (시간)" },
  { hanzi: "高兴", pinyin: "gāoxìng", meaning: "기쁘다" },
  { hanzi: "个", pinyin: "gè", meaning: "개" },
  { hanzi: "工作", pinyin: "gōngzuò", meaning: "일, 일하다" },
  { hanzi: "汉语", pinyin: "Hànyǔ", meaning: "중국어" },
  { hanzi: "好", pinyin: "hǎo", meaning: "좋다" },
  { hanzi: "号", pinyin: "hào", meaning: "일, 번호" },
  { hanzi: "喝", pinyin: "hē", meaning: "마시다" },
  { hanzi: "和", pinyin: "hé", meaning: "와/과" },
  { hanzi: "很", pinyin: "hěn", meaning: "매우" },
  { hanzi: "后面", pinyin: "hòumiàn", meaning: "뒤" },
  { hanzi: "回", pinyin: "huí", meaning: "돌아가다" },
  { hanzi: "会", pinyin: "huì", meaning: "할 줄 알다" },
  { hanzi: "几", pinyin: "jǐ", meaning: "몇" },
  { hanzi: "家", pinyin: "jiā", meaning: "집, 가족" },
  { hanzi: "叫", pinyin: "jiào", meaning: "부르다" },
  { hanzi: "今天", pinyin: "jīntiān", meaning: "오늘" },
  { hanzi: "九", pinyin: "jiǔ", meaning: "아홉" },
  { hanzi: "开", pinyin: "kāi", meaning: "열다, 켜다" },
  { hanzi: "看", pinyin: "kàn", meaning: "보다" },
  { hanzi: "看见", pinyin: "kànjiàn", meaning: "보이다" },
  { hanzi: "块", pinyin: "kuài", meaning: "위안 (돈 단위)" },
  { hanzi: "来", pinyin: "lái", meaning: "오다" },
  { hanzi: "老师", pinyin: "lǎoshī", meaning: "선생님" },
  { hanzi: "了", pinyin: "le", meaning: "~했다 (완료)" },
  { hanzi: "冷", pinyin: "lěng", meaning: "춥다" },
  { hanzi: "里", pinyin: "lǐ", meaning: "안" },
  { hanzi: "零", pinyin: "líng", meaning: "영 (0)" },
  { hanzi: "六", pinyin: "liù", meaning: "여섯" },
  { hanzi: "妈妈", pinyin: "māma", meaning: "엄마" },
  { hanzi: "吗", pinyin: "ma", meaning: "입니까? (의문 조사)" },
  { hanzi: "买", pinyin: "mǎi", meaning: "사다" },
  { hanzi: "猫", pinyin: "māo", meaning: "고양이" },
  { hanzi: "没", pinyin: "méi", meaning: "없다, 안 했다" },
  { hanzi: "没关系", pinyin: "méiguānxi", meaning: "괜찮습니다" },
  { hanzi: "米饭", pinyin: "mǐfàn", meaning: "쌀밥" },
  { hanzi: "明天", pinyin: "míngtiān", meaning: "내일" },
  { hanzi: "名字", pinyin: "míngzi", meaning: "이름" },
  { hanzi: "哪", pinyin: "nǎ", meaning: "어느" },
  { hanzi: "哪儿", pinyin: "nǎr", meaning: "어디" },
  { hanzi: "那", pinyin: "nà", meaning: "그, 저" },
  { hanzi: "呢", pinyin: "ne", meaning: "는요? (의문 조사)" },
  { hanzi: "能", pinyin: "néng", meaning: "할 수 있다" },
  { hanzi: "你", pinyin: "nǐ", meaning: "너" },
  { hanzi: "年", pinyin: "nián", meaning: "년" },
  { hanzi: "女儿", pinyin: "nǚ'ér", meaning: "딸" },
  { hanzi: "朋友", pinyin: "péngyou", meaning: "친구" },
  { hanzi: "漂亮", pinyin: "piàoliang", meaning: "예쁘다" },
  { hanzi: "苹果", pinyin: "píngguǒ", meaning: "사과" },
  { hanzi: "七", pinyin: "qī", meaning: "일곱" },
  { hanzi: "钱", pinyin: "qián", meaning: "돈" },
  { hanzi: "前面", pinyin: "qiánmiàn", meaning: "앞" },
  { hanzi: "请", pinyin: "qǐng", meaning: "청하다, 제발" },
  { hanzi: "去", pinyin: "qù", meaning: "가다" },
  { hanzi: "热", pinyin: "rè", meaning: "덥다" },
  { hanzi: "人", pinyin: "rén", meaning: "사람" },
  { hanzi: "认识", pinyin: "rènshi", meaning: "알다, 인식하다" },
  { hanzi: "三", pinyin: "sān", meaning: "셋" },
  { hanzi: "商店", pinyin: "shāngdiàn", meaning: "상점" },
  { hanzi: "上", pinyin: "shàng", meaning: "위" },
  { hanzi: "上午", pinyin: "shàngwǔ", meaning: "오전" },
  { hanzi: "少", pinyin: "shǎo", meaning: "적다" },
  { hanzi: "谁", pinyin: "shéi", meaning: "누구" },
  { hanzi: "什么", pinyin: "shénme", meaning: "무엇" },
  { hanzi: "十", pinyin: "shí", meaning: "열" },
  { hanzi: "时候", pinyin: "shíhou", meaning: "때, 시간" },
  { hanzi: "是", pinyin: "shì", meaning: "~이다" },
  { hanzi: "书", pinyin: "shū", meaning: "책" },
  { hanzi: "水", pinyin: "shuǐ", meaning: "물" },
  { hanzi: "水果", pinyin: "shuǐguǒ", meaning: "과일" },
  { hanzi: "睡觉", pinyin: "shuìjiào", meaning: "자다" },
  { hanzi: "说话", pinyin: "shuōhuà", meaning: "말하다" },
  { hanzi: "四", pinyin: "sì", meaning: "넷" },
  { hanzi: "岁", pinyin: "suì", meaning: "살 (나이)" },
  { hanzi: "他", pinyin: "tā", meaning: "그" },
  { hanzi: "她", pinyin: "tā", meaning: "그녀" },
  { hanzi: "太", pinyin: "tài", meaning: "너무" },
  { hanzi: "天气", pinyin: "tiānqì", meaning: "날씨" },
  { hanzi: "听", pinyin: "tīng", meaning: "듣다" },
  { hanzi: "同学", pinyin: "tóngxué", meaning: "학우" },
  { hanzi: "喂", pinyin: "wéi", meaning: "여보세요" },
  { hanzi: "我", pinyin: "wǒ", meaning: "나" },
  { hanzi: "我们", pinyin: "wǒmen", meaning: "우리" },
  { hanzi: "五", pinyin: "wǔ", meaning: "다섯" },
  { hanzi: "喜欢", pinyin: "xǐhuan", meaning: "좋아하다" },
  { hanzi: "下", pinyin: "xià", meaning: "아래" },
  { hanzi: "下午", pinyin: "xiàwǔ", meaning: "오후" },
  { hanzi: "下雨", pinyin: "xiàyǔ", meaning: "비가 오다" },
  { hanzi: "先生", pinyin: "xiānsheng", meaning: "선생님, 미스터" },
  { hanzi: "现在", pinyin: "xiànzài", meaning: "지금" },
  { hanzi: "想", pinyin: "xiǎng", meaning: "생각하다, ~하고 싶다" },
  { hanzi: "小", pinyin: "xiǎo", meaning: "작다" },
  { hanzi: "小姐", pinyin: "xiǎojiě", meaning: "아가씨" },
  { hanzi: "些", pinyin: "xiē", meaning: "조금, 약간" },
  { hanzi: "写", pinyin: "xiě", meaning: "쓰다" },
  { hanzi: "谢谢", pinyin: "xièxie", meaning: "감사합니다" },
  { hanzi: "星期", pinyin: "xīngqī", meaning: "요일" },
  { hanzi: "学生", pinyin: "xuésheng", meaning: "학생" },
  { hanzi: "学习", pinyin: "xuéxí", meaning: "학습하다" },
  { hanzi: "学校", pinyin: "xuéxiào", meaning: "학교" },
  { hanzi: "一", pinyin: "yī", meaning: "하나" },
  { hanzi: "衣服", pinyin: "yīfu", meaning: "옷" },
  { hanzi: "医生", pinyin: "yīshēng", meaning: "의사" },
  { hanzi: "医院", pinyin: "yīyuàn", meaning: "병원" },
  { hanzi: "椅子", pinyin: "yǐzi", meaning: "의자" },
  { hanzi: "有", pinyin: "yǒu", meaning: "있다" },
  { hanzi: "月", pinyin: "yuè", meaning: "월" },
  { hanzi: "再见", pinyin: "zàijiàn", meaning: "안녕히 가세요" },
  { hanzi: "在", pinyin: "zài", meaning: "있다, ~에서" },
  { hanzi: "怎么", pinyin: "zěnme", meaning: "어떻게" },
  { hanzi: "怎么样", pinyin: "zěnmeyàng", meaning: "어때요" },
  { hanzi: "这", pinyin: "zhè", meaning: "이것" },
  { hanzi: "中国", pinyin: "Zhōngguó", meaning: "중국" },
  { hanzi: "中午", pinyin: "zhōngwǔ", meaning: "정오" },
  { hanzi: "住", pinyin: "zhù", meaning: "살다, 거주하다" },
  { hanzi: "桌子", pinyin: "zhuōzi", meaning: "책상" },
  { hanzi: "字", pinyin: "zì", meaning: "글자" },
  { hanzi: "昨天", pinyin: "zuótiān", meaning: "어제" },
  { hanzi: "坐", pinyin: "zuò", meaning: "앉다, 타다" },
  { hanzi: "做", pinyin: "zuò", meaning: "하다, 만들다" }
];

const hsk2Words = [
  { hanzi: "吧", pinyin: "ba", meaning: "~하자, ~지 (어기조사)" },
  { hanzi: "白", pinyin: "bái", meaning: "하얗다" },
  { hanzi: "百", pinyin: "bǎi", meaning: "백" },
  { hanzi: "帮助", pinyin: "bāngzhù", meaning: "돕다" },
  { hanzi: "报纸", pinyin: "bàozhǐ", meaning: "신문" },
  { hanzi: "比", pinyin: "bǐ", meaning: "~보다" },
  { hanzi: "别", pinyin: "bié", meaning: "~하지 마라" },
  { hanzi: "长", pinyin: "cháng", meaning: "길다" },
  { hanzi: "唱歌", pinyin: "chànggē", meaning: "노래하다" },
  { hanzi: "出", pinyin: "chū", meaning: "나가다, 나오다" },
  { hanzi: "穿", pinyin: "chuān", meaning: "입다" },
  { hanzi: "次", pinyin: "cì", meaning: "번, 차례" },
  { hanzi: "从", pinyin: "cóng", meaning: "~부터" },
  { hanzi: "错", pinyin: "cuò", meaning: "틀리다" },
  { hanzi: "打篮球", pinyin: "dǎ lánqiú", meaning: "농구하다" },
  { hanzi: "大家", pinyin: "dàjiā", meaning: "여러분" },
  { hanzi: "到", pinyin: "dào", meaning: "도착하다" },
  { hanzi: "得", pinyin: "de", meaning: "정도를 나타내는 구조조사" },
  { hanzi: "等", pinyin: "děng", meaning: "기다리다" },
  { hanzi: "弟弟", pinyin: "dìdi", meaning: "남동생" },
  { hanzi: "第一", pinyin: "dì-yī", meaning: "제일, 첫째" },
  { hanzi: "懂", pinyin: "dǒng", meaning: "이해하다" },
  { hanzi: "对", pinyin: "duì", meaning: "맞다, ~에 대하여" },
  { hanzi: "房间", pinyin: "fángjiān", meaning: "방" },
  { hanzi: "非常", pinyin: "fēicháng", meaning: "매우" },
  { hanzi: "服务员", pinyin: "fúwùyuán", meaning: "종업원" },
  { hanzi: "高", pinyin: "gāo", meaning: "높다" },
  { hanzi: "告诉", pinyin: "gàosu", meaning: "알리다" },
  { hanzi: "哥哥", pinyin: "gēge", meaning: "형, 오빠" },
  { hanzi: "给", pinyin: "gěi", meaning: "주다, ~에게" },
  { hanzi: "公共汽车", pinyin: "gōnggòng qìchē", meaning: "버스" },
  { hanzi: "公司", pinyin: "gōngsī", meaning: "회사" },
  { hanzi: "狗", pinyin: "gǒu", meaning: "개" },
  { hanzi: "贵", pinyin: "guì", meaning: "비싸다" },
  { hanzi: "过", pinyin: "guo", meaning: "~한 적이 있다 (경험)" },
  { hanzi: "还", pinyin: "hái", meaning: "아직, 또" },
  { hanzi: "孩子", pinyin: "háizi", meaning: "아이" },
  { hanzi: "好吃", pinyin: "hǎochī", meaning: "맛있다" },
  { hanzi: "黑", pinyin: "hēi", meaning: "검다" },
  { hanzi: "红", pinyin: "hóng", meaning: "붉다" },
  { hanzi: "欢迎", pinyin: "huānyíng", meaning: "환영하다" },
  { hanzi: "回答", pinyin: "huídá", meaning: "대답하다" },
  { hanzi: "火车站", pinyin: "huǒchēzhàn", meaning: "기차역" },
  { hanzi: "机场", pinyin: "jīchǎng", meaning: "공항" },
  { hanzi: "鸡蛋", pinyin: "jīdàn", meaning: "계란" },
  { hanzi: "件", pinyin: "jiàn", meaning: "건, 벌 (양사)" },
  { hanzi: "教室", pinyin: "jiàoshì", meaning: "교실" },
  { hanzi: "姐姐", pinyin: "jiějie", meaning: "누나, 언니" },
  { hanzi: "介绍", pinyin: "jièshào", meaning: "소개하다" },
  { hanzi: "进", pinyin: "jìn", meaning: "들어가다" },
  { hanzi: "近", pinyin: "jìn", meaning: "가깝다" },
  { hanzi: "就", pinyin: "jiù", meaning: "바로, 곧" },
  { hanzi: "觉得", pinyin: "juéde", meaning: "느끼다, 생각하다" },
  { hanzi: "咖啡", pinyin: "kāfēi", meaning: "커피" },
  { hanzi: "开始", pinyin: "kāishǐ", meaning: "시작하다" },
  { hanzi: "考试", pinyin: "kǎoshì", meaning: "시험" },
  { hanzi: "可能", pinyin: "kěnéng", meaning: "가능하다, 아마도" },
  { hanzi: "可以", pinyin: "kěyǐ", meaning: "할 수 있다, 해도 좋다" },
  { hanzi: "课", pinyin: "kè", meaning: "수업" },
  { hanzi: "快", pinyin: "kuài", meaning: "빠르다" },
  { hanzi: "快乐", pinyin: "kuàilè", meaning: "즐겁다" },
  { hanzi: "累", pinyin: "lèi", meaning: "피곤하다" },
  { hanzi: "离", pinyin: "lí", meaning: "~에서 (거리)" },
  { hanzi: "两", pinyin: "liǎng", meaning: "둘 (수량)" },
  { hanzi: "零", pinyin: "líng", meaning: "영" },
  { hanzi: "路", pinyin: "lù", meaning: "길" },
  { hanzi: "旅游", pinyin: "lǚyóu", meaning: "여행하다" },
  { hanzi: "卖", pinyin: "mài", meaning: "팔다" },
  { hanzi: "慢", pinyin: "màn", meaning: "느리다" },
  { hanzi: "忙", pinyin: "máng", meaning: "바쁘다" },
  { hanzi: "每", pinyin: "měi", meaning: "매, 마다" },
  { hanzi: "妹妹", pinyin: "mèimei", meaning: "여동생" },
  { hanzi: "门", pinyin: "mén", meaning: "문" },
  { hanzi: "面条", pinyin: "miàntiáo", meaning: "국수" },
  { hanzi: "男", pinyin: "nán", meaning: "남자" },
  { hanzi: "您", pinyin: "nín", meaning: "당신 (존칭)" },
  { hanzi: "牛奶", pinyin: "niúnǎi", meaning: "우유" },
  { hanzi: "女", pinyin: "nǚ", meaning: "여자" },
  { hanzi: "旁边", pinyin: "pángbiān", meaning: "옆" },
  { hanzi: "跑步", pinyin: "pǎobù", meaning: "달리다" },
  { hanzi: "便宜", pinyin: "piányi", meaning: "싸다" },
  { hanzi: "票", pinyin: "piào", meaning: "표" },
  { hanzi: "妻子", pinyin: "qīzi", meaning: "아내" },
  { hanzi: "起床", pinyin: "qǐchuáng", meaning: "일어나다 (기상)" },
  { hanzi: "千", pinyin: "qiān", meaning: "천" },
  { hanzi: "铅笔", pinyin: "qiānbǐ", meaning: "연필" },
  { hanzi: "晴", pinyin: "qíng", meaning: "맑다" },
  { hanzi: "去年", pinyin: "qùnián", meaning: "작년" },
  { hanzi: "让", pinyin: "ràng", meaning: "양보하다, ~하게 하다" },
  { hanzi: "日", pinyin: "rì", meaning: "일, 해" },
  { hanzi: "上班", pinyin: "shàngbān", meaning: "출근하다" },
  { hanzi: "身体", pinyin: "shēntǐ", meaning: "신체, 몸" },
  { hanzi: "生病", pinyin: "shēngbìng", meaning: "병이 나다" },
  { hanzi: "生日", pinyin: "shēngrì", meaning: "생일" },
  { hanzi: "时间", pinyin: "shíjiān", meaning: "시간" },
  { hanzi: "事情", pinyin: "shìqing", meaning: "일, 사건" },
  { hanzi: "手表", pinyin: "shǒubiǎo", meaning: "손목시계" },
  { hanzi: "手机", pinyin: "shǒujī", meaning: "휴대폰" },
  { hanzi: "说话", pinyin: "shuōhuà", meaning: "말하다" },
  { hanzi: "送", pinyin: "sòng", meaning: "보내다, 선물하다" },
  { hanzi: "虽然", pinyin: "suīrán", meaning: "비록" },
  { hanzi: "但是", pinyin: "dànshì", meaning: "그러나" },
  { hanzi: "它", pinyin: "tā", meaning: "그것" },
  { hanzi: "踢足球", pinyin: "tī zúqiú", meaning: "축구하다" },
  { hanzi: "题", pinyin: "tí", meaning: "문제" },
  { hanzi: "跳舞", pinyin: "tiàowǔ", meaning: "춤추다" },
  { hanzi: "外", pinyin: "wài", meaning: "밖" },
  { hanzi: "完", pinyin: "wán", meaning: "끝나다" },
  { hanzi: "玩", pinyin: "wán", meaning: "놀다" },
  { hanzi: "晚上", pinyin: "wǎnshang", meaning: "저녁" },
  { hanzi: "往", pinyin: "wǎng", meaning: "~을 향해" },
  { hanzi: "为什么", pinyin: "wèishénme", meaning: "왜" },
  { hanzi: "问", pinyin: "wèn", meaning: "묻다" },
  { hanzi: "问题", pinyin: "wèntí", meaning: "문제" },
  { hanzi: "希望", pinyin: "xīwàng", meaning: "희망하다" },
  { hanzi: "西瓜", pinyin: "xīguā", meaning: "수박" },
  { hanzi: "洗", pinyin: "xǐ", meaning: "씻다" },
  { hanzi: "小时", pinyin: "xiǎoshí", meaning: "시간 (Hour)" },
  { hanzi: "笑", pinyin: "xiào", meaning: "웃다" },
  { hanzi: "新", pinyin: "xīn", meaning: "새롭다" },
  { hanzi: "姓", pinyin: "xìng", meaning: "성씨" },
  { hanzi: "休息", pinyin: "xiūxi", meaning: "휴식하다" },
  { hanzi: "雪", pinyin: "xuě", meaning: "눈 (자연)" },
  { hanzi: "颜色", pinyin: "yánsè", meaning: "색깔" },
  { hanzi: "眼睛", pinyin: "yǎnjing", meaning: "눈 (신체)" },
  { hanzi: "羊肉", pinyin: "yángròu", meaning: "양고기" },
  { hanzi: "药", pinyin: "yào", meaning: "약" },
  { hanzi: "要", pinyin: "yào", meaning: "원하다, ~해야 한다" },
  { hanzi: "也", pinyin: "yě", meaning: "도, 역시" },
  { hanzi: "一起", pinyin: "yìqǐ", meaning: "함께" },
  { hanzi: "一下", pinyin: "yíxià", meaning: "한 번 ~하다" },
  { hanzi: "已经", pinyin: "yǐjīng", meaning: "이미" },
  { hanzi: "意思", pinyin: "yìsi", meaning: "의미" },
  { hanzi: "因为", pinyin: "yīnwèi", meaning: "왜냐하면" },
  { hanzi: "所以", pinyin: "suǒyǐ", meaning: "그래서" },
  { hanzi: "阴", pinyin: "yīn", meaning: "흐리다" },
  { hanzi: "游泳", pinyin: "yóuyǒng", meaning: "수영하다" },
  { hanzi: "右边", pinyin: "yòubian", meaning: "오른쪽" },
  { hanzi: "鱼", pinyin: "yú", meaning: "물고기" },
  { hanzi: "远", pinyin: "yuǎn", meaning: "멀다" },
  { hanzi: "运动", pinyin: "yùndòng", meaning: "운동하다" },
  { hanzi: "再", pinyin: "zài", meaning: "다시" },
  { hanzi: "早上", pinyin: "zǎoshang", meaning: "아침" },
  { hanzi: "丈夫", pinyin: "zhàngfu", meaning: "남편" },
  { hanzi: "找", pinyin: "zhǎo", meaning: "찾다" },
  { hanzi: "着", pinyin: "zhe", meaning: "~하고 있다 (상태 지속)" },
  { hanzi: "真", pinyin: "zhēn", meaning: "정말" },
  { hanzi: "正在", pinyin: "zhèngzài", meaning: "마침 ~하고 있다" },
  { hanzi: "知道", pinyin: "zhīdào", meaning: "알다" },
  { hanzi: "准备", pinyin: "zhǔnbèi", meaning: "준비하다" },
  { hanzi: "自行车", pinyin: "zìxíngchē", meaning: "자전거" },
  { hanzi: "走", pinyin: "zǒu", meaning: "걷다, 가다" },
  { hanzi: "最", pinyin: "zuì", meaning: "가장" },
  { hanzi: "左边", pinyin: "zuǒbian", meaning: "왼쪽" }
];
