const hsk4Words = [
  { hanzi: "爱情", pinyin: "àiqíng", meaning: "사랑" },
  { hanzi: "安排", pinyin: "ānpái", meaning: "안배하다, 계획하다" },
  { hanzi: "安全", pinyin: "ānquán", meaning: "안전하다" },
  { hanzi: "按时", pinyin: "ànshí", meaning: "제때에" },
  { hanzi: "按照", pinyin: "ànzhào", meaning: "~에 따라서" },
  { hanzi: "百分之", pinyin: "bǎifēnzhī", meaning: "퍼센트 (%)" },
  { hanzi: "棒", pinyin: "bàng", meaning: "훌륭하다" },
  { hanzi: "包子", pinyin: "bāozi", meaning: "만두" },
  { hanzi: "保护", pinyin: "bǎohù", meaning: "보호하다" },
  { hanzi: "保证", pinyin: "bǎozhèng", meaning: "보증하다, 장담하다" },
  { hanzi: "报名", pinyin: "bàomíng", meaning: "신청하다" },
  { hanzi: "抱", pinyin: "bào", meaning: "안다, 포옹하다" },
  { hanzi: "抱歉", pinyin: "bàoqiàn", meaning: "미안하게 생각하다" },
  { hanzi: "倍", pinyin: "bèi", meaning: "배 (곱절)" },
  { hanzi: "本来", pinyin: "běnlái", meaning: "본래, 원래" },
  { hanzi: "笨", pinyin: "bèn", meaning: "멍청하다, 바보같다" },
  { hanzi: "比如", pinyin: "bǐrú", meaning: "예를 들어" },
  { hanzi: "毕业", pinyin: "bìyè", meaning: "졸업하다" },
  { hanzi: "遍", pinyin: "biàn", meaning: "번 (동작의 횟수)" },
  { hanzi: "标准", pinyin: "biāozhǔn", meaning: "표준, 기준" },
  { hanzi: "表格", pinyin: "biǎogé", meaning: "양식, 표" },
  { hanzi: "表示", pinyin: "biǎoshì", meaning: "표시하다, 나타내다" },
  { hanzi: "表演", pinyin: "biǎoyǎn", meaning: "공연하다, 연기하다" },
  { hanzi: "表扬", pinyin: "biǎoyáng", meaning: "칭찬하다" },
  { hanzi: "饼干", pinyin: "bǐnggān", meaning: "비스킷, 과자" },
  { hanzi: "并且", pinyin: "bìngqiě", meaning: "게다가, 그리고" },
  { hanzi: "博士", pinyin: "bóshì", meaning: "박사" },
  { hanzi: "不过", pinyin: "búguò", meaning: "그러나, 하지만" },
  { hanzi: "不得不", pinyin: "bùdébù", meaning: "어쩔 수 없이 ~하다" },
  { hanzi: "不管", pinyin: "bùguǎn", meaning: "~에 관계없이" },
  { hanzi: "不仅", pinyin: "bùjǐn", meaning: "~일 뿐만 아니라" },
  { hanzi: "部分", pinyin: "bùfen", meaning: "부분" },
  { hanzi: "擦", pinyin: "cā", meaning: "닦다" },
  { hanzi: "猜", pinyin: "cāi", meaning: "추측하다" },
  { hanzi: "材料", pinyin: "cáiliào", meaning: "자료, 재료" },
  { hanzi: "参观", pinyin: "cānguān", meaning: "참관하다" },
  { hanzi: "餐厅", pinyin: "cāntīng", meaning: "식당, 레스토랑" },
  { hanzi: "厕所", pinyin: "cèsuǒ", meaning: "화장실" },
  { hanzi: "差不多", pinyin: "chàbuduō", meaning: "거의 비슷하다" },
  { hanzi: "长城", pinyin: "Chángchéng", meaning: "만리장성" },
  { hanzi: "长江", pinyin: "Chángjiāng", meaning: "창장 (양쯔강)" },
  { hanzi: "尝", pinyin: "cháng", meaning: "맛보다" },
  { hanzi: "场", pinyin: "chǎng", meaning: "장, 마당 (양사)" },
  { hanzi: "超过", pinyin: "chāoguò", meaning: "초과하다, 넘다" },
  { hanzi: "吵", pinyin: "chǎo", meaning: "시끄럽다, 다투다" },
  { hanzi: "成功", pinyin: "chénggōng", meaning: "성공하다" },
  { hanzi: "成为", pinyin: "chéngwéi", meaning: "~이 되다" },
  { hanzi: "诚实", pinyin: "chéngshí", meaning: "정직하다" },
  { hanzi: "乘坐", pinyin: "chéngzuò", meaning: "탑승하다" },
  { hanzi: "吃惊", pinyin: "chījīng", meaning: "놀라다" },
  { hanzi: "重新", pinyin: "chóngxīn", meaning: "다시, 새로" },
  { hanzi: "抽烟", pinyin: "chōuyān", meaning: "담배를 피우다" },
  { hanzi: "出差", pinyin: "chūchāi", meaning: "출장가다" },
  { hanzi: "出发", pinyin: "chūfā", meaning: "출발하다" },
  { hanzi: "出生", pinyin: "chūshēng", meaning: "태어나다" },
  { hanzi: "出现", pinyin: "chūxiàn", meaning: "나타나다" },
  { hanzi: "厨房", pinyin: "chúfáng", meaning: "주방, 부엌" },
  { hanzi: "传真", pinyin: "chuánzhēn", meaning: "팩스" },
  { hanzi: "窗户", pinyin: "chuānghu", meaning: "창문" },
  { hanzi: "词语", pinyin: "cíyǔ", meaning: "단어, 어휘" },
  { hanzi: "从来", pinyin: "cónglái", meaning: "지금껏, 여태껏" },
  { hanzi: "粗心", pinyin: "cūxīn", meaning: "부주의하다" },
  { hanzi: "存", pinyin: "cún", meaning: "보관하다, 저축하다" },
  { hanzi: "错误", pinyin: "cuòwù", meaning: "오류, 잘못" },
  { hanzi: "答案", pinyin: "dá'àn", meaning: "정답" },
  { hanzi: "打扮", pinyin: "dǎban", meaning: "꾸미다, 단장하다" },
  { hanzi: "打扰", pinyin: "dǎrǎo", meaning: "방해하다" },
  { hanzi: "打印", pinyin: "dǎyìn", meaning: "프린트하다, 인쇄하다" },
  { hanzi: "打招呼", pinyin: "dǎ zhāohu", meaning: "인사하다" },
  { hanzi: "打折", pinyin: "dǎzhé", meaning: "할인하다" },
  { hanzi: "打针", pinyin: "dǎzhēn", meaning: "주사를 맞다" },
  { hanzi: "大概", pinyin: "dàgài", meaning: "대략, 아마도" },
  { hanzi: "大使馆", pinyin: "dàshǐguǎn", meaning: "대사관" },
  { hanzi: "大约", pinyin: "dàyuē", meaning: "대략" },
  { hanzi: "大夫", pinyin: "dàifu", meaning: "의사" },
  { hanzi: "戴", pinyin: "dài", meaning: "착용하다 (모자, 안경 등)" },
  { hanzi: "当时", pinyin: "dāngshí", meaning: "당시" },
  { hanzi: "刀", pinyin: "dāo", meaning: "칼" },
  { hanzi: "导游", pinyin: "dǎoyóu", meaning: "가이드" },
  { hanzi: "倒", pinyin: "dǎo", meaning: "넘어지다" },
  { hanzi: "到处", pinyin: "dàochù", meaning: "곳곳에, 도처에" },
  { hanzi: "到底", pinyin: "dàodǐ", meaning: "도대체, 마침내" },
  { hanzi: "道歉", pinyin: "dàoqiàn", meaning: "사과하다" },
  { hanzi: "得意", pinyin: "déyì", meaning: "득의양양하다, 우쭐하다" },
  { hanzi: "得", pinyin: "děi", meaning: "~해야 한다" },
  { hanzi: "登机牌", pinyin: "dēngjīpái", meaning: "탑승권" },
  { hanzi: "底", pinyin: "dǐ", meaning: "밑, 끝" },
  { hanzi: "地点", pinyin: "dìdiǎn", meaning: "장소, 지점" },
  { hanzi: "地球", pinyin: "dìqiú", meaning: "지구" },
  { hanzi: "地址", pinyin: "dìzhǐ", meaning: "주소" },
  { hanzi: "调查", pinyin: "diàochá", meaning: "조사하다" },
  { hanzi: "掉", pinyin: "diào", meaning: "떨어지다, 잃다" },
  { hanzi: "丢", pinyin: "diū", meaning: "잃어버리다" },
  { hanzi: "动作", pinyin: "dòngzuò", meaning: "동작" },
  { hanzi: "堵车", pinyin: "dǔchē", meaning: "차가 막히다" },
  { hanzi: "肚子", pinyin: "dùzi", meaning: "배 (신체)" },
  { hanzi: "断", pinyin: "duàn", meaning: "끊어지다" },
  { hanzi: "对话", pinyin: "duìhuà", meaning: "대화하다" },
  { hanzi: "反对", pinyin: "fǎnduì", meaning: "반대하다" },
  { hanzi: "反映", pinyin: "fǎnyìng", meaning: "반영하다" },
  { hanzi: "范围", pinyin: "fànwéi", meaning: "범위" },
  { hanzi: "方向", pinyin: "fāngxiàng", meaning: "방향" },
  { hanzi: "放弃", pinyin: "fàngqì", meaning: "포기하다" },
  { hanzi: "放暑假", pinyin: "fàng shǔjià", meaning: "여름방학을 하다" },
  { hanzi: "放松", pinyin: "fàngsōng", meaning: "긴장을 풀다" },
  { hanzi: "费用", pinyin: "fèiyòng", meaning: "비용" },
  { hanzi: "份", pinyin: "fèn", meaning: "부, 몫 (양사)" },
  { hanzi: "丰富", pinyin: "fēngfù", meaning: "풍부하다" },
  { hanzi: "否则", pinyin: "fǒuzé", meaning: "그렇지 않으면" },
  { hanzi: "符合", pinyin: "fúhé", meaning: "부합하다" },
  { hanzi: "父亲", pinyin: "fùqīn", meaning: "아버지" },
  { hanzi: "付款", pinyin: "fùkuǎn", meaning: "지불하다" },
  { hanzi: "负责", pinyin: "fùzé", meaning: "책임지다" },
  { hanzi: "复杂", pinyin: "fùzá", meaning: "복잡하다" },
  { hanzi: "富", pinyin: "fù", meaning: "부유하다" },
  { hanzi: "改变", pinyin: "gǎibiàn", meaning: "바꾸다, 변화하다" },
  { hanzi: "干杯", pinyin: "gānbēi", meaning: "건배하다" },
  { hanzi: "赶", pinyin: "gǎn", meaning: "서두르다, 쫓다" },
  { hanzi: "敢", pinyin: "gǎn", meaning: "감히 ~하다" },
  { hanzi: "感动", pinyin: "gǎndòng", meaning: "감동하다" },
  { hanzi: "感觉", pinyin: "gǎnjué", meaning: "느낌, 느끼다" },
  { hanzi: "感情", pinyin: "gǎnqíng", meaning: "감정" },
  { hanzi: "感谢", pinyin: "gǎnxiè", meaning: "감사하다" },
  { hanzi: "干", pinyin: "gàn", meaning: "하다, 일하다" },
  { hanzi: "刚", pinyin: "gāng", meaning: "방금, 막" },
  { hanzi: "高速公路", pinyin: "gāosù gōnglù", meaning: "고속도로" },
  { hanzi: "胳膊", pinyin: "gēbo", meaning: "팔" },
  { hanzi: "各", pinyin: "gè", meaning: "각, 각각" },
  { hanzi: "工资", pinyin: "gōngzī", meaning: "임금, 월급" },
  { hanzi: "公里", pinyin: "gōnglǐ", meaning: "킬로미터" },
  { hanzi: "功夫", pinyin: "gōngfu", meaning: "쿵푸, 시간/노력" },
  { hanzi: "共同", pinyin: "gòngtóng", meaning: "공동의" },
  { hanzi: "购物", pinyin: "gòuwù", meaning: "쇼핑하다" },
  { hanzi: "够", pinyin: "gòu", meaning: "충분하다" },
  { hanzi: "估计", pinyin: "gūjì", meaning: "추측하다, 평가하다" },
  { hanzi: "孤单", pinyin: "gūdān", meaning: "외롭다, 고독하다" },
  { hanzi: "鼓励", pinyin: "gǔlì", meaning: "격려하다" },
  { hanzi: "鼓掌", pinyin: "gǔzhǎng", meaning: "박수치다" },
  { hanzi: "故意", pinyin: "gùyì", meaning: "고의로" },
  { hanzi: "顾客", pinyin: "gùkè", meaning: "고객" },
  { hanzi: "挂", pinyin: "guà", meaning: "걸다 (전화를 끊다)" },
  { hanzi: "关键", pinyin: "guānjiàn", meaning: "관건, 핵심" },
  { hanzi: "观众", pinyin: "guānzhòng", meaning: "관중" },
  { hanzi: "管理", pinyin: "guǎnlǐ", meaning: "관리하다" },
  { hanzi: "光", pinyin: "guāng", meaning: "빛, 남김없이" },
  { hanzi: "广播", pinyin: "guǎngbō", meaning: "방송" },
  { hanzi: "广告", pinyin: "guǎnggào", meaning: "광고" },
  { hanzi: "逛", pinyin: "guàng", meaning: "거닐다, 구경하다" },
  { hanzi: "规定", pinyin: "guīdìng", meaning: "규정하다" },
  { hanzi: "国籍", pinyin: "guójí", meaning: "국적" },
  { hanzi: "国际", pinyin: "guójì", meaning: "국제의" },
  { hanzi: "果然", pinyin: "guǒrán", meaning: "과연" },
  { hanzi: "过程", pinyin: "guòchéng", meaning: "과정" },
  { hanzi: "海洋", pinyin: "hǎiyáng", meaning: "해양, 바다" },
  { hanzi: "害羞", pinyin: "hàixiū", meaning: "부끄러워하다" },
  { hanzi: "寒假", pinyin: "hánjià", meaning: "겨울방학" },
  { hanzi: "汗", pinyin: "hàn", meaning: "땀" },
  { hanzi: "好处", pinyin: "hǎochu", meaning: "이점, 장점" },
  { hanzi: "好像", pinyin: "hǎoxiàng", meaning: "마치 ~인 것 같다" },
  { hanzi: "号码", pinyin: "hàomǎ", meaning: "번호" },
  { hanzi: "合格", pinyin: "hégé", meaning: "합격하다, 규격에 맞다" },
  { hanzi: "合适", pinyin: "héshì", meaning: "적합하다" },
  { hanzi: "盒子", pinyin: "hézi", meaning: "상자, 곽" },
  { hanzi: "后悔", pinyin: "hòuhuǐ", meaning: "후회하다" },
  { hanzi: "厚", pinyin: "hòu", meaning: "두껍다" },
  { hanzi: "互联网", pinyin: "hùliánwǎng", meaning: "인터넷" },
  { hanzi: "互相", pinyin: "hùxiāng", meaning: "서로" },
  { hanzi: "护士", pinyin: "hùshi", meaning: "간호사" },
  { hanzi: "怀疑", pinyin: "huáiyí", meaning: "의심하다" },
  { hanzi: "回忆", pinyin: "huíyì", meaning: "추억, 회상하다" },
  { hanzi: "活动", pinyin: "huódòng", meaning: "활동하다" },
  { hanzi: "活泼", pinyin: "huópō", meaning: "활발하다" },
  { hanzi: "火", pinyin: "huǒ", meaning: "불, 화나다" },
  { hanzi: "获得", pinyin: "huòdé", meaning: "얻다, 획득하다" },
  { hanzi: "积极", pinyin: "jījí", meaning: "적극적이다" },
  { hanzi: "积累", pinyin: "jīlěi", meaning: "축적하다" },
  { hanzi: "基础", pinyin: "jīchǔ", meaning: "기초" },
  { hanzi: "激动", pinyin: "jīdòng", meaning: "감동하다, 흥분하다" },
  { hanzi: "及时", pinyin: "jíshí", meaning: "제때에" },
  { hanzi: "即使", pinyin: "jíshǐ", meaning: "설령 ~하더라도" },
  { hanzi: "计划", pinyin: "jìhuà", meaning: "계획" },
  { hanzi: "计算机", pinyin: "jìsuànjī", meaning: "컴퓨터" },
  { hanzi: "记者", pinyin: "jìzhě", meaning: "기자" },
  { hanzi: "技术", pinyin: "jìshù", meaning: "기술" },
  { hanzi: "既然", pinyin: "jìrán", meaning: "기왕 이렇게 된 바에" },
  { hanzi: "继续", pinyin: "jìxù", meaning: "계속하다" },
  { hanzi: "寄", pinyin: "jì", meaning: "부치다 (우편물)" },
  { hanzi: "加班", pinyin: "jiābān", meaning: "야근하다" },
  { hanzi: "加油站", pinyin: "jiāyóuzhàn", meaning: "주유소" },
  { hanzi: "家具", pinyin: "jiājù", meaning: "가구" },
  { hanzi: "假", pinyin: "jiǎ", meaning: "가짜의" },
  { hanzi: "价格", pinyin: "jiàgé", meaning: "가격" },
  { hanzi: "坚持", pinyin: "jiānchí", meaning: "견지하다, 고집하다" },
  { hanzi: "减肥", pinyin: "jiǎnféi", meaning: "다이어트하다" },
  { hanzi: "减少", pinyin: "jiǎnshǎo", meaning: "감소하다" },
  { hanzi: "建议", pinyin: "jiànyì", meaning: "건의하다" },
  { hanzi: "将来", pinyin: "jiānglái", meaning: "장래, 미래" },
  { hanzi: "奖金", pinyin: "jiǎngjīn", meaning: "상금, 보너스" },
  { hanzi: "降低", pinyin: "jiàngdī", meaning: "낮추다, 떨어지다" },
  { hanzi: "交", pinyin: "jiāo", meaning: "사귀다, 제출하다" },
  { hanzi: "交流", pinyin: "jiāoliú", meaning: "교류하다" },
  { hanzi: "交通", pinyin: "jiāotōng", meaning: "교통" },
  { hanzi: "郊区", pinyin: "jiāoqū", meaning: "교외" },
  { hanzi: "骄傲", pinyin: "jiāo'ào", meaning: "교만하다, 자랑스럽다" },
  { hanzi: "饺子", pinyin: "jiǎozi", meaning: "만두 (교자)" },
  { hanzi: "教授", pinyin: "jiàoshòu", meaning: "교수" },
  { hanzi: "教育", pinyin: "jiàoyù", meaning: "교육하다" },
  { hanzi: "接受", pinyin: "jiēshòu", meaning: "받아들이다" },
  { hanzi: "接着", pinyin: "jiēzhe", meaning: "이어서, 계속해서" },
  { hanzi: "节约", pinyin: "jiéyuē", meaning: "절약하다" },
  { hanzi: "结果", pinyin: "jiéguǒ", meaning: "결과" },
  { hanzi: "解释", pinyin: "jiěshì", meaning: "해석하다, 설명하다" },
  { hanzi: "尽管", pinyin: "jǐnguǎn", meaning: "비록 ~일지라도" },
  { hanzi: "紧张", pinyin: "jǐnzhāng", meaning: "긴장하다" },
  { hanzi: "进行", pinyin: "jìnxíng", meaning: "진행하다" },
  { hanzi: "京剧", pinyin: "jīngjù", meaning: "경극" },
  { hanzi: "经济", pinyin: "jīngjì", meaning: "경제" },
  { hanzi: "经历", pinyin: "jīnglì", meaning: "경험, 겪다" },
  { hanzi: "经验", pinyin: "jīngyàn", meaning: "경험" },
  { hanzi: "精彩", pinyin: "jīngcǎi", meaning: "훌륭하다, 멋지다" },
  { hanzi: "景色", pinyin: "jǐngsè", meaning: "경치" },
  { hanzi: "警察", pinyin: "jǐngchá", meaning: "경찰" },
  { hanzi: "竞争", pinyin: "jìngzhēng", meaning: "경쟁하다" },
  { hanzi: "竟然", pinyin: "jìngrán", meaning: "뜻밖에도" },
  { hanzi: "镜子", pinyin: "jìngzi", meaning: "거울" },
  { hanzi: "究竟", pinyin: "jiūjìng", meaning: "도대체, 결국" },
  { hanzi: "举", pinyin: "jǔ", meaning: "들다 (손을)" },
  { hanzi: "举办", pinyin: "jǔbàn", meaning: "개최하다" },
  { hanzi: "举行", pinyin: "jǔxíng", meaning: "거행하다" },
  { hanzi: "拒绝", pinyin: "jùjué", meaning: "거절하다" },
  { hanzi: "距离", pinyin: "jùlí", meaning: "거리, 떨어져 있다" },
  { hanzi: "聚会", pinyin: "jùhuì", meaning: "모임, 회식" },
  { hanzi: "开玩笑", pinyin: "kāi wánxiào", meaning: "농담하다" },
  { hanzi: "开心", pinyin: "kāixīn", meaning: "즐겁다" },
  { hanzi: "看法", pinyin: "kànfǎ", meaning: "견해, 생각" },
  { hanzi: "考虑", pinyin: "kǎolǜ", meaning: "고려하다" },
  { hanzi: "烤鸭", pinyin: "kǎoyā", meaning: "카오야 (오리구이)" },
  { hanzi: "科学", pinyin: "kēxué", meaning: "과학" },
  { hanzi: "棵", pinyin: "kē", meaning: "그루 (나무 양사)" },
  { hanzi: "咳嗽", pinyin: "késou", meaning: "기침하다" },
  { hanzi: "可怜", pinyin: "kělián", meaning: "가엾다, 불쌍하다" },
  { hanzi: "可是", pinyin: "kěshì", meaning: "그러나" },
  { hanzi: "可惜", pinyin: "kěxī", meaning: "아쉽다, 안타깝다" },
  { hanzi: "客厅", pinyin: "kètīng", meaning: "거실" },
  { hanzi: "肯定", pinyin: "kěndìng", meaning: "틀림없이, 확실하다" },
  { hanzi: "空", pinyin: "kōng", meaning: "비다, 헛되다" },
  { hanzi: "空气", pinyin: "kōngqì", meaning: "공기" },
  { hanzi: "恐怕", pinyin: "kǒngpà", meaning: "아마도, 두렵건대" },
  { hanzi: "苦", pinyin: "kǔ", meaning: "쓰다 (맛)" },
  { hanzi: "矿泉水", pinyin: "kuàngquánshuǐ", meaning: "생수" },
  { hanzi: "困", pinyin: "kùn", meaning: "졸리다" },
  { hanzi: "困难", pinyin: "kùnnan", meaning: "어려움, 곤란하다" },
  { hanzi: "垃圾桶", pinyin: "lājītǒng", meaning: "쓰레기통" },
  { hanzi: "拉", pinyin: "lā", meaning: "당기다" },
  { hanzi: "辣", pinyin: "là", meaning: "맵다" },
  { hanzi: "来不及", pinyin: "láibují", meaning: "시간이 촉박하다, 늦다" },
  { hanzi: "来得及", pinyin: "láidejí", meaning: "시간이 충분하다, 댈 수 있다" },
  { hanzi: "来自", pinyin: "láizì", meaning: "~에서 오다" },
  { hanzi: "懒", pinyin: "lǎn", meaning: "게으르다" },
  { hanzi: "浪费", pinyin: "làngfèi", meaning: "낭비하다" },
  { hanzi: "浪漫", pinyin: "làngmàn", meaning: "낭만적이다" },
  { hanzi: "老虎", pinyin: "lǎohǔ", meaning: "호랑이" },
  { hanzi: "理发", pinyin: "lǐfà", meaning: "이발하다" },
  { hanzi: "理解", pinyin: "lǐjiě", meaning: "이해하다" },
  { hanzi: "理想", pinyin: "lǐxiǎng", meaning: "이상적이다" },
  { hanzi: "礼貌", pinyin: "lǐmào", meaning: "예의 바르다" },
  { hanzi: "厉害", pinyin: "lìhai", meaning: "대단하다, 심각하다" },
  { hanzi: "力气", pinyin: "lìqi", meaning: "힘" },
  { hanzi: "例如", pinyin: "lìrú", meaning: "예를 들어" },
  { hanzi: "俩", pinyin: "liǎ", meaning: "두 사람 (둘)" },
  { hanzi: "连", pinyin: "lián", meaning: "조차도" },
  { hanzi: "联系", pinyin: "liánxì", meaning: "연락하다" },
  { hanzi: "凉快", pinyin: "liángkuai", meaning: "시원하다" },
  { hanzi: "零钱", pinyin: "língqián", meaning: "잔돈" },
  { hanzi: "另外", pinyin: "lìngwài", meaning: "그 밖에, 또" },
  { hanzi: "留", pinyin: "liú", meaning: "머무르다, 남기다" },
  { hanzi: "流利", pinyin: "liúlì", meaning: "유창하다" },
  { hanzi: "流行", pinyin: "liúxíng", meaning: "유행하다" },
  { hanzi: "旅行", pinyin: "lǚxíng", meaning: "여행하다" },
  { hanzi: "律师", pinyin: "lǜshī", meaning: "변호사" },
  { hanzi: "麻烦", pinyin: "máfan", meaning: "번거롭다, 귀찮게 하다" },
  { hanzi: "马虎", pinyin: "mǎhu", meaning: "덜렁거리다, 부주의하다" },
  { hanzi: "满", pinyin: "mǎn", meaning: "가득 차다" },
  { hanzi: "毛", pinyin: "máo", meaning: "털, 10전 (돈)" },
  { hanzi: "毛巾", pinyin: "máojīn", meaning: "수건" },
  { hanzi: "美丽", pinyin: "měilì", meaning: "아름답다" },
  { hanzi: "梦", pinyin: "mèng", meaning: "꿈" },
  { hanzi: "迷路", pinyin: "mílù", meaning: "길을 잃다" },
  { hanzi: "密码", pinyin: "mìmǎ", meaning: "비밀번호" },
  { hanzi: "免费", pinyin: "miǎnfèi", meaning: "무료의" },
  { hanzi: "秒", pinyin: "miǎo", meaning: "초 (시간)" },
  { hanzi: "民族", pinyin: "mínzú", meaning: "민족" },
  { hanzi: "母亲", pinyin: "mǔqīn", meaning: "어머니" },
  { hanzi: "目的", pinyin: "mùdì", meaning: "목적" },
  { hanzi: "耐心", pinyin: "nàixīn", meaning: "인내심" },
  { hanzi: "难道", pinyin: "nándào", meaning: "설마 ~란 말인가" },
  { hanzi: "难受", pinyin: "nánshòu", meaning: "참기 힘들다, 고통스럽다" },
  { hanzi: "内", pinyin: "nèi", meaning: "내, 안" },
  { hanzi: "内容", pinyin: "nèiróng", meaning: "내용" },
  { hanzi: "能力", pinyin: "nénglì", meaning: "능력" },
  { hanzi: "年龄", pinyin: "niánlíng", meaning: "연령, 나이" },
  { hanzi: "弄", pinyin: "nòng", meaning: "만들다, 하다" },
  { hanzi: "暖和", pinyin: "nuǎnhuo", meaning: "따뜻하다" },
  { hanzi: "偶尔", pinyin: "ǒu'ěr", meaning: "때때로, 가끔" },
  { hanzi: "排队", pinyin: "páiduì", meaning: "줄을 서다" },
  { hanzi: "排列", pinyin: "páiliè", meaning: "배열하다" },
  { hanzi: "判断", pinyin: "pànduàn", meaning: "판단하다" },
  { hanzi: "陪", pinyin: "péi", meaning: "모시다, 동반하다" },
  { hanzi: "批评", pinyin: "pīpíng", meaning: "비판하다, 꾸짖다" },
  { hanzi: "皮肤", pinyin: "pífū", meaning: "피부" },
  { hanzi: "脾气", pinyin: "píqi", meaning: "성질, 화" },
  { hanzi: "篇", pinyin: "piān", meaning: "편 (글을 세는 양사)" },
  { hanzi: "骗", pinyin: "piàn", meaning: "속이다" },
  { hanzi: "乒乓球", pinyin: "pīngpāngqiú", meaning: "탁구" },
  { hanzi: "平时", pinyin: "píngshí", meaning: "평소" },
  { hanzi: "破", pinyin: "pò", meaning: "깨지다, 찢어지다" },
  { hanzi: "葡萄", pinyin: "pútao", meaning: "포도" },
  { hanzi: "普遍", pinyin: "pǔbiàn", meaning: "보편적이다" },
  { hanzi: "其次", pinyin: "qícì", meaning: "그 다음으로" },
  { hanzi: "其中", pinyin: "qízhōng", meaning: "그 중" },
  { hanzi: "起来", pinyin: "qǐlái", meaning: "일어나다, ~하기 시작하다" },
  { hanzi: "气候", pinyin: "qìhòu", meaning: "기후" },
  { hanzi: "千万", pinyin: "qiānwàn", meaning: "천만, 제발 (꼭)" },
  { hanzi: "签证", pinyin: "qiānzhèng", meaning: "비자" },
  { hanzi: "敲", pinyin: "qiāo", meaning: "두드리다" },
  { hanzi: "桥", pinyin: "qiáo", meaning: "다리 (건축물)" },
  { hanzi: "巧克力", pinyin: "qiǎokèlì", meaning: "초콜릿" },
  { hanzi: "亲戚", pinyin: "qīnqi", meaning: "친척" },
  { hanzi: "轻", pinyin: "qīng", meaning: "가볍다" },
  { hanzi: "轻松", pinyin: "qīngsōng", meaning: "수월하다, 홀가분하다" },
  { hanzi: "情况", pinyin: "qíngkuàng", meaning: "상황" },
  { hanzi: "穷", pinyin: "qióng", meaning: "가난하다" },
  { hanzi: "区别", pinyin: "qūbié", meaning: "구별, 차이" },
  { hanzi: "取", pinyin: "qǔ", meaning: "취하다, 찾다" },
  { hanzi: "全部", pinyin: "quánbù", meaning: "전부" },
  { hanzi: "缺点", pinyin: "quēdiǎn", meaning: "단점" },
  { hanzi: "缺少", pinyin: "quēshǎo", meaning: "부족하다" },
  { hanzi: "却", pinyin: "què", meaning: "오히려" },
  { hanzi: "确实", pinyin: "quèshí", meaning: "확실히" },
  { hanzi: "然而", pinyin: "rán'ér", meaning: "그러나" },
  { hanzi: "热闹", pinyin: "rènao", meaning: "번화하다, 시끌벅적하다" },
  { hanzi: "任何", pinyin: "rènhé", meaning: "어떠한" },
  { hanzi: "任务", pinyin: "rènwu", meaning: "임무" },
  { hanzi: "扔", pinyin: "rēng", meaning: "던지다, 버리다" },
  { hanzi: "仍然", pinyin: "réngrán", meaning: "여전히" },
  { hanzi: "日记", pinyin: "rìjì", meaning: "일기" },
  { hanzi: "入口", pinyin: "rùkǒu", meaning: "입구" },
  { hanzi: "散步", pinyin: "sànbù", meaning: "산책하다" },
  { hanzi: "森林", pinyin: "sēnlín", meaning: "삼림, 숲" },
  { hanzi: "沙发", pinyin: "shāfā", meaning: "소파" },
  { hanzi: "伤心", pinyin: "shāngxīn", meaning: "상심하다, 슬프다" },
  { hanzi: "商量", pinyin: "shāngliang", meaning: "상의하다" },
  { hanzi: "稍微", pinyin: "shāowēi", meaning: "조금, 약간" },
  { hanzi: "勺子", pinyin: "sháozi", meaning: "숟가락" },
  { hanzi: "社会", pinyin: "shèhuì", meaning: "사회" },
  { hanzi: "申请", pinyin: "shēnqǐng", meaning: "신청하다" },
  { hanzi: "深", pinyin: "shēn", meaning: "깊다" },
  { hanzi: "甚至", pinyin: "shènzhì", meaning: "심지어" },
  { hanzi: "生活", pinyin: "shēnghuó", meaning: "생활하다" },
  { hanzi: "生命", pinyin: "shēngmìng", meaning: "생명" },
  { hanzi: "生意", pinyin: "shēngyì", meaning: "사업, 장사" },
  { hanzi: "省", pinyin: "shěng", meaning: "생략하다, 성 (행정구역)" },
  { hanzi: "剩", pinyin: "shèng", meaning: "남다" },
  { hanzi: "失败", pinyin: "shībài", meaning: "실패하다" },
  { hanzi: "失望", pinyin: "shīwàng", meaning: "실망하다" },
  { hanzi: "师傅", pinyin: "shīfu", meaning: "기사님, 사부" },
  { hanzi: "十分", pinyin: "shífēn", meaning: "매우" },
  { hanzi: "实际", pinyin: "shíjì", meaning: "실제" },
  { hanzi: "实在", pinyin: "shízài", meaning: "참으로, 솔직하다" },
  { hanzi: "使", pinyin: "shǐ", meaning: "~하게 하다" },
  { hanzi: "使用", pinyin: "shǐyòng", meaning: "사용하다" },
  { hanzi: "世纪", pinyin: "shìjì", meaning: "세기" },
  { hanzi: "是否", pinyin: "shìfǒu", meaning: "~인지 아닌지" },
  { hanzi: "适合", pinyin: "shìhé", meaning: "적합하다" },
  { hanzi: "适应", pinyin: "shìyìng", meaning: "적응하다" },
  { hanzi: "收", pinyin: "shōu", meaning: "받다, 거두다" },
  { hanzi: "收入", pinyin: "shōurù", meaning: "수입" },
  { hanzi: "收拾", pinyin: "shōushi", meaning: "정리하다" },
  { hanzi: "首都", pinyin: "shǒudū", meaning: "수도" },
  { hanzi: "首先", pinyin: "shǒuxiān", meaning: "우선" },
  { hanzi: "受不了", pinyin: "shòubuliǎo", meaning: "참을 수 없다" },
  { hanzi: "受到", pinyin: "shòudào", meaning: "받다 (추상적인 것)" },
  { hanzi: "售货员", pinyin: "shòuhuòyuán", meaning: "판매원" },
  { hanzi: "输", pinyin: "shū", meaning: "지다 (패배)" },
  { hanzi: "熟悉", pinyin: "shúxī", meaning: "익숙하다, 잘 알다" },
  { hanzi: "数量", pinyin: "shùliàng", meaning: "수량" },
  { hanzi: "数字", pinyin: "shùzì", meaning: "숫자" },
  { hanzi: "帅", pinyin: "shuài", meaning: "잘생기다" },
  { hanzi: "顺便", pinyin: "shùnbiàn", meaning: "하는 김에" },
  { hanzi: "顺利", pinyin: "shùnlì", meaning: "순조롭다" },
  { hanzi: "顺序", pinyin: "shùnxù", meaning: "순서" },
  { hanzi: "说明", pinyin: "shuōmíng", meaning: "설명하다" },
  { hanzi: "硕士", pinyin: "shuòshì", meaning: "석사" },
  { hanzi: "死", pinyin: "sǐ", meaning: "죽다" },
  { hanzi: "速度", pinyin: "sùdù", meaning: "속도" },
  { hanzi: "塑料袋", pinyin: "sùliàodài", meaning: "비닐봉지" },
  { hanzi: "酸", pinyin: "suān", meaning: "시다 (맛)" },
  { hanzi: "随便", pinyin: "suíbiàn", meaning: "마음대로" },
  { hanzi: "随着", pinyin: "suízhe", meaning: "~함에 따라" },
  { hanzi: "孙子", pinyin: "sūnzi", meaning: "손자" },
  { hanzi: "所有", pinyin: "suǒyǒu", meaning: "모든" },
  { hanzi: "台", pinyin: "tái", meaning: "대 (기계 양사)" },
  { hanzi: "抬", pinyin: "tái", meaning: "들다 (물건을)" },
  { hanzi: "态度", pinyin: "tàidu", meaning: "태도" },
  { hanzi: "谈", pinyin: "tán", meaning: "이야기하다" },
  { hanzi: "弹钢琴", pinyin: "tán gāngqín", meaning: "피아노를 치다" },
  { hanzi: "汤", pinyin: "tāng", meaning: "국, 탕" },
  { hanzi: "糖", pinyin: "táng", meaning: "사탕, 설탕" },
  { hanzi: "躺", pinyin: "tǎng", meaning: "눕다" },
  { hanzi: "趟", pinyin: "tàng", meaning: "번 (왕복 횟수)" },
  { hanzi: "讨论", pinyin: "tǎolùn", meaning: "토론하다" },
  { hanzi: "讨厌", pinyin: "tǎoyàn", meaning: "싫어하다, 밉다" },
  { hanzi: "特点", pinyin: "tèdiǎn", meaning: "특징" },
  { hanzi: "提", pinyin: "tí", meaning: "들다, 제기하다" },
  { hanzi: "提供", pinyin: "tígōng", meaning: "제공하다" },
  { hanzi: "提前", pinyin: "tíqián", meaning: "앞당기다" },
  { hanzi: "提醒", pinyin: "tíxǐng", meaning: "일깨우다, 상기시키다" },
  { hanzi: "填空", pinyin: "tiánkòng", meaning: "빈칸을 채우다" },
  { hanzi: "条件", pinyin: "tiáojiàn", meaning: "조건" },
  { hanzi: "停", pinyin: "tíng", meaning: "정지하다, 멈추다" },
  { hanzi: "挺", pinyin: "tǐng", meaning: "매우" },
  { hanzi: "通过", pinyin: "tōngguò", meaning: "통과하다, ~를 통하여" },
  { hanzi: "通知", pinyin: "tōngzhī", meaning: "통지하다" },
  { hanzi: "同情", pinyin: "tóngqíng", meaning: "동정하다" },
  { hanzi: "同时", pinyin: "tóngshí", meaning: "동시에" },
  { hanzi: "推", pinyin: "tuī", meaning: "밀다" },
  { hanzi: "推迟", pinyin: "tuīchí", meaning: "미루다, 연기하다" },
  { hanzi: "脱", pinyin: "tuō", meaning: "벗다" },
  { hanzi: "袜子", pinyin: "wàzi", meaning: "양말" },
  { hanzi: "完全", pinyin: "wánquán", meaning: "완전히" },
  { hanzi: "网球", pinyin: "wǎngqiú", meaning: "테니스" },
  { hanzi: "网站", pinyin: "wǎngzhàn", meaning: "웹사이트" },
  { hanzi: "往", pinyin: "wǎng", meaning: "~로 (방향)" },
  { hanzi: "往往", pinyin: "wǎngwǎng", meaning: "종종, 자주" },
  { hanzi: "危险", pinyin: "wēixiǎn", meaning: "위험하다" },
  { hanzi: "卫生间", pinyin: "wèishēngjiān", meaning: "화장실" },
  { hanzi: "味道", pinyin: "wèidào", meaning: "맛, 냄새" },
  { hanzi: "温度", pinyin: "wēndù", meaning: "온도" },
  { hanzi: "文章", pinyin: "wénzhāng", meaning: "문장, 글" },
  { hanzi: "污染", pinyin: "wūrǎn", meaning: "오염되다" },
  { hanzi: "无", pinyin: "wú", meaning: "없다" },
  { hanzi: "无聊", pinyin: "wúliáo", meaning: "무료하다, 심심하다" },
  { hanzi: "无论", pinyin: "wúlùn", meaning: "~을 막론하고" },
  { hanzi: "误会", pinyin: "wùhuì", meaning: "오해하다" },
  { hanzi: "西红柿", pinyin: "xīhóngshì", meaning: "토마토" },
  { hanzi: "吸引", pinyin: "xīyǐn", meaning: "끌다, 유인하다" },
  { hanzi: "咸", pinyin: "xián", meaning: "짜다 (맛)" },
  { hanzi: "现金", pinyin: "xiànjīn", meaning: "현금" },
  { hanzi: "羡慕", pinyin: "xiànmù", meaning: "부러워하다" },
  { hanzi: "相反", pinyin: "xiāngfǎn", meaning: "상반되다" },
  { hanzi: "相同", pinyin: "xiāngtóng", meaning: "같다" },
  { hanzi: "香", pinyin: "xiāng", meaning: "향기롭다" },
  { hanzi: "详细", pinyin: "xiángxì", meaning: "상세하다" },
  { hanzi: "响", pinyin: "xiǎng", meaning: "울리다, 소리나다" },
  { hanzi: "橡皮", pinyin: "xiàngpí", meaning: "지우개" },
  { hanzi: "消息", pinyin: "xiāoxi", meaning: "소식" },
  { hanzi: "小吃", pinyin: "xiǎochī", meaning: "간식" },
  { hanzi: "小伙子", pinyin: "xiǎohuǒzi", meaning: "젊은이" },
  { hanzi: "小说", pinyin: "xiǎoshuō", meaning: "소설" },
  { hanzi: "笑话", pinyin: "xiàohua", meaning: "농담, 웃음거리" },
  { hanzi: "效果", pinyin: "xiàoguǒ", meaning: "효과" },
  { hanzi: "心情", pinyin: "xīnqíng", meaning: "심정, 기분" },
  { hanzi: "辛苦", pinyin: "xīnkǔ", meaning: "수고하다, 고생하다" },
  { hanzi: "信封", pinyin: "xìnfēng", meaning: "편지 봉투" },
  { hanzi: "信息", pinyin: "xìnxī", meaning: "정보, 메시지" },
  { hanzi: "信心", pinyin: "xìnxīn", meaning: "자신감" },
  { hanzi: "兴奋", pinyin: "xīngfèn", meaning: "흥분하다" },
  { hanzi: "行", pinyin: "xíng", meaning: "좋다, 걷다" },
  { hanzi: "醒", pinyin: "xǐng", meaning: "깨다" },
  { hanzi: "幸福", pinyin: "xìngfú", meaning: "행복하다" },
  { hanzi: "性别", pinyin: "xìngbié", meaning: "성별" },
  { hanzi: "性格", pinyin: "xìnggé", meaning: "성격" },
  { hanzi: "修", pinyin: "xiū", meaning: "고치다, 수리하다" },
  { hanzi: "许多", pinyin: "xǔduō", meaning: "허다한, 많은" },
  { hanzi: "学期", pinyin: "xuéqī", meaning: "학기" },
  { hanzi: "压力", pinyin: "yālì", meaning: "스트레스, 압력" },
  { hanzi: "呀", pinyin: "ya", meaning: "아 (감탄사)" },
  { hanzi: "牙膏", pinyin: "yágāo", meaning: "치약" },
  { hanzi: "亚洲", pinyin: "Yàzhōu", meaning: "아시아" },
  { hanzi: "严格", pinyin: "yángé", meaning: "엄격하다" },
  { hanzi: "严重", pinyin: "yánzhòng", meaning: "심각하다" },
  { hanzi: "研究", pinyin: "yánjiū", meaning: "연구하다" },
  { hanzi: "盐", pinyin: "yán", meaning: "소금" },
  { hanzi: "眼镜", pinyin: "yǎnjìng", meaning: "안경" },
  { hanzi: "演出", pinyin: "yǎnchū", meaning: "공연하다" },
  { hanzi: "演员", pinyin: "yǎnyuán", meaning: "배우" },
  { hanzi: "阳光", pinyin: "yángguāng", meaning: "햇빛" },
  { hanzi: "养成", pinyin: "yǎngchéng", meaning: "기르다, 양성하다" },
  { hanzi: "样子", pinyin: "yàngzi", meaning: "모양, 모습" },
  { hanzi: "邀请", pinyin: "yāoqǐng", meaning: "초대하다" },
  { hanzi: "要是", pinyin: "yàoshi", meaning: "만약 ~라면" },
  { hanzi: "钥匙", pinyin: "yàoshi", meaning: "열쇠" },
  { hanzi: "也许", pinyin: "yěxǔ", meaning: "어쩌면" },
  { hanzi: "叶子", pinyin: "yèzi", meaning: "나뭇잎" },
  { hanzi: "页", pinyin: "yè", meaning: "페이지" },
  { hanzi: "一切", pinyin: "yíqiè", meaning: "모든 것" },
  { hanzi: "以", pinyin: "yǐ", meaning: "~로써" },
  { hanzi: "以为", pinyin: "yǐwéi", meaning: "~라고 여기다 (오해)" },
  { hanzi: "艺术", pinyin: "yìshù", meaning: "예술" },
  { hanzi: "意见", pinyin: "yìjiàn", meaning: "의견" },
  { hanzi: "因此", pinyin: "yīncǐ", meaning: "그러므로" },
  { hanzi: "引起", pinyin: "yǐnqǐ", meaning: "야기하다, 일으키다" },
  { hanzi: "印象", pinyin: "yìnxiàng", meaning: "인상" },
  { hanzi: "赢", pinyin: "yíng", meaning: "이기다" },
  { hanzi: "应聘", pinyin: "yìngpìn", meaning: "지원하다, 응빙하다" },
  { hanzi: "永远", pinyin: "yǒngyuǎn", meaning: "영원히" },
  { hanzi: "勇敢", pinyin: "yǒnggǎn", meaning: "용감하다" },
  { hanzi: "优点", pinyin: "yōudiǎn", meaning: "장점" },
  { hanzi: "优秀", pinyin: "yōuxiù", meaning: "우수하다" },
  { hanzi: "幽默", pinyin: "yōumò", meaning: "유머러스하다" },
  { hanzi: "尤其", pinyin: "yóuqí", meaning: "특히" },
  { hanzi: "由", pinyin: "yóu", meaning: "~에 의해, ~부터" },
  { hanzi: "由于", pinyin: "yóuyú", meaning: "~때문에" },
  { hanzi: "邮局", pinyin: "yóujú", meaning: "우체국" },
  { hanzi: "友好", pinyin: "yǒuhǎo", meaning: "우호적이다" },
  { hanzi: "友谊", pinyin: "yǒuyì", meaning: "우정" },
  { hanzi: "有趣", pinyin: "yǒuqù", meaning: "재미있다" },
  { hanzi: "于是", pinyin: "yúshì", meaning: "그래서, 이리하여" },
  { hanzi: "愉快", pinyin: "yúkuài", meaning: "유쾌하다" },
  { hanzi: "与", pinyin: "yǔ", meaning: "~와 (과)" },
  { hanzi: "羽毛球", pinyin: "yǔmáoqiú", meaning: "배드민턴" },
  { hanzi: "语法", pinyin: "yǔfǎ", meaning: "문법" },
  { hanzi: "语言", pinyin: "yǔyán", meaning: "언어" },
  { hanzi: "预习", pinyin: "yùxí", meaning: "예습하다" },
  { hanzi: "原来", pinyin: "yuánlái", meaning: "원래" },
  { hanzi: "原谅", pinyin: "yuánliàng", meaning: "용서하다" },
  { hanzi: "原因", pinyin: "yuányīn", meaning: "원인" },
  { hanzi: "约会", pinyin: "yuēhuì", meaning: "데이트하다, 약속" },
  { hanzi: "阅读", pinyin: "yuèdú", meaning: "읽다, 독서하다" },
  { hanzi: "云", pinyin: "yún", meaning: "구름" },
  { hanzi: "允许", pinyin: "yǔnxǔ", meaning: "허락하다" },
  { hanzi: "杂志", pinyin: "zázhì", meaning: "잡지" },
  { hanzi: "咱们", pinyin: "zánmen", meaning: "우리 (화자, 청자 포함)" },
  { hanzi: "暂时", pinyin: "zànshí", meaning: "잠시, 임시로" },
  { hanzi: "脏", pinyin: "zāng", meaning: "더럽다" },
  { hanzi: "责任", pinyin: "zérèn", meaning: "책임" },
  { hanzi: "增加", pinyin: "zēngjiā", meaning: "증가하다" },
  { hanzi: "占", pinyin: "zhàn", meaning: "차지하다" },
  { hanzi: "招聘", pinyin: "zhāopìn", meaning: "모집하다" },
  { hanzi: "照", pinyin: "zhào", meaning: "비추다, ~에 따라" },
  { hanzi: "真正", pinyin: "zhēnzhèng", meaning: "진정한" },
  { hanzi: "整理", pinyin: "zhěnglǐ", meaning: "정리하다" },
  { hanzi: "正常", pinyin: "zhèngcháng", meaning: "정상적이다" },
  { hanzi: "正好", pinyin: "zhènghǎo", meaning: "마침, 딱 맞다" },
  { hanzi: "正确", pinyin: "zhèngquè", meaning: "정확하다" },
  { hanzi: "正式", pinyin: "zhèngshì", meaning: "정식의, 공식적인" },
  { hanzi: "证明", pinyin: "zhèngmíng", meaning: "증명하다" },
  { hanzi: "之", pinyin: "zhī", meaning: "~의" },
  { hanzi: "支持", pinyin: "zhīchí", meaning: "지지하다" },
  { hanzi: "知识", pinyin: "zhīshi", meaning: "지식" },
  { hanzi: "直接", pinyin: "zhíjiē", meaning: "직접적인" },
  { hanzi: "值得", pinyin: "zhíde", meaning: "~할 만한 가치가 있다" },
  { hanzi: "职业", pinyin: "zhíyè", meaning: "직업" },
  { hanzi: "植物", pinyin: "zhíwù", meaning: "식물" },
  { hanzi: "只好", pinyin: "zhǐhǎo", meaning: "부득이, 할 수 없이" },
  { hanzi: "只要", pinyin: "zhǐyào", meaning: "~하기만 하면" },
  { hanzi: "指", pinyin: "zhǐ", meaning: "가리키다" },
  { hanzi: "至少", pinyin: "zhìshǎo", meaning: "적어도" },
  { hanzi: "质量", pinyin: "zhìliàng", meaning: "품질" },
  { hanzi: "重", pinyin: "zhòng", meaning: "무겁다" },
  { hanzi: "重点", pinyin: "zhòngdiǎn", meaning: "중점" },
  { hanzi: "重视", pinyin: "zhòngshì", meaning: "중시하다" },
  { hanzi: "周围", pinyin: "zhōuwéi", meaning: "주위, 주변" },
  { hanzi: "主意", pinyin: "zhǔyi", meaning: "생각, 아이디어" },
  { hanzi: "祝贺", pinyin: "zhùhè", meaning: "축하하다" },
  { hanzi: "著名", pinyin: "zhùmíng", meaning: "저명하다" },
  { hanzi: "专门", pinyin: "zhuānmén", meaning: "전문적으로, 특히" },
  { hanzi: "专业", pinyin: "zhuānyè", meaning: "전공, 전문" },
  { hanzi: "转", pinyin: "zhuǎn", meaning: "돌다, 회전하다" },
  { hanzi: "赚", pinyin: "zhuàn", meaning: "벌다 (돈을)" },
  { hanzi: "准确", pinyin: "zhǔnquè", meaning: "정확하다" },
  { hanzi: "准时", pinyin: "zhǔnshí", meaning: "제시간에, 정각에" },
  { hanzi: "仔细", pinyin: "zǐxì", meaning: "자세하다, 꼼꼼하다" },
  { hanzi: "自然", pinyin: "zìrán", meaning: "자연" },
  { hanzi: "自信", pinyin: "zìxìn", meaning: "자신감 있다" },
  { hanzi: "总结", pinyin: "zǒngjié", meaning: "결론짓다, 총결산하다" },
  { hanzi: "租", pinyin: "zū", meaning: "빌리다, 임대하다" },
  { hanzi: "最好", pinyin: "zuìhǎo", meaning: "가장 좋다, ~하는 편이 좋다" },
  { hanzi: "尊重", pinyin: "zūnzhòng", meaning: "존중하다" },
  { hanzi: "左右", pinyin: "zuǒyòu", meaning: "좌우, 정도" },
  { hanzi: "作家", pinyin: "zuòjiā", meaning: "작가" },
  { hanzi: "作用", pinyin: "zuòyòng", meaning: "작용, 효과" },
  { hanzi: "作者", pinyin: "zuòzhě", meaning: "작자, 저자" },
  { hanzi: "座位", pinyin: "zuòwèi", meaning: "좌석" }
];
