// HSK 5급 단어 (1298개, HSK 2.0 기준)
// 단어·병음 출처: complete-hsk-vocabulary (https://github.com/drkameleon/complete-hsk-vocabulary, MIT License)
// 한국어 뜻은 이 프로젝트에서 작성했습니다.
const hsk5Words = [
  { hanzi: '唉', pinyin: 'āi', meaning: '아이고, 에이 (탄식)' },
  { hanzi: '爱护', pinyin: 'àihù', meaning: '아끼고 보호하다' },
  { hanzi: '爱惜', pinyin: 'àixī', meaning: '소중히 여기다' },
  { hanzi: '爱心', pinyin: 'àixīn', meaning: '사랑하는 마음' },
  { hanzi: '安慰', pinyin: 'ānwèi', meaning: '위로하다' },
  { hanzi: '安装', pinyin: 'ānzhuāng', meaning: '설치하다' },
  { hanzi: '岸', pinyin: 'àn', meaning: '기슭, 언덕' },
  { hanzi: '把握', pinyin: 'bǎwò', meaning: '잡다, 파악하다' },
  { hanzi: '摆', pinyin: 'bǎi', meaning: '배열하다, 놓다' },
  { hanzi: '班主任', pinyin: 'bānzhǔrèn', meaning: '담임 선생님' },
  { hanzi: '办理', pinyin: 'bànlǐ', meaning: '처리하다' },
  { hanzi: '傍晚', pinyin: 'bàngwǎn', meaning: '저녁 무렵' },
  { hanzi: '棒', pinyin: 'bàng', meaning: '훌륭하다' },
  { hanzi: '包裹', pinyin: 'bāoguǒ', meaning: '소포' },
  { hanzi: '包含', pinyin: 'bāohán', meaning: '포함하다' },
  { hanzi: '包子', pinyin: 'bāozi', meaning: '만두' },
  { hanzi: '薄', pinyin: 'báo', meaning: '얇다' },
  { hanzi: '宝贝', pinyin: 'bǎobèi', meaning: '보배, 귀염둥이' },
  { hanzi: '宝贵', pinyin: 'bǎoguì', meaning: '귀중하다' },
  { hanzi: '保持', pinyin: 'bǎochí', meaning: '유지하다' },
  { hanzi: '保存', pinyin: 'bǎocún', meaning: '보존하다' },
  { hanzi: '保留', pinyin: 'bǎoliú', meaning: '보류하다' },
  { hanzi: '保险', pinyin: 'bǎoxiǎn', meaning: '보험' },
  { hanzi: '报告', pinyin: 'bàogào', meaning: '보고하다' },
  { hanzi: '悲观', pinyin: 'bēiguān', meaning: '비관적이다' },
  { hanzi: '背', pinyin: 'bèi', meaning: '등, 업다' },
  { hanzi: '背景', pinyin: 'běijǐng', meaning: '배경' },
  { hanzi: '被子', pinyin: 'bèizi', meaning: '이불' },
  { hanzi: '本科', pinyin: 'běnkē', meaning: '학부 (대학)' },
  { hanzi: '本领', pinyin: 'běnlǐng', meaning: '능력, 솜씨' },
  { hanzi: '本质', pinyin: 'běnzhì', meaning: '본질' },
  { hanzi: '比例', pinyin: 'bǐlì', meaning: '비례, 비율' },
  { hanzi: '比如', pinyin: 'bǐrú', meaning: '예를 들어' },
  { hanzi: '彼此', pinyin: 'bǐcǐ', meaning: '피차, 서로' },
  { hanzi: '必然', pinyin: 'bìrán', meaning: '필연적이다' },
  { hanzi: '必需', pinyin: 'bìxū', meaning: '꼭 필요하다, 필수의' },
  { hanzi: '必要', pinyin: 'bìyào', meaning: '필요하다' },
  { hanzi: '毕竟', pinyin: 'bìjìng', meaning: '어쨌든, 결국' },
  { hanzi: '避免', pinyin: 'bìmiǎn', meaning: '피하다' },
  { hanzi: '编辑', pinyin: 'biānjí', meaning: '편집하다' },
  { hanzi: '鞭炮', pinyin: 'biānpào', meaning: '폭죽' },
  { hanzi: '便', pinyin: 'biàn', meaning: '곧, 편하다' },
  { hanzi: '辩论', pinyin: 'biànlùn', meaning: '변론하다' },
  { hanzi: '标点', pinyin: 'biāodiǎn', meaning: '구두점' },
  { hanzi: '标志', pinyin: 'biāozhì', meaning: '상징, 표지' },
  { hanzi: '表面', pinyin: 'biǎomiàn', meaning: '표면' },
  { hanzi: '表明', pinyin: 'biǎomíng', meaning: '분명하게 나타내다' },
  { hanzi: '表情', pinyin: 'biǎoqíng', meaning: '표정' },
  { hanzi: '表现', pinyin: 'biǎoxiàn', meaning: '표현하다, 태도' },
  { hanzi: '丙', pinyin: 'bǐng', meaning: '병 (셋째, 천간의 셋째)' },
  { hanzi: '病毒', pinyin: 'bìngdú', meaning: '바이러스' },
  { hanzi: '玻璃', pinyin: 'bōli', meaning: '유리' },
  { hanzi: '脖子', pinyin: 'bózi', meaning: '목' },
  { hanzi: '博物馆', pinyin: 'bówùguǎn', meaning: '박물관' },
  { hanzi: '补充', pinyin: 'bǔchōng', meaning: '보충하다' },
  { hanzi: '不安', pinyin: 'bùān', meaning: '불안하다' },
  { hanzi: '不必', pinyin: 'bùbì', meaning: '~할 필요 없다' },
  { hanzi: '不得了', pinyin: 'bùdéliǎo', meaning: '큰일 났다' },
  { hanzi: '不断', pinyin: 'búduàn', meaning: '끊임없이' },
  { hanzi: '不好意思', pinyin: 'bùhǎoyìsi', meaning: '부끄럽다, 미안하다' },
  { hanzi: '不见得', pinyin: 'bújiànde', meaning: '반드시 ~한 것은 아니다' },
  { hanzi: '不免', pinyin: 'bùmiǎn', meaning: '면할 수 없다, 아무래도' },
  { hanzi: '不耐烦', pinyin: 'búnàifán', meaning: '귀찮다, 성가시다' },
  { hanzi: '不然', pinyin: 'bùrán', meaning: '그렇지 않으면' },
  { hanzi: '不如', pinyin: 'bùrú', meaning: '~만 못하다' },
  { hanzi: '不要紧', pinyin: 'búyàojǐn', meaning: '괜찮다, 문제없다' },
  { hanzi: '不足', pinyin: 'bùzú', meaning: '부족하다' },
  { hanzi: '布', pinyin: 'bù', meaning: '천, 직물' },
  { hanzi: '步骤', pinyin: 'bùzhòu', meaning: '절차, 단계' },
  { hanzi: '部门', pinyin: 'bùmén', meaning: '부서, 부문' },
  { hanzi: '财产', pinyin: 'cáichǎn', meaning: '재산' },
  { hanzi: '采访', pinyin: 'cǎifǎng', meaning: '취재하다' },
  { hanzi: '采取', pinyin: 'cǎiqǔ', meaning: '채택하다' },
  { hanzi: '彩虹', pinyin: 'cǎihóng', meaning: '무지개' },
  { hanzi: '踩', pinyin: 'cǎi', meaning: '밟다' },
  { hanzi: '参考', pinyin: 'cānkǎo', meaning: '참고하다' },
  { hanzi: '参与', pinyin: 'cānyù', meaning: '참여하다' },
  { hanzi: '餐厅', pinyin: 'cāntīng', meaning: '식당, 레스토랑' },
  { hanzi: '残疾', pinyin: 'cánjí', meaning: '장애' },
  { hanzi: '惭愧', pinyin: 'cánkuì', meaning: '부끄럽다' },
  { hanzi: '操场', pinyin: 'cāochǎng', meaning: '운동장' },
  { hanzi: '操心', pinyin: 'cāoxīn', meaning: '애태우다, 신경 쓰다' },
  { hanzi: '册', pinyin: 'cè', meaning: '권, 책자' },
  { hanzi: '厕所', pinyin: 'cèsuǒ', meaning: '화장실' },
  { hanzi: '测验', pinyin: 'cèyàn', meaning: '테스트, 시험하다' },
  { hanzi: '曾经', pinyin: 'céngjīng', meaning: '일찍이, 이전에' },
  { hanzi: '叉子', pinyin: 'chāzi', meaning: '포크' },
  { hanzi: '插', pinyin: 'chā', meaning: '꽂다, 끼우다' },
  { hanzi: '差别', pinyin: 'chābié', meaning: '차이, 차별' },
  { hanzi: '拆', pinyin: 'chāi', meaning: '뜯다, 허물다' },
  { hanzi: '产品', pinyin: 'chǎnpǐn', meaning: '제품, 상품' },
  { hanzi: '产生', pinyin: 'chǎnshēng', meaning: '생기다, 발생하다' },
  { hanzi: '常识', pinyin: 'chángshí', meaning: '상식' },
  { hanzi: '抄', pinyin: 'chāo', meaning: '베끼다, 베껴 쓰다' },
  { hanzi: '朝', pinyin: 'cháo', meaning: '~을 향하여, 왕조' },
  { hanzi: '朝代', pinyin: 'cháodài', meaning: '왕조, 시대' },
  { hanzi: '吵架', pinyin: 'chǎojià', meaning: '말다툼하다' },
  { hanzi: '炒', pinyin: 'chǎo', meaning: '볶다' },
  { hanzi: '车库', pinyin: 'chēkù', meaning: '차고' },
  { hanzi: '车厢', pinyin: 'chēxiāng', meaning: '객차, 차량 칸' },
  { hanzi: '彻底', pinyin: 'chèdǐ', meaning: '철저하다' },
  { hanzi: '沉默', pinyin: 'chénmò', meaning: '침묵하다' },
  { hanzi: '趁', pinyin: 'chèn', meaning: '(기회를) 틈타다' },
  { hanzi: '称呼', pinyin: 'chēnghu', meaning: '부르다, 호칭' },
  { hanzi: '称赞', pinyin: 'chēngzàn', meaning: '칭찬하다' },
  { hanzi: '成分', pinyin: 'chéngfèn', meaning: '성분' },
  { hanzi: '成果', pinyin: 'chéngguǒ', meaning: '성과' },
  { hanzi: '成就', pinyin: 'chéngjiù', meaning: '성취, 업적' },
  { hanzi: '成立', pinyin: 'chénglì', meaning: '설립하다, 성립하다' },
  { hanzi: '成语', pinyin: 'chéngyǔ', meaning: '성어, 사자성어' },
  { hanzi: '成长', pinyin: 'chéngzhǎng', meaning: '성장하다' },
  { hanzi: '承担', pinyin: 'chéngdān', meaning: '맡다, 담당하다' },
  { hanzi: '承认', pinyin: 'chéngrèn', meaning: '인정하다, 승인하다' },
  { hanzi: '承受', pinyin: 'chéngshòu', meaning: '견디다, 감당하다' },
  { hanzi: '诚恳', pinyin: 'chéngkěn', meaning: '진실하다, 간절하다' },
  { hanzi: '乘', pinyin: 'chéng', meaning: '타다, 곱하다' },
  { hanzi: '程度', pinyin: 'chéngdù', meaning: '정도' },
  { hanzi: '程序', pinyin: 'chéngxù', meaning: '순서, 절차, 프로그램' },
  { hanzi: '吃亏', pinyin: 'chīkuī', meaning: '손해를 보다' },
  { hanzi: '池子', pinyin: 'chízi', meaning: '못, 연못' },
  { hanzi: '持续', pinyin: 'chíxù', meaning: '지속하다' },
  { hanzi: '尺子', pinyin: 'chǐzi', meaning: '자' },
  { hanzi: '翅膀', pinyin: 'chìbǎng', meaning: '날개' },
  { hanzi: '充电器', pinyin: 'chōngdiànqì', meaning: '충전기' },
  { hanzi: '充分', pinyin: 'chōngfèn', meaning: '충분하다' },
  { hanzi: '充满', pinyin: 'chōngmǎn', meaning: '가득 차다, 충만하다' },
  { hanzi: '冲', pinyin: 'chōng', meaning: '돌진하다, (물에) 타다' },
  { hanzi: '宠物', pinyin: 'chǒngwù', meaning: '애완동물' },
  { hanzi: '抽屉', pinyin: 'chōuti', meaning: '서랍' },
  { hanzi: '抽象', pinyin: 'chōuxiàng', meaning: '추상적이다' },
  { hanzi: '丑', pinyin: 'chǒu', meaning: '못생기다, 추하다' },
  { hanzi: '臭', pinyin: 'chòu', meaning: '냄새나다, 구리다' },
  { hanzi: '出版', pinyin: 'chūbǎn', meaning: '출판하다' },
  { hanzi: '出口', pinyin: 'chūkǒu', meaning: '출구, 수출하다' },
  { hanzi: '出色', pinyin: 'chūsè', meaning: '뛰어나다' },
  { hanzi: '出席', pinyin: 'chūxí', meaning: '출석하다, 참석하다' },
  { hanzi: '初级', pinyin: 'chūjí', meaning: '초급' },
  { hanzi: '除', pinyin: 'chú', meaning: '제거하다, ~을 제외하고' },
  { hanzi: '除非', pinyin: 'chúfēi', meaning: '오직 ~해야만' },
  { hanzi: '除夕', pinyin: 'Chúxī', meaning: '섣달 그믐날 밤' },
  { hanzi: '处理', pinyin: 'chǔlǐ', meaning: '처리하다' },
  { hanzi: '传播', pinyin: 'chuánbō', meaning: '전파하다, 퍼뜨리다' },
  { hanzi: '传递', pinyin: 'chuándì', meaning: '전달하다' },
  { hanzi: '传染', pinyin: 'chuánrǎn', meaning: '전염하다' },
  { hanzi: '传说', pinyin: 'chuánshuō', meaning: '전설' },
  { hanzi: '传统', pinyin: 'chuántǒng', meaning: '전통' },
  { hanzi: '窗帘', pinyin: 'chuānglián', meaning: '커튼' },
  { hanzi: '闯', pinyin: 'chuǎng', meaning: '돌진하다, 뛰어들다' },
  { hanzi: '创造', pinyin: 'chuàngzào', meaning: '창조하다' },
  { hanzi: '吹', pinyin: 'chuī', meaning: '불다' },
  { hanzi: '辞职', pinyin: 'cízhí', meaning: '사직하다' },
  { hanzi: '磁带', pinyin: 'cídài', meaning: '카세트테이프' },
  { hanzi: '此外', pinyin: 'cǐwài', meaning: '이 밖에' },
  { hanzi: '次要', pinyin: 'cìyào', meaning: '부차적인, 덜 중요한' },
  { hanzi: '刺激', pinyin: 'cìjī', meaning: '자극하다' },
  { hanzi: '匆忙', pinyin: 'cōngmáng', meaning: '바쁘다, 급하다' },
  { hanzi: '从此', pinyin: 'cóngcǐ', meaning: '이제부터, 그로부터' },
  { hanzi: '从而', pinyin: 'cóngér', meaning: '따라서, 그리하여' },
  { hanzi: '从前', pinyin: 'cóngqián', meaning: '이전, 옛날' },
  { hanzi: '从事', pinyin: 'cóngshì', meaning: '종사하다' },
  { hanzi: '促进', pinyin: 'cùjìn', meaning: '촉진하다' },
  { hanzi: '促使', pinyin: 'cùshǐ', meaning: '~하도록 재촉하다' },
  { hanzi: '醋', pinyin: 'cù', meaning: '식초, 질투' },
  { hanzi: '催', pinyin: 'cuī', meaning: '재촉하다' },
  { hanzi: '存', pinyin: 'cún', meaning: '보관하다, 저축하다' },
  { hanzi: '存在', pinyin: 'cúnzài', meaning: '존재하다' },
  { hanzi: '措施', pinyin: 'cuòshī', meaning: '조치' },
  { hanzi: '错误', pinyin: 'cuòwù', meaning: '오류, 잘못' },
  { hanzi: '达到', pinyin: 'dádào', meaning: '도달하다, 달성하다' },
  { hanzi: '答应', pinyin: 'dāying', meaning: '대답하다, 승낙하다' },
  { hanzi: '打工', pinyin: 'dǎgōng', meaning: '아르바이트하다' },
  { hanzi: '打交道', pinyin: 'dǎjiāodào', meaning: '왕래하다, 교제하다' },
  { hanzi: '打喷嚏', pinyin: 'dǎpēntì', meaning: '재채기하다' },
  { hanzi: '打听', pinyin: 'dǎting', meaning: '물어보다, 알아보다' },
  { hanzi: '打招呼', pinyin: 'dǎ zhāohu', meaning: '인사하다' },
  { hanzi: '大方', pinyin: 'dàfang', meaning: '대범하다, 시원스럽다' },
  { hanzi: '大象', pinyin: 'dàxiàng', meaning: '코끼리' },
  { hanzi: '大型', pinyin: 'dàxíng', meaning: '대형' },
  { hanzi: '呆', pinyin: 'dāi', meaning: '멍하다, 어리둥절하다' },
  { hanzi: '待遇', pinyin: 'dàiyù', meaning: '대우, 급여' },
  { hanzi: '贷款', pinyin: 'dàikuǎn', meaning: '대출, 대출하다' },
  { hanzi: '单纯', pinyin: 'dānchún', meaning: '단순하다' },
  { hanzi: '单调', pinyin: 'dāndiào', meaning: '단조롭다' },
  { hanzi: '单独', pinyin: 'dāndú', meaning: '단독으로, 혼자서' },
  { hanzi: '单位', pinyin: 'dānwèi', meaning: '단위, 직장' },
  { hanzi: '单元', pinyin: 'dānyuán', meaning: '단원, (아파트의) 동·라인' },
  { hanzi: '担任', pinyin: 'dānrèn', meaning: '맡다, 담당하다' },
  { hanzi: '耽误', pinyin: 'dānwu', meaning: '지체하다, 그르치다' },
  { hanzi: '胆小鬼', pinyin: 'dǎnxiǎoguǐ', meaning: '겁쟁이' },
  { hanzi: '淡', pinyin: 'dàn', meaning: '싱겁다, 연하다' },
  { hanzi: '当代', pinyin: 'dāngdài', meaning: '당대, 현대' },
  { hanzi: '挡', pinyin: 'dǎng', meaning: '막다, 가리다' },
  { hanzi: '导演', pinyin: 'dǎoyǎn', meaning: '감독, 연출하다' },
  { hanzi: '导致', pinyin: 'dǎozhì', meaning: '초래하다, 야기하다' },
  { hanzi: '岛', pinyin: 'dǎo', meaning: '섬' },
  { hanzi: '到达', pinyin: 'dàodá', meaning: '도착하다' },
  { hanzi: '倒', pinyin: 'dǎo', meaning: '넘어지다' },
  { hanzi: '倒霉', pinyin: 'dǎoméi', meaning: '재수 없다' },
  { hanzi: '道德', pinyin: 'dàodé', meaning: '도덕' },
  { hanzi: '道理', pinyin: 'dàoli', meaning: '도리, 이치' },
  { hanzi: '地道', pinyin: 'dìdao', meaning: '본고장의, 진짜의' },
  { hanzi: '地理', pinyin: 'dìlǐ', meaning: '지리' },
  { hanzi: '地区', pinyin: 'dìqū', meaning: '지역' },
  { hanzi: '地毯', pinyin: 'dìtǎn', meaning: '카펫, 양탄자' },
  { hanzi: '地位', pinyin: 'dìwèi', meaning: '지위' },
  { hanzi: '地震', pinyin: 'dìzhèn', meaning: '지진' },
  { hanzi: '的确', pinyin: 'díquè', meaning: '확실히, 정말' },
  { hanzi: '登机牌', pinyin: 'dēngjīpái', meaning: '탑승권' },
  { hanzi: '登记', pinyin: 'dēngjì', meaning: '등록하다' },
  { hanzi: '等待', pinyin: 'děngdài', meaning: '기다리다' },
  { hanzi: '等候', pinyin: 'děnghòu', meaning: '기다리다' },
  { hanzi: '等于', pinyin: 'děngyú', meaning: '~와 같다' },
  { hanzi: '滴', pinyin: 'dī', meaning: '방울, 떨어지다' },
  { hanzi: '敌人', pinyin: 'dírén', meaning: '적' },
  { hanzi: '递', pinyin: 'dì', meaning: '건네다, 전하다' },
  { hanzi: '点头', pinyin: 'diǎntóu', meaning: '고개를 끄덕이다' },
  { hanzi: '点心', pinyin: 'diǎnxin', meaning: '간식, 딤섬' },
  { hanzi: '电池', pinyin: 'diànchí', meaning: '건전지, 배터리' },
  { hanzi: '电台', pinyin: 'diàntái', meaning: '라디오 방송국' },
  { hanzi: '钓', pinyin: 'diào', meaning: '낚다, 낚시하다' },
  { hanzi: '调皮', pinyin: 'tiáopí', meaning: '장난스럽다' },
  { hanzi: '调整', pinyin: 'tiáozhěng', meaning: '조정하다' },
  { hanzi: '丁', pinyin: 'dīng', meaning: '정 (넷째), 정사각 조각' },
  { hanzi: '顶', pinyin: 'dǐng', meaning: '꼭대기, (모자 등을 세는 단위)' },
  { hanzi: '动画片', pinyin: 'dònghuàpiàn', meaning: '애니메이션' },
  { hanzi: '冻', pinyin: 'dòng', meaning: '얼다' },
  { hanzi: '洞', pinyin: 'dòng', meaning: '구멍, 동굴' },
  { hanzi: '豆腐', pinyin: 'dòufu', meaning: '두부' },
  { hanzi: '逗', pinyin: 'dòu', meaning: '놀리다, 웃기다' },
  { hanzi: '独立', pinyin: 'dúlì', meaning: '독립하다' },
  { hanzi: '独特', pinyin: 'dútè', meaning: '독특하다' },
  { hanzi: '度过', pinyin: 'dùguò', meaning: '보내다, 지내다' },
  { hanzi: '短信', pinyin: 'duǎnxìn', meaning: '문자 메시지' },
  { hanzi: '堆', pinyin: 'duī', meaning: '쌓다, 무더기' },
  { hanzi: '对比', pinyin: 'duìbǐ', meaning: '대비하다, 비교하다' },
  { hanzi: '对待', pinyin: 'duìdài', meaning: '대하다, 대우하다' },
  { hanzi: '对方', pinyin: 'duìfāng', meaning: '상대방' },
  { hanzi: '对手', pinyin: 'duìshǒu', meaning: '상대, 라이벌' },
  { hanzi: '对象', pinyin: 'duìxiàng', meaning: '대상, 결혼 상대' },
  { hanzi: '对于', pinyin: 'duìyú', meaning: '~에 대하여' },
  { hanzi: '吨', pinyin: 'dūn', meaning: '톤 (무게 단위)' },
  { hanzi: '蹲', pinyin: 'dūn', meaning: '쪼그리고 앉다' },
  { hanzi: '多亏', pinyin: 'duōkuī', meaning: '덕분에, 다행히' },
  { hanzi: '多余', pinyin: 'duōyú', meaning: '여분의, 쓸데없다' },
  { hanzi: '躲藏', pinyin: 'duǒcáng', meaning: '숨다' },
  { hanzi: '恶劣', pinyin: 'èliè', meaning: '열악하다, 나쁘다' },
  { hanzi: '发表', pinyin: 'fābiǎo', meaning: '발표하다' },
  { hanzi: '发愁', pinyin: 'fāchóu', meaning: '걱정하다' },
  { hanzi: '发达', pinyin: 'fādá', meaning: '발달하다' },
  { hanzi: '发抖', pinyin: 'fādǒu', meaning: '떨다' },
  { hanzi: '发挥', pinyin: 'fāhuī', meaning: '발휘하다' },
  { hanzi: '发明', pinyin: 'fāmíng', meaning: '발명하다' },
  { hanzi: '发票', pinyin: 'fāpiào', meaning: '영수증' },
  { hanzi: '发言', pinyin: 'fāyán', meaning: '발언하다' },
  { hanzi: '罚款', pinyin: 'fákuǎn', meaning: '벌금' },
  { hanzi: '法院', pinyin: 'fǎyuàn', meaning: '법원' },
  { hanzi: '翻', pinyin: 'fān', meaning: '뒤집다, 넘기다' },
  { hanzi: '凡是', pinyin: 'fánshì', meaning: '무릇, 모든' },
  { hanzi: '繁荣', pinyin: 'fánróng', meaning: '번영하다' },
  { hanzi: '反而', pinyin: 'fǎnér', meaning: '오히려' },
  { hanzi: '反复', pinyin: 'fǎnfù', meaning: '반복하다' },
  { hanzi: '反应', pinyin: 'fǎnyìng', meaning: '반응' },
  { hanzi: '反正', pinyin: 'fǎnzhèng', meaning: '어차피, 아무튼' },
  { hanzi: '方', pinyin: 'fāng', meaning: '네모, 방향' },
  { hanzi: '方案', pinyin: 'fāngàn', meaning: '방안' },
  { hanzi: '方式', pinyin: 'fāngshì', meaning: '방식' },
  { hanzi: '妨碍', pinyin: 'fángài', meaning: '방해하다' },
  { hanzi: '房东', pinyin: 'fángdōng', meaning: '집주인' },
  { hanzi: '仿佛', pinyin: 'fǎngfú', meaning: '마치 ~인 것 같다' },
  { hanzi: '放松', pinyin: 'fàngsōng', meaning: '긴장을 풀다' },
  { hanzi: '非', pinyin: 'fēi', meaning: '~이 아니다' },
  { hanzi: '肥皂', pinyin: 'féizào', meaning: '비누' },
  { hanzi: '废话', pinyin: 'fèihuà', meaning: '쓸데없는 말' },
  { hanzi: '肺', pinyin: 'fèi', meaning: '폐' },
  { hanzi: '费用', pinyin: 'fèiyòng', meaning: '비용' },
  { hanzi: '分别', pinyin: 'fēnbié', meaning: '헤어지다, 구별하다' },
  { hanzi: '分布', pinyin: 'fēnbù', meaning: '분포하다' },
  { hanzi: '分配', pinyin: 'fēnpèi', meaning: '분배하다, 배정하다' },
  { hanzi: '分析', pinyin: 'fēnxī', meaning: '분석하다' },
  { hanzi: '纷纷', pinyin: 'fēnfēn', meaning: '잇달아, 분분하다' },
  { hanzi: '奋斗', pinyin: 'fèndòu', meaning: '분투하다' },
  { hanzi: '愤怒', pinyin: 'fènnù', meaning: '분노하다' },
  { hanzi: '风格', pinyin: 'fēnggé', meaning: '스타일, 풍격' },
  { hanzi: '风俗', pinyin: 'fēngsú', meaning: '풍속' },
  { hanzi: '风险', pinyin: 'fēngxiǎn', meaning: '위험, 리스크' },
  { hanzi: '疯狂', pinyin: 'fēngkuáng', meaning: '미치다, 광적이다' },
  { hanzi: '讽刺', pinyin: 'fěngcì', meaning: '풍자하다' },
  { hanzi: '否定', pinyin: 'fǒudìng', meaning: '부정하다' },
  { hanzi: '否认', pinyin: 'fǒurèn', meaning: '부인하다' },
  { hanzi: '扶', pinyin: 'fú', meaning: '부축하다, 짚다' },
  { hanzi: '服从', pinyin: 'fúcóng', meaning: '복종하다' },
  { hanzi: '服装', pinyin: 'fúzhuāng', meaning: '복장, 의상' },
  { hanzi: '幅', pinyin: 'fú', meaning: '폭 (그림·천을 세는 단위)' },
  { hanzi: '辅导', pinyin: 'fǔdǎo', meaning: '지도하다, 과외하다' },
  { hanzi: '付款', pinyin: 'fùkuǎn', meaning: '지불하다' },
  { hanzi: '妇女', pinyin: 'fùnǚ', meaning: '부녀자, 여성' },
  { hanzi: '复制', pinyin: 'fùzhì', meaning: '복제하다' },
  { hanzi: '改革', pinyin: 'gǎigé', meaning: '개혁하다' },
  { hanzi: '改进', pinyin: 'gǎijìn', meaning: '개선하다' },
  { hanzi: '改善', pinyin: 'gǎishàn', meaning: '개선하다' },
  { hanzi: '改正', pinyin: 'gǎizhèng', meaning: '바르게 고치다' },
  { hanzi: '盖', pinyin: 'gài', meaning: '덮다, 뚜껑, 짓다' },
  { hanzi: '概括', pinyin: 'gàikuò', meaning: '요약하다, 개괄하다' },
  { hanzi: '概念', pinyin: 'gàiniàn', meaning: '개념' },
  { hanzi: '赶紧', pinyin: 'gǎnjǐn', meaning: '서둘러, 재빨리' },
  { hanzi: '赶快', pinyin: 'gǎnkuài', meaning: '빨리, 얼른' },
  { hanzi: '感激', pinyin: 'gǎnjī', meaning: '감격하다, 고마워하다' },
  { hanzi: '感受', pinyin: 'gǎnshòu', meaning: '느끼다, 느낌' },
  { hanzi: '感想', pinyin: 'gǎnxiǎng', meaning: '감상, 소감' },
  { hanzi: '干脆', pinyin: 'gāncuì', meaning: '시원스럽다, 아예' },
  { hanzi: '干活儿', pinyin: 'gànhuór', meaning: '일하다' },
  { hanzi: '钢铁', pinyin: 'gāngtiě', meaning: '강철' },
  { hanzi: '高档', pinyin: 'gāodàng', meaning: '고급' },
  { hanzi: '高速', pinyin: 'gāosù', meaning: '고속' },
  { hanzi: '搞', pinyin: 'gǎo', meaning: '하다, 처리하다' },
  { hanzi: '告别', pinyin: 'gàobié', meaning: '작별하다' },
  { hanzi: '胳膊', pinyin: 'gēbo', meaning: '팔' },
  { hanzi: '鸽子', pinyin: 'gēzi', meaning: '비둘기' },
  { hanzi: '革命', pinyin: 'gémìng', meaning: '혁명' },
  { hanzi: '格外', pinyin: 'géwài', meaning: '유달리, 특히' },
  { hanzi: '隔壁', pinyin: 'gébì', meaning: '이웃, 옆집' },
  { hanzi: '个别', pinyin: 'gèbié', meaning: '개별적, 일부' },
  { hanzi: '个人', pinyin: 'gèrén', meaning: '개인' },
  { hanzi: '个性', pinyin: 'gèxìng', meaning: '개성' },
  { hanzi: '各自', pinyin: 'gèzì', meaning: '각자' },
  { hanzi: '根', pinyin: 'gēn', meaning: '뿌리, 가늘고 긴 것을 세는 단위' },
  { hanzi: '根本', pinyin: 'gēnběn', meaning: '근본, 전혀' },
  { hanzi: '更加', pinyin: 'gèngjiā', meaning: '더욱' },
  { hanzi: '工厂', pinyin: 'gōngchǎng', meaning: '공장' },
  { hanzi: '工程师', pinyin: 'gōngchéngshī', meaning: '엔지니어' },
  { hanzi: '工人', pinyin: 'gōngrén', meaning: '노동자' },
  { hanzi: '工业', pinyin: 'gōngyè', meaning: '공업' },
  { hanzi: '公布', pinyin: 'gōngbù', meaning: '공포하다, 공표하다' },
  { hanzi: '公开', pinyin: 'gōngkāi', meaning: '공개하다' },
  { hanzi: '公平', pinyin: 'gōngpíng', meaning: '공평하다' },
  { hanzi: '公寓', pinyin: 'gōngyù', meaning: '아파트' },
  { hanzi: '公元', pinyin: 'gōngyuán', meaning: '서기' },
  { hanzi: '公主', pinyin: 'gōngzhǔ', meaning: '공주' },
  { hanzi: '功夫', pinyin: 'gōngfu', meaning: '쿵푸, 시간/노력' },
  { hanzi: '功能', pinyin: 'gōngnéng', meaning: '기능' },
  { hanzi: '贡献', pinyin: 'gòngxiàn', meaning: '공헌하다' },
  { hanzi: '沟通', pinyin: 'gōutōng', meaning: '소통하다' },
  { hanzi: '构成', pinyin: 'gòuchéng', meaning: '구성하다' },
  { hanzi: '姑姑', pinyin: 'gūgu', meaning: '고모' },
  { hanzi: '姑娘', pinyin: 'gūniang', meaning: '아가씨' },
  { hanzi: '古代', pinyin: 'gǔdài', meaning: '고대' },
  { hanzi: '古典', pinyin: 'gǔdiǎn', meaning: '고전' },
  { hanzi: '古老', pinyin: 'gǔlǎo', meaning: '오래되다' },
  { hanzi: '股票', pinyin: 'gǔpiào', meaning: '주식' },
  { hanzi: '骨头', pinyin: 'gǔtou', meaning: '뼈' },
  { hanzi: '鼓舞', pinyin: 'gǔwǔ', meaning: '고무하다, 북돋우다' },
  { hanzi: '固定', pinyin: 'gùdìng', meaning: '고정하다' },
  { hanzi: '固体', pinyin: 'gùtǐ', meaning: '고체' },
  { hanzi: '雇佣', pinyin: 'gùyōng', meaning: '고용하다' },
  { hanzi: '挂号', pinyin: 'guàhào', meaning: '접수하다, 등기로 부치다' },
  { hanzi: '乖', pinyin: 'guāi', meaning: '얌전하다, 말을 잘 듣다' },
  { hanzi: '拐弯', pinyin: 'guǎiwān', meaning: '모퉁이를 돌다' },
  { hanzi: '怪不得', pinyin: 'guàibude', meaning: '어쩐지' },
  { hanzi: '关闭', pinyin: 'guānbì', meaning: '닫다, 폐쇄하다' },
  { hanzi: '关怀', pinyin: 'guānhuái', meaning: '관심을 갖다, 보살피다' },
  { hanzi: '观察', pinyin: 'guānchá', meaning: '관찰하다' },
  { hanzi: '观点', pinyin: 'guāndiǎn', meaning: '관점' },
  { hanzi: '观念', pinyin: 'guānniàn', meaning: '관념' },
  { hanzi: '官', pinyin: 'guān', meaning: '관리, 벼슬' },
  { hanzi: '冠军', pinyin: 'guànjūn', meaning: '우승, 챔피언' },
  { hanzi: '管子', pinyin: 'guǎnzi', meaning: '관, 파이프' },
  { hanzi: '罐头', pinyin: 'guàntou', meaning: '통조림' },
  { hanzi: '光滑', pinyin: 'guānghuá', meaning: '매끄럽다' },
  { hanzi: '光临', pinyin: 'guānglín', meaning: '왕림하다, 방문하다' },
  { hanzi: '光明', pinyin: 'guāngmíng', meaning: '광명, 밝다' },
  { hanzi: '光盘', pinyin: 'guāngpán', meaning: 'CD, 디스크' },
  { hanzi: '光荣', pinyin: 'guāngróng', meaning: '영광스럽다' },
  { hanzi: '广场', pinyin: 'guǎngchǎng', meaning: '광장' },
  { hanzi: '广大', pinyin: 'guǎngdà', meaning: '광대하다, 넓다' },
  { hanzi: '广泛', pinyin: 'guǎngfàn', meaning: '광범위하다' },
  { hanzi: '规矩', pinyin: 'guīju', meaning: '규칙, 예의 바르다' },
  { hanzi: '规律', pinyin: 'guīlǜ', meaning: '규칙, 법칙' },
  { hanzi: '规模', pinyin: 'guīmó', meaning: '규모' },
  { hanzi: '规则', pinyin: 'guīzé', meaning: '규칙' },
  { hanzi: '柜台', pinyin: 'guìtái', meaning: '카운터, 계산대' },
  { hanzi: '滚', pinyin: 'gǔn', meaning: '구르다, 꺼져' },
  { hanzi: '锅', pinyin: 'guō', meaning: '솥, 냄비' },
  { hanzi: '国籍', pinyin: 'guójí', meaning: '국적' },
  { hanzi: '国庆节', pinyin: 'Guóqìngjié', meaning: '국경절' },
  { hanzi: '果实', pinyin: 'guǒshí', meaning: '열매, 성과' },
  { hanzi: '过分', pinyin: 'guòfèn', meaning: '지나치다' },
  { hanzi: '过敏', pinyin: 'guòmǐn', meaning: '알레르기, 과민하다' },
  { hanzi: '过期', pinyin: 'guòqī', meaning: '기한이 지나다' },
  { hanzi: '哈', pinyin: 'hā', meaning: '하하 (웃음소리)' },
  { hanzi: '海关', pinyin: 'hǎiguān', meaning: '세관' },
  { hanzi: '海鲜', pinyin: 'hǎixiān', meaning: '해산물' },
  { hanzi: '喊', pinyin: 'hǎn', meaning: '외치다, 소리치다' },
  { hanzi: '豪华', pinyin: 'háohuá', meaning: '호화롭다' },
  { hanzi: '好奇', pinyin: 'hàoqí', meaning: '호기심이 많다' },
  { hanzi: '合法', pinyin: 'héfǎ', meaning: '합법적이다' },
  { hanzi: '合理', pinyin: 'hélǐ', meaning: '합리적이다' },
  { hanzi: '合同', pinyin: 'hétong', meaning: '계약서' },
  { hanzi: '合影', pinyin: 'héyǐng', meaning: '단체 사진, 함께 사진 찍다' },
  { hanzi: '合作', pinyin: 'hézuò', meaning: '합작하다, 협력하다' },
  { hanzi: '何必', pinyin: 'hébì', meaning: '구태여 ~할 필요가 있는가' },
  { hanzi: '何况', pinyin: 'hékuàng', meaning: '하물며' },
  { hanzi: '和平', pinyin: 'hépíng', meaning: '평화' },
  { hanzi: '核心', pinyin: 'héxīn', meaning: '핵심' },
  { hanzi: '恨', pinyin: 'hèn', meaning: '미워하다, 원망하다' },
  { hanzi: '横', pinyin: 'héng', meaning: '가로, 가로의' },
  { hanzi: '后果', pinyin: 'hòuguǒ', meaning: '(나쁜) 결과' },
  { hanzi: '呼吸', pinyin: 'hūxī', meaning: '호흡하다' },
  { hanzi: '忽视', pinyin: 'hūshì', meaning: '소홀히 하다, 무시하다' },
  { hanzi: '胡说', pinyin: 'húshuō', meaning: '헛소리하다' },
  { hanzi: '胡同', pinyin: 'hútòng', meaning: '골목' },
  { hanzi: '胡须', pinyin: 'húxū', meaning: '수염' },
  { hanzi: '壶', pinyin: 'hú', meaning: '주전자, 병' },
  { hanzi: '蝴蝶', pinyin: 'húdié', meaning: '나비' },
  { hanzi: '糊涂', pinyin: 'hútu', meaning: '어리석다, 흐리멍덩하다' },
  { hanzi: '花生', pinyin: 'huāshēng', meaning: '땅콩' },
  { hanzi: '华裔', pinyin: 'huáyì', meaning: '화교, 중국계' },
  { hanzi: '滑冰', pinyin: 'huábīng', meaning: '스케이트를 타다' },
  { hanzi: '化学', pinyin: 'huàxué', meaning: '화학' },
  { hanzi: '划船', pinyin: 'huáchuán', meaning: '배를 젓다' },
  { hanzi: '话题', pinyin: 'huàtí', meaning: '화제' },
  { hanzi: '怀念', pinyin: 'huáiniàn', meaning: '그리워하다' },
  { hanzi: '缓解', pinyin: 'huǎnjiě', meaning: '완화하다' },
  { hanzi: '幻想', pinyin: 'huànxiǎng', meaning: '환상' },
  { hanzi: '慌张', pinyin: 'huāngzhāng', meaning: '당황하다' },
  { hanzi: '皇帝', pinyin: 'huángdì', meaning: '황제' },
  { hanzi: '皇后', pinyin: 'huánghòu', meaning: '황후' },
  { hanzi: '黄瓜', pinyin: 'huángguā', meaning: '오이' },
  { hanzi: '黄金', pinyin: 'huángjīn', meaning: '황금' },
  { hanzi: '灰', pinyin: 'huī', meaning: '재, 회색' },
  { hanzi: '灰尘', pinyin: 'huīchén', meaning: '먼지' },
  { hanzi: '灰心', pinyin: 'huīxīn', meaning: '낙심하다' },
  { hanzi: '恢复', pinyin: 'huīfù', meaning: '회복하다' },
  { hanzi: '挥', pinyin: 'huī', meaning: '휘두르다, 흔들다' },
  { hanzi: '汇率', pinyin: 'huìlǜ', meaning: '환율' },
  { hanzi: '会计', pinyin: 'kuàijì', meaning: '회계, 회계사' },
  { hanzi: '婚礼', pinyin: 'hūnlǐ', meaning: '결혼식' },
  { hanzi: '婚姻', pinyin: 'hūnyīn', meaning: '혼인, 결혼' },
  { hanzi: '活跃', pinyin: 'huóyuè', meaning: '활발하다' },
  { hanzi: '火柴', pinyin: 'huǒchái', meaning: '성냥' },
  { hanzi: '伙伴', pinyin: 'huǒbàn', meaning: '동료, 파트너' },
  { hanzi: '机器', pinyin: 'jīqì', meaning: '기계' },
  { hanzi: '肌肉', pinyin: 'jīròu', meaning: '근육' },
  { hanzi: '基本', pinyin: 'jīběn', meaning: '기본, 기본적인' },
  { hanzi: '激烈', pinyin: 'jīliè', meaning: '격렬하다' },
  { hanzi: '及格', pinyin: 'jígé', meaning: '합격하다' },
  { hanzi: '急忙', pinyin: 'jímáng', meaning: '급히, 서둘러' },
  { hanzi: '集体', pinyin: 'jítǐ', meaning: '집단, 단체' },
  { hanzi: '集中', pinyin: 'jízhōng', meaning: '집중하다' },
  { hanzi: '计算', pinyin: 'jìsuàn', meaning: '계산하다' },
  { hanzi: '记录', pinyin: 'jìlù', meaning: '기록하다, 기록' },
  { hanzi: '记忆', pinyin: 'jìyì', meaning: '기억' },
  { hanzi: '纪录', pinyin: 'jìlù', meaning: '기록' },
  { hanzi: '纪律', pinyin: 'jìlǜ', meaning: '규율' },
  { hanzi: '纪念', pinyin: 'jìniàn', meaning: '기념하다' },
  { hanzi: '寂寞', pinyin: 'jìmò', meaning: '외롭다, 쓸쓸하다' },
  { hanzi: '夹子', pinyin: 'jiāzi', meaning: '집게, 클립' },
  { hanzi: '家庭', pinyin: 'jiātíng', meaning: '가정' },
  { hanzi: '家务', pinyin: 'jiāwù', meaning: '집안일' },
  { hanzi: '家乡', pinyin: 'jiāxiāng', meaning: '고향' },
  { hanzi: '嘉宾', pinyin: 'jiābīn', meaning: '귀빈, 게스트' },
  { hanzi: '甲', pinyin: 'jiǎ', meaning: '갑 (첫째), 손발톱' },
  { hanzi: '假如', pinyin: 'jiǎrú', meaning: '만약' },
  { hanzi: '假装', pinyin: 'jiǎzhuāng', meaning: '~인 척하다' },
  { hanzi: '价值', pinyin: 'jiàzhí', meaning: '가치' },
  { hanzi: '驾驶', pinyin: 'jiàshǐ', meaning: '운전하다, 조종하다' },
  { hanzi: '嫁', pinyin: 'jià', meaning: '시집가다' },
  { hanzi: '尖锐', pinyin: 'jiānruì', meaning: '날카롭다, 첨예하다' },
  { hanzi: '坚决', pinyin: 'jiānjué', meaning: '단호하다' },
  { hanzi: '坚强', pinyin: 'jiānqiáng', meaning: '굳세다, 강인하다' },
  { hanzi: '肩膀', pinyin: 'jiānbǎng', meaning: '어깨' },
  { hanzi: '艰巨', pinyin: 'jiānjù', meaning: '어렵고 힘들다' },
  { hanzi: '艰苦', pinyin: 'jiānkǔ', meaning: '고생스럽다' },
  { hanzi: '煎', pinyin: 'jiān', meaning: '부치다, 지지다' },
  { hanzi: '捡', pinyin: 'jiǎn', meaning: '줍다' },
  { hanzi: '剪刀', pinyin: 'jiǎndāo', meaning: '가위' },
  { hanzi: '简历', pinyin: 'jiǎnlì', meaning: '이력서' },
  { hanzi: '简直', pinyin: 'jiǎnzhí', meaning: '그야말로, 정말' },
  { hanzi: '建立', pinyin: 'jiànlì', meaning: '세우다, 건립하다' },
  { hanzi: '建设', pinyin: 'jiànshè', meaning: '건설하다' },
  { hanzi: '建议', pinyin: 'jiànyì', meaning: '건의하다' },
  { hanzi: '建筑', pinyin: 'jiànzhù', meaning: '건축하다, 건축물' },
  { hanzi: '健身房', pinyin: 'jiànshēnfáng', meaning: '헬스장' },
  { hanzi: '键盘', pinyin: 'jiànpán', meaning: '키보드' },
  { hanzi: '讲究', pinyin: 'jiǎngjiu', meaning: '중시하다, 신경 쓰다' },
  { hanzi: '讲座', pinyin: 'jiǎngzuò', meaning: '강좌' },
  { hanzi: '降落', pinyin: 'jiàngluò', meaning: '착륙하다, 내려오다' },
  { hanzi: '酱油', pinyin: 'jiàngyóu', meaning: '간장' },
  { hanzi: '交换', pinyin: 'jiāohuàn', meaning: '교환하다' },
  { hanzi: '交际', pinyin: 'jiāojì', meaning: '교제하다' },
  { hanzi: '郊区', pinyin: 'jiāoqū', meaning: '교외' },
  { hanzi: '浇', pinyin: 'jiāo', meaning: '(물을) 붓다, 뿌리다' },
  { hanzi: '胶水', pinyin: 'jiāoshuǐ', meaning: '풀, 접착제' },
  { hanzi: '角度', pinyin: 'jiǎodù', meaning: '각도, 관점' },
  { hanzi: '角色', pinyin: 'juésè', meaning: '배역, 역할' },
  { hanzi: '狡猾', pinyin: 'jiǎohuá', meaning: '교활하다' },
  { hanzi: '教材', pinyin: 'jiàocái', meaning: '교재' },
  { hanzi: '教练', pinyin: 'jiàoliàn', meaning: '코치, 감독' },
  { hanzi: '教训', pinyin: 'jiàoxun', meaning: '교훈, 훈계하다' },
  { hanzi: '阶段', pinyin: 'jiēduàn', meaning: '단계' },
  { hanzi: '接触', pinyin: 'jiēchù', meaning: '접촉하다' },
  { hanzi: '接待', pinyin: 'jiēdài', meaning: '접대하다, 맞이하다' },
  { hanzi: '接近', pinyin: 'jiējìn', meaning: '접근하다, 가깝다' },
  { hanzi: '接着', pinyin: 'jiēzhe', meaning: '이어서, 계속해서' },
  { hanzi: '节', pinyin: 'jié', meaning: '마디, 명절, (수업) 교시' },
  { hanzi: '节省', pinyin: 'jiéshěng', meaning: '절약하다' },
  { hanzi: '结构', pinyin: 'jiégòu', meaning: '구조' },
  { hanzi: '结合', pinyin: 'jiéhé', meaning: '결합하다' },
  { hanzi: '结论', pinyin: 'jiélùn', meaning: '결론' },
  { hanzi: '结实', pinyin: 'jiēshi', meaning: '튼튼하다' },
  { hanzi: '结账', pinyin: 'jiézhàng', meaning: '계산하다, 결제하다' },
  { hanzi: '解放', pinyin: 'jiěfàng', meaning: '해방하다' },
  { hanzi: '解说员', pinyin: 'jiěshuōyuán', meaning: '해설자' },
  { hanzi: '戒烟', pinyin: 'jièyān', meaning: '담배를 끊다' },
  { hanzi: '戒指', pinyin: 'jièzhi', meaning: '반지' },
  { hanzi: '届', pinyin: 'jiè', meaning: '회, 기 (정기 행사를 세는 단위)' },
  { hanzi: '借口', pinyin: 'jièkǒu', meaning: '핑계, 구실' },
  { hanzi: '金属', pinyin: 'jīnshǔ', meaning: '금속' },
  { hanzi: '尽力', pinyin: 'jìnlì', meaning: '힘을 다하다' },
  { hanzi: '尽量', pinyin: 'jǐnliàng', meaning: '가능한 한, 최대한' },
  { hanzi: '紧', pinyin: 'jǐn', meaning: '팽팽하다, 꽉 끼다' },
  { hanzi: '紧急', pinyin: 'jǐnjí', meaning: '긴급하다' },
  { hanzi: '谨慎', pinyin: 'jǐnshèn', meaning: '신중하다' },
  { hanzi: '近代', pinyin: 'jìndài', meaning: '근대' },
  { hanzi: '进步', pinyin: 'jìnbù', meaning: '진보하다, 발전하다' },
  { hanzi: '进口', pinyin: 'jìnkǒu', meaning: '수입하다, 입구' },
  { hanzi: '经典', pinyin: 'jīngdiǎn', meaning: '고전, 경전' },
  { hanzi: '经营', pinyin: 'jīngyíng', meaning: '경영하다' },
  { hanzi: '精力', pinyin: 'jīnglì', meaning: '정력, 에너지' },
  { hanzi: '景色', pinyin: 'jǐngsè', meaning: '경치' },
  { hanzi: '敬爱', pinyin: 'jìngài', meaning: '경애하다' },
  { hanzi: '酒吧', pinyin: 'jiǔbā', meaning: '술집, 바' },
  { hanzi: '救', pinyin: 'jiù', meaning: '구하다' },
  { hanzi: '救护车', pinyin: 'jiùhùchē', meaning: '구급차' },
  { hanzi: '舅舅', pinyin: 'jiùjiu', meaning: '외삼촌' },
  { hanzi: '居然', pinyin: 'jūrán', meaning: '뜻밖에, 놀랍게도' },
  { hanzi: '桔子', pinyin: 'júzi', meaning: '귤' },
  { hanzi: '举', pinyin: 'jǔ', meaning: '들다 (손을)' },
  { hanzi: '巨大', pinyin: 'jùdà', meaning: '거대하다' },
  { hanzi: '具备', pinyin: 'jùbèi', meaning: '갖추다' },
  { hanzi: '具体', pinyin: 'jùtǐ', meaning: '구체적이다' },
  { hanzi: '俱乐部', pinyin: 'jùlèbù', meaning: '클럽, 동호회' },
  { hanzi: '据说', pinyin: 'jùshuō', meaning: '듣자 하니' },
  { hanzi: '聚会', pinyin: 'jùhuì', meaning: '모임, 회식' },
  { hanzi: '捐', pinyin: 'juān', meaning: '기부하다' },
  { hanzi: '卷', pinyin: 'juǎn', meaning: '말다, 두루마리' },
  { hanzi: '决赛', pinyin: 'juésài', meaning: '결승전' },
  { hanzi: '决心', pinyin: 'juéxīn', meaning: '결심' },
  { hanzi: '绝对', pinyin: 'juéduì', meaning: '절대적으로' },
  { hanzi: '军事', pinyin: 'jūnshì', meaning: '군사' },
  { hanzi: '均匀', pinyin: 'jūnyún', meaning: '균일하다, 고르다' },
  { hanzi: '卡车', pinyin: 'kǎchē', meaning: '트럭' },
  { hanzi: '开发', pinyin: 'kāifā', meaning: '개발하다' },
  { hanzi: '开放', pinyin: 'kāifàng', meaning: '개방하다, (꽃이) 피다' },
  { hanzi: '开幕式', pinyin: 'kāimùshì', meaning: '개막식' },
  { hanzi: '开心', pinyin: 'kāixīn', meaning: '즐겁다' },
  { hanzi: '砍', pinyin: 'kǎn', meaning: '(도끼로) 찍다, 베다' },
  { hanzi: '看不起', pinyin: 'kànbuqǐ', meaning: '얕보다, 무시하다' },
  { hanzi: '看来', pinyin: 'kànlai', meaning: '보아하니' },
  { hanzi: '抗议', pinyin: 'kàngyì', meaning: '항의하다' },
  { hanzi: '烤鸭', pinyin: 'kǎoyā', meaning: '카오야 (오리구이)' },
  { hanzi: '颗', pinyin: 'kē', meaning: '알 (작고 둥근 것을 세는 단위)' },
  { hanzi: '可见', pinyin: 'kějiàn', meaning: '~을 알 수 있다' },
  { hanzi: '可靠', pinyin: 'kěkào', meaning: '믿을 만하다' },
  { hanzi: '可怕', pinyin: 'kěpà', meaning: '무섭다, 두렵다' },
  { hanzi: '克', pinyin: 'kè', meaning: '그램(g), 이기다' },
  { hanzi: '克服', pinyin: 'kèfú', meaning: '극복하다' },
  { hanzi: '刻苦', pinyin: 'kèkǔ', meaning: '고생을 참다, 열심히 하다' },
  { hanzi: '客观', pinyin: 'kèguān', meaning: '객관적이다' },
  { hanzi: '客厅', pinyin: 'kètīng', meaning: '거실' },
  { hanzi: '课程', pinyin: 'kèchéng', meaning: '교육 과정, 커리큘럼' },
  { hanzi: '空间', pinyin: 'kōngjiān', meaning: '공간' },
  { hanzi: '空闲', pinyin: 'kòngxián', meaning: '여가, 한가하다' },
  { hanzi: '恐怖', pinyin: 'kǒngbù', meaning: '무섭다, 공포' },
  { hanzi: '控制', pinyin: 'kòngzhì', meaning: '통제하다, 제어하다' },
  { hanzi: '口味', pinyin: 'kǒuwèi', meaning: '입맛, 맛' },
  { hanzi: '夸', pinyin: 'kuā', meaning: '칭찬하다, 과장하다' },
  { hanzi: '矿泉水', pinyin: 'kuàngquánshuǐ', meaning: '생수' },
  { hanzi: '蜡烛', pinyin: 'làzhú', meaning: '양초' },
  { hanzi: '辣椒', pinyin: 'làjiāo', meaning: '고추' },
  { hanzi: '来自', pinyin: 'láizì', meaning: '~에서 오다' },
  { hanzi: '拦', pinyin: 'lán', meaning: '가로막다' },
  { hanzi: '烂', pinyin: 'làn', meaning: '썩다, 흐물흐물하다' },
  { hanzi: '狼', pinyin: 'láng', meaning: '늑대' },
  { hanzi: '劳动', pinyin: 'láodòng', meaning: '노동' },
  { hanzi: '劳驾', pinyin: 'láojià', meaning: '실례합니다' },
  { hanzi: '老百姓', pinyin: 'lǎobǎixìng', meaning: '백성, 일반 국민' },
  { hanzi: '老板', pinyin: 'lǎobǎn', meaning: '사장, 주인' },
  { hanzi: '老实', pinyin: 'lǎoshi', meaning: '성실하다, 정직하다' },
  { hanzi: '老鼠', pinyin: 'lǎoshǔ', meaning: '쥐' },
  { hanzi: '姥姥', pinyin: 'lǎolao', meaning: '외할머니' },
  { hanzi: '乐观', pinyin: 'lèguān', meaning: '낙관적이다' },
  { hanzi: '了不起', pinyin: 'liǎobuqǐ', meaning: '대단하다' },
  { hanzi: '雷', pinyin: 'léi', meaning: '천둥, 우레' },
  { hanzi: '类', pinyin: 'lèi', meaning: '종류, 무리' },
  { hanzi: '厘米', pinyin: 'límǐ', meaning: '센티미터' },
  { hanzi: '离婚', pinyin: 'líhūn', meaning: '이혼하다' },
  { hanzi: '梨', pinyin: 'lí', meaning: '배 (과일)' },
  { hanzi: '礼拜天', pinyin: 'lǐbàitiān', meaning: '일요일' },
  { hanzi: '理论', pinyin: 'lǐlùn', meaning: '이론' },
  { hanzi: '理由', pinyin: 'lǐyóu', meaning: '이유' },
  { hanzi: '力量', pinyin: 'lìliang', meaning: '힘, 역량' },
  { hanzi: '立方', pinyin: 'lìfāng', meaning: '입방, 세제곱' },
  { hanzi: '立即', pinyin: 'lìjí', meaning: '즉시' },
  { hanzi: '立刻', pinyin: 'lìkè', meaning: '즉시, 곧' },
  { hanzi: '利润', pinyin: 'lìrùn', meaning: '이윤' },
  { hanzi: '利息', pinyin: 'lìxī', meaning: '이자' },
  { hanzi: '利益', pinyin: 'lìyì', meaning: '이익' },
  { hanzi: '利用', pinyin: 'lìyòng', meaning: '이용하다' },
  { hanzi: '粒', pinyin: 'lì', meaning: '알, 톨 (낟알을 세는 단위)' },
  { hanzi: '连忙', pinyin: 'liánmáng', meaning: '얼른, 서둘러' },
  { hanzi: '连续剧', pinyin: 'liánxùjù', meaning: '연속극, 드라마' },
  { hanzi: '联合', pinyin: 'liánhé', meaning: '연합하다' },
  { hanzi: '恋爱', pinyin: 'liànài', meaning: '연애하다' },
  { hanzi: '良好', pinyin: 'liánghǎo', meaning: '양호하다' },
  { hanzi: '粮食', pinyin: 'liángshi', meaning: '양식, 곡물' },
  { hanzi: '临时', pinyin: 'línshí', meaning: '임시의, 때에 이르러' },
  { hanzi: '灵活', pinyin: 'línghuó', meaning: '민첩하다, 융통성 있다' },
  { hanzi: '铃', pinyin: 'líng', meaning: '방울, 벨' },
  { hanzi: '零件', pinyin: 'língjiàn', meaning: '부품' },
  { hanzi: '零钱', pinyin: 'língqián', meaning: '잔돈' },
  { hanzi: '零食', pinyin: 'língshí', meaning: '간식, 군것질' },
  { hanzi: '领导', pinyin: 'lǐngdǎo', meaning: '지도자, 지도하다' },
  { hanzi: '领域', pinyin: 'lǐngyù', meaning: '영역, 분야' },
  { hanzi: '浏览', pinyin: 'liúlǎn', meaning: '훑어보다, 브라우징하다' },
  { hanzi: '流传', pinyin: 'liúchuán', meaning: '전해지다' },
  { hanzi: '龙', pinyin: 'lóng', meaning: '용' },
  { hanzi: '漏', pinyin: 'lòu', meaning: '새다' },
  { hanzi: '陆地', pinyin: 'lùdì', meaning: '육지' },
  { hanzi: '陆续', pinyin: 'lùxù', meaning: '잇달아' },
  { hanzi: '录取', pinyin: 'lùqǔ', meaning: '채용하다, 합격시키다' },
  { hanzi: '录音', pinyin: 'lùyīn', meaning: '녹음하다' },
  { hanzi: '露', pinyin: 'lù', meaning: '드러내다, 이슬' },
  { hanzi: '轮流', pinyin: 'lúnliú', meaning: '교대로 하다' },
  { hanzi: '论文', pinyin: 'lùnwén', meaning: '논문' },
  { hanzi: '逻辑', pinyin: 'luóji', meaning: '논리' },
  { hanzi: '落后', pinyin: 'luòhòu', meaning: '뒤떨어지다, 낙후하다' },
  { hanzi: '骂', pinyin: 'mà', meaning: '욕하다, 꾸짖다' },
  { hanzi: '麦克风', pinyin: 'màikèfēng', meaning: '마이크' },
  { hanzi: '馒头', pinyin: 'mántou', meaning: '찐빵' },
  { hanzi: '满足', pinyin: 'mǎnzú', meaning: '만족하다, 만족시키다' },
  { hanzi: '毛', pinyin: 'máo', meaning: '털, 10전 (돈)' },
  { hanzi: '毛病', pinyin: 'máobìng', meaning: '결점, 고장, 병' },
  { hanzi: '矛盾', pinyin: 'máodùn', meaning: '모순' },
  { hanzi: '冒险', pinyin: 'màoxiǎn', meaning: '모험하다' },
  { hanzi: '贸易', pinyin: 'màoyì', meaning: '무역' },
  { hanzi: '眉毛', pinyin: 'méimao', meaning: '눈썹' },
  { hanzi: '煤炭', pinyin: 'méitàn', meaning: '석탄' },
  { hanzi: '美术', pinyin: 'měishù', meaning: '미술' },
  { hanzi: '魅力', pinyin: 'mèilì', meaning: '매력' },
  { hanzi: '迷路', pinyin: 'mílù', meaning: '길을 잃다' },
  { hanzi: '谜语', pinyin: 'míyǔ', meaning: '수수께끼' },
  { hanzi: '秘密', pinyin: 'mìmì', meaning: '비밀' },
  { hanzi: '秘书', pinyin: 'mìshū', meaning: '비서' },
  { hanzi: '密切', pinyin: 'mìqiè', meaning: '밀접하다' },
  { hanzi: '蜜蜂', pinyin: 'mìfēng', meaning: '꿀벌' },
  { hanzi: '棉花', pinyin: 'miánhua', meaning: '목화, 솜' },
  { hanzi: '面对', pinyin: 'miànduì', meaning: '직면하다, 마주하다' },
  { hanzi: '面积', pinyin: 'miànjī', meaning: '면적' },
  { hanzi: '面临', pinyin: 'miànlín', meaning: '직면하다' },
  { hanzi: '苗条', pinyin: 'miáotiao', meaning: '날씬하다' },
  { hanzi: '描写', pinyin: 'miáoxiě', meaning: '묘사하다' },
  { hanzi: '秒', pinyin: 'miǎo', meaning: '초 (시간)' },
  { hanzi: '民主', pinyin: 'mínzhǔ', meaning: '민주' },
  { hanzi: '名牌', pinyin: 'míngpái', meaning: '유명 브랜드, 명찰' },
  { hanzi: '名片', pinyin: 'míngpiàn', meaning: '명함' },
  { hanzi: '名胜', pinyin: 'míngshèng', meaning: '명승지' },
  { hanzi: '明确', pinyin: 'míngquè', meaning: '명확하다' },
  { hanzi: '明显', pinyin: 'míngxiǎn', meaning: '뚜렷하다, 분명하다' },
  { hanzi: '明信片', pinyin: 'míngxìnpiàn', meaning: '엽서' },
  { hanzi: '明星', pinyin: 'míngxīng', meaning: '스타' },
  { hanzi: '命令', pinyin: 'mìnglìng', meaning: '명령' },
  { hanzi: '命运', pinyin: 'mìngyùn', meaning: '운명' },
  { hanzi: '摸', pinyin: 'mō', meaning: '만지다, 더듬다' },
  { hanzi: '模仿', pinyin: 'mófǎng', meaning: '모방하다' },
  { hanzi: '模糊', pinyin: 'móhu', meaning: '모호하다, 흐릿하다' },
  { hanzi: '摩托车', pinyin: 'mótuōchē', meaning: '오토바이' },
  { hanzi: '陌生', pinyin: 'mòshēng', meaning: '낯설다' },
  { hanzi: '某', pinyin: 'mǒu', meaning: '어떤, 아무' },
  { hanzi: '木头', pinyin: 'mùtou', meaning: '나무, 목재' },
  { hanzi: '目标', pinyin: 'mùbiāo', meaning: '목표' },
  { hanzi: '目录', pinyin: 'mùlù', meaning: '목록, 목차' },
  { hanzi: '目前', pinyin: 'mùqián', meaning: '현재' },
  { hanzi: '哪怕', pinyin: 'nǎpà', meaning: '설령 ~하더라도' },
  { hanzi: '难怪', pinyin: 'nánguài', meaning: '어쩐지' },
  { hanzi: '难看', pinyin: 'nánkàn', meaning: '보기 흉하다' },
  { hanzi: '脑袋', pinyin: 'nǎodai', meaning: '머리' },
  { hanzi: '内科', pinyin: 'nèikē', meaning: '내과' },
  { hanzi: '嫩', pinyin: 'nèn', meaning: '연하다, 부드럽다' },
  { hanzi: '能干', pinyin: 'nénggàn', meaning: '유능하다' },
  { hanzi: '能源', pinyin: 'néngyuán', meaning: '에너지원' },
  { hanzi: '年代', pinyin: 'niándài', meaning: '연대, 시대' },
  { hanzi: '年纪', pinyin: 'niánjì', meaning: '나이' },
  { hanzi: '念', pinyin: 'niàn', meaning: '읽다, 그리워하다' },
  { hanzi: '宁可', pinyin: 'nìngkě', meaning: '차라리 ~할지언정' },
  { hanzi: '牛仔裤', pinyin: 'niúzǎikù', meaning: '청바지' },
  { hanzi: '农民', pinyin: 'nóngmín', meaning: '농민' },
  { hanzi: '农业', pinyin: 'nóngyè', meaning: '농업' },
  { hanzi: '浓', pinyin: 'nóng', meaning: '진하다, 짙다' },
  { hanzi: '女士', pinyin: 'nǚshì', meaning: '여사, 숙녀' },
  { hanzi: '偶然', pinyin: 'ǒurán', meaning: '우연히, 우연하다' },
  { hanzi: '拍', pinyin: 'pāi', meaning: '치다, 찍다' },
  { hanzi: '排队', pinyin: 'páiduì', meaning: '줄을 서다' },
  { hanzi: '排球', pinyin: 'páiqiú', meaning: '배구' },
  { hanzi: '派', pinyin: 'pài', meaning: '파견하다, 파벌' },
  { hanzi: '盼望', pinyin: 'pànwàng', meaning: '간절히 바라다' },
  { hanzi: '培养', pinyin: 'péiyǎng', meaning: '기르다, 양성하다' },
  { hanzi: '赔偿', pinyin: 'péicháng', meaning: '배상하다' },
  { hanzi: '佩服', pinyin: 'pèifú', meaning: '감탄하다, 탄복하다' },
  { hanzi: '配合', pinyin: 'pèihé', meaning: '협력하다, 호흡을 맞추다' },
  { hanzi: '盆', pinyin: 'pén', meaning: '대야, 화분' },
  { hanzi: '碰见', pinyin: 'pèngjiàn', meaning: '우연히 만나다' },
  { hanzi: '批', pinyin: 'pī', meaning: '비판하다, 무더기' },
  { hanzi: '批准', pinyin: 'pīzhǔn', meaning: '비준하다, 허가하다' },
  { hanzi: '披', pinyin: 'pī', meaning: '걸치다' },
  { hanzi: '皮鞋', pinyin: 'píxié', meaning: '구두' },
  { hanzi: '疲劳', pinyin: 'píláo', meaning: '피로하다' },
  { hanzi: '匹', pinyin: 'pǐ', meaning: '필 (말·천을 세는 단위)' },
  { hanzi: '片', pinyin: 'piàn', meaning: '조각, 편 (얇은 것을 세는 단위)' },
  { hanzi: '片面', pinyin: 'piànmiàn', meaning: '일방적이다, 편면적이다' },
  { hanzi: '飘', pinyin: 'piāo', meaning: '나부끼다, 흩날리다' },
  { hanzi: '频道', pinyin: 'píndào', meaning: '채널' },
  { hanzi: '品种', pinyin: 'pǐnzhǒng', meaning: '품종' },
  { hanzi: '平', pinyin: 'píng', meaning: '평평하다' },
  { hanzi: '平常', pinyin: 'píngcháng', meaning: '평소, 평범하다' },
  { hanzi: '平等', pinyin: 'píngděng', meaning: '평등하다' },
  { hanzi: '平方', pinyin: 'píngfāng', meaning: '제곱, 평방미터' },
  { hanzi: '平衡', pinyin: 'pínghéng', meaning: '균형' },
  { hanzi: '平静', pinyin: 'píngjìng', meaning: '평온하다' },
  { hanzi: '平均', pinyin: 'píngjūn', meaning: '평균' },
  { hanzi: '评价', pinyin: 'píngjià', meaning: '평가하다' },
  { hanzi: '凭', pinyin: 'píng', meaning: '~에 근거하여, 기대다' },
  { hanzi: '迫切', pinyin: 'pòqiè', meaning: '절박하다' },
  { hanzi: '破产', pinyin: 'pòchǎn', meaning: '파산하다' },
  { hanzi: '破坏', pinyin: 'pòhuài', meaning: '파괴하다' },
  { hanzi: '朴素', pinyin: 'pǔsù', meaning: '소박하다' },
  { hanzi: '期待', pinyin: 'qīdài', meaning: '기대하다' },
  { hanzi: '期间', pinyin: 'qījiān', meaning: '기간' },
  { hanzi: '其余', pinyin: 'qíyú', meaning: '나머지' },
  { hanzi: '奇迹', pinyin: 'qíjì', meaning: '기적' },
  { hanzi: '企图', pinyin: 'qǐtú', meaning: '꾀하다, 시도' },
  { hanzi: '企业', pinyin: 'qǐyè', meaning: '기업' },
  { hanzi: '启发', pinyin: 'qǐfā', meaning: '일깨우다, 계발하다' },
  { hanzi: '气氛', pinyin: 'qìfēn', meaning: '분위기' },
  { hanzi: '汽油', pinyin: 'qìyóu', meaning: '휘발유' },
  { hanzi: '牵', pinyin: 'qiān', meaning: '끌다' },
  { hanzi: '谦虚', pinyin: 'qiānxū', meaning: '겸손하다' },
  { hanzi: '签字', pinyin: 'qiānzì', meaning: '서명하다' },
  { hanzi: '前途', pinyin: 'qiántú', meaning: '전도, 앞날' },
  { hanzi: '浅', pinyin: 'qiǎn', meaning: '얕다, (색이) 연하다' },
  { hanzi: '欠', pinyin: 'qiàn', meaning: '빚지다, 모자라다' },
  { hanzi: '枪', pinyin: 'qiāng', meaning: '총' },
  { hanzi: '强调', pinyin: 'qiángdiào', meaning: '강조하다' },
  { hanzi: '强烈', pinyin: 'qiángliè', meaning: '강렬하다' },
  { hanzi: '抢', pinyin: 'qiǎng', meaning: '빼앗다, 앞다투다' },
  { hanzi: '悄悄', pinyin: 'qiāoqiāo', meaning: '몰래, 살금살금' },
  { hanzi: '瞧', pinyin: 'qiáo', meaning: '보다' },
  { hanzi: '巧妙', pinyin: 'qiǎomiào', meaning: '교묘하다' },
  { hanzi: '切', pinyin: 'qiē', meaning: '썰다, 자르다' },
  { hanzi: '亲爱', pinyin: 'qīnài', meaning: '친애하다, 사랑하는' },
  { hanzi: '亲切', pinyin: 'qīnqiè', meaning: '친절하다' },
  { hanzi: '亲自', pinyin: 'qīnzì', meaning: '직접, 몸소' },
  { hanzi: '侵略', pinyin: 'qīnlu:è', meaning: '침략하다' },
  { hanzi: '勤奋', pinyin: 'qínfèn', meaning: '부지런하다' },
  { hanzi: '勤劳', pinyin: 'qínláo', meaning: '근면하다' },
  { hanzi: '青', pinyin: 'qīng', meaning: '푸르다' },
  { hanzi: '青春', pinyin: 'qīngchūn', meaning: '청춘' },
  { hanzi: '青少年', pinyin: 'qīngshàonián', meaning: '청소년' },
  { hanzi: '轻视', pinyin: 'qīngshì', meaning: '경시하다' },
  { hanzi: '清淡', pinyin: 'qīngdàn', meaning: '담백하다' },
  { hanzi: '情景', pinyin: 'qíngjǐng', meaning: '광경, 장면' },
  { hanzi: '情绪', pinyin: 'qíngxù', meaning: '기분, 정서' },
  { hanzi: '请求', pinyin: 'qǐngqiú', meaning: '요청하다' },
  { hanzi: '庆祝', pinyin: 'qìngzhù', meaning: '경축하다' },
  { hanzi: '球迷', pinyin: 'qiúmí', meaning: '축구·야구 팬' },
  { hanzi: '趋势', pinyin: 'qūshì', meaning: '추세' },
  { hanzi: '取消', pinyin: 'qǔxiāo', meaning: '취소하다' },
  { hanzi: '娶', pinyin: 'qǔ', meaning: '아내를 얻다, 장가들다' },
  { hanzi: '去世', pinyin: 'qùshì', meaning: '세상을 떠나다' },
  { hanzi: '圈', pinyin: 'quān', meaning: '원, 동그라미' },
  { hanzi: '全面', pinyin: 'quánmiàn', meaning: '전면적이다' },
  { hanzi: '权力', pinyin: 'quánlì', meaning: '권력' },
  { hanzi: '权利', pinyin: 'quánlì', meaning: '권리' },
  { hanzi: '劝', pinyin: 'quàn', meaning: '권하다, 타이르다' },
  { hanzi: '缺乏', pinyin: 'quēfá', meaning: '결핍되다' },
  { hanzi: '确定', pinyin: 'quèdìng', meaning: '확정하다' },
  { hanzi: '确认', pinyin: 'quèrèn', meaning: '확인하다' },
  { hanzi: '燃烧', pinyin: 'ránshāo', meaning: '연소하다, 타다' },
  { hanzi: '嚷', pinyin: 'rǎng', meaning: '고함치다' },
  { hanzi: '绕', pinyin: 'rào', meaning: '감다, 돌다, 우회하다' },
  { hanzi: '热爱', pinyin: 'rèài', meaning: '열렬히 사랑하다' },
  { hanzi: '热烈', pinyin: 'rèliè', meaning: '열렬하다' },
  { hanzi: '热心', pinyin: 'rèxīn', meaning: '열성적이다' },
  { hanzi: '人才', pinyin: 'réncái', meaning: '인재' },
  { hanzi: '人口', pinyin: 'rénkǒu', meaning: '인구' },
  { hanzi: '人类', pinyin: 'rénlèi', meaning: '인류' },
  { hanzi: '人生', pinyin: 'rénshēng', meaning: '인생' },
  { hanzi: '人事', pinyin: 'rénshì', meaning: '인사' },
  { hanzi: '人物', pinyin: 'rénwù', meaning: '인물' },
  { hanzi: '人员', pinyin: 'rényuán', meaning: '인원' },
  { hanzi: '忍不住', pinyin: 'rěnbuzhù', meaning: '참을 수 없다' },
  { hanzi: '日常', pinyin: 'rìcháng', meaning: '일상' },
  { hanzi: '日程', pinyin: 'rìchéng', meaning: '일정' },
  { hanzi: '日历', pinyin: 'rìlì', meaning: '달력' },
  { hanzi: '日期', pinyin: 'rìqī', meaning: '날짜' },
  { hanzi: '日用品', pinyin: 'rìyòngpǐn', meaning: '일용품' },
  { hanzi: '荣幸', pinyin: 'róngxìng', meaning: '영광스럽다' },
  { hanzi: '荣誉', pinyin: 'róngyù', meaning: '영예' },
  { hanzi: '融化', pinyin: 'rónghuà', meaning: '녹다' },
  { hanzi: '如何', pinyin: 'rúhé', meaning: '어떻게' },
  { hanzi: '如今', pinyin: 'rújīn', meaning: '지금, 오늘날' },
  { hanzi: '软件', pinyin: 'ruǎnjiàn', meaning: '소프트웨어' },
  { hanzi: '弱', pinyin: 'ruò', meaning: '약하다' },
  { hanzi: '洒', pinyin: 'sǎ', meaning: '뿌리다, 엎지르다' },
  { hanzi: '嗓子', pinyin: 'sǎngzi', meaning: '목, 목소리' },
  { hanzi: '杀', pinyin: 'shā', meaning: '죽이다' },
  { hanzi: '沙漠', pinyin: 'shāmò', meaning: '사막' },
  { hanzi: '沙滩', pinyin: 'shātān', meaning: '모래사장' },
  { hanzi: '傻', pinyin: 'shǎ', meaning: '어리석다, 바보 같다' },
  { hanzi: '晒', pinyin: 'shài', meaning: '햇볕을 쬐다, 말리다' },
  { hanzi: '删除', pinyin: 'shānchú', meaning: '삭제하다' },
  { hanzi: '闪电', pinyin: 'shǎndiàn', meaning: '번개' },
  { hanzi: '扇子', pinyin: 'shànzi', meaning: '부채' },
  { hanzi: '善良', pinyin: 'shànliáng', meaning: '착하다, 선량하다' },
  { hanzi: '善于', pinyin: 'shànyú', meaning: '~에 능숙하다' },
  { hanzi: '商品', pinyin: 'shāngpǐn', meaning: '상품' },
  { hanzi: '商业', pinyin: 'shāngyè', meaning: '상업' },
  { hanzi: '上当', pinyin: 'shàngdàng', meaning: '속다' },
  { hanzi: '勺子', pinyin: 'sháozi', meaning: '숟가락' },
  { hanzi: '舌头', pinyin: 'shétou', meaning: '혀' },
  { hanzi: '蛇', pinyin: 'shé', meaning: '뱀' },
  { hanzi: '舍不得', pinyin: 'shěbude', meaning: '아까워하다, 아쉬워하다' },
  { hanzi: '设备', pinyin: 'shèbèi', meaning: '설비' },
  { hanzi: '设计', pinyin: 'shèjì', meaning: '설계하다, 디자인' },
  { hanzi: '设施', pinyin: 'shèshī', meaning: '시설' },
  { hanzi: '射击', pinyin: 'shèjī', meaning: '사격하다' },
  { hanzi: '摄影', pinyin: 'shèyǐng', meaning: '촬영하다' },
  { hanzi: '伸', pinyin: 'shēn', meaning: '펴다, 내밀다' },
  { hanzi: '身材', pinyin: 'shēncái', meaning: '몸매, 체격' },
  { hanzi: '身份', pinyin: 'shēnfèn', meaning: '신분' },
  { hanzi: '深刻', pinyin: 'shēnkè', meaning: '깊다, 심각하다' },
  { hanzi: '神话', pinyin: 'shénhuà', meaning: '신화' },
  { hanzi: '神经', pinyin: 'shénjīng', meaning: '신경' },
  { hanzi: '神秘', pinyin: 'shénmì', meaning: '신비하다' },
  { hanzi: '升', pinyin: 'shēng', meaning: '오르다, 리터' },
  { hanzi: '生产', pinyin: 'shēngchǎn', meaning: '생산하다' },
  { hanzi: '生动', pinyin: 'shēngdòng', meaning: '생동감 있다' },
  { hanzi: '声调', pinyin: 'shēngdiào', meaning: '성조' },
  { hanzi: '绳子', pinyin: 'shéngzi', meaning: '밧줄, 끈' },
  { hanzi: '省略', pinyin: 'shěnglu:è', meaning: '생략하다' },
  { hanzi: '胜利', pinyin: 'shènglì', meaning: '승리' },
  { hanzi: '失眠', pinyin: 'shīmián', meaning: '잠을 못 이루다' },
  { hanzi: '失去', pinyin: 'shīqù', meaning: '잃다' },
  { hanzi: '失业', pinyin: 'shīyè', meaning: '실업하다' },
  { hanzi: '诗', pinyin: 'shī', meaning: '시' },
  { hanzi: '石头', pinyin: 'shítou', meaning: '돌' },
  { hanzi: '时代', pinyin: 'shídài', meaning: '시대' },
  { hanzi: '时刻', pinyin: 'shíkè', meaning: '시각, 늘' },
  { hanzi: '时髦', pinyin: 'shímáo', meaning: '유행하다, 세련되다' },
  { hanzi: '时期', pinyin: 'shíqī', meaning: '시기' },
  { hanzi: '时尚', pinyin: 'shíshàng', meaning: '유행, 패션' },
  { hanzi: '实话', pinyin: 'shíhuà', meaning: '실화, 솔직한 말' },
  { hanzi: '实践', pinyin: 'shíjiàn', meaning: '실천하다' },
  { hanzi: '实习', pinyin: 'shíxí', meaning: '실습하다, 인턴' },
  { hanzi: '实现', pinyin: 'shíxiàn', meaning: '실현하다' },
  { hanzi: '实行', pinyin: 'shíxíng', meaning: '실행하다' },
  { hanzi: '实验', pinyin: 'shíyàn', meaning: '실험' },
  { hanzi: '实用', pinyin: 'shíyòng', meaning: '실용적이다' },
  { hanzi: '食物', pinyin: 'shíwù', meaning: '음식물' },
  { hanzi: '使劲儿', pinyin: 'shǐjìnr', meaning: '힘을 쓰다' },
  { hanzi: '始终', pinyin: 'shǐzhōng', meaning: '처음부터 끝까지, 줄곧' },
  { hanzi: '士兵', pinyin: 'shìbīng', meaning: '병사' },
  { hanzi: '似的', pinyin: 'shìde', meaning: '~과 같다' },
  { hanzi: '似乎', pinyin: 'sìhū', meaning: '마치 ~인 것 같다' },
  { hanzi: '事实', pinyin: 'shìshí', meaning: '사실' },
  { hanzi: '事物', pinyin: 'shìwù', meaning: '사물' },
  { hanzi: '事先', pinyin: 'shìxiān', meaning: '사전에, 미리' },
  { hanzi: '试卷', pinyin: 'shìjuàn', meaning: '시험지' },
  { hanzi: '是否', pinyin: 'shìfǒu', meaning: '~인지 아닌지' },
  { hanzi: '收获', pinyin: 'shōuhuò', meaning: '수확, 성과' },
  { hanzi: '收据', pinyin: 'shōujù', meaning: '영수증' },
  { hanzi: '手工', pinyin: 'shǒugōng', meaning: '수공, 수작업' },
  { hanzi: '手术', pinyin: 'shǒushù', meaning: '수술' },
  { hanzi: '手套', pinyin: 'shǒutào', meaning: '장갑' },
  { hanzi: '手续', pinyin: 'shǒuxù', meaning: '수속' },
  { hanzi: '手指', pinyin: 'shǒuzhǐ', meaning: '손가락' },
  { hanzi: '寿命', pinyin: 'shòumìng', meaning: '수명' },
  { hanzi: '受伤', pinyin: 'shòushāng', meaning: '다치다' },
  { hanzi: '书架', pinyin: 'shūjià', meaning: '책장' },
  { hanzi: '梳子', pinyin: 'shūzi', meaning: '빗' },
  { hanzi: '舒适', pinyin: 'shūshì', meaning: '쾌적하다, 편안하다' },
  { hanzi: '输入', pinyin: 'shūrù', meaning: '입력하다' },
  { hanzi: '蔬菜', pinyin: 'shūcài', meaning: '채소' },
  { hanzi: '熟练', pinyin: 'shúliàn', meaning: '능숙하다' },
  { hanzi: '属于', pinyin: 'shǔyú', meaning: '~에 속하다' },
  { hanzi: '鼠标', pinyin: 'shǔbiāo', meaning: '마우스' },
  { hanzi: '数据', pinyin: 'shùjù', meaning: '데이터' },
  { hanzi: '数码', pinyin: 'shùmǎ', meaning: '디지털, 숫자' },
  { hanzi: '摔', pinyin: 'shuāi', meaning: '넘어지다, 떨어뜨리다' },
  { hanzi: '甩', pinyin: 'shuǎi', meaning: '휘두르다, 내던지다' },
  { hanzi: '双方', pinyin: 'shuāngfāng', meaning: '쌍방' },
  { hanzi: '税', pinyin: 'shuì', meaning: '세금' },
  { hanzi: '说不定', pinyin: 'shuōbudìng', meaning: '아마, ~일지도 모른다' },
  { hanzi: '说服', pinyin: 'shuōfú', meaning: '설득하다' },
  { hanzi: '丝绸', pinyin: 'sīchóu', meaning: '비단' },
  { hanzi: '丝毫', pinyin: 'sīháo', meaning: '조금도' },
  { hanzi: '私人', pinyin: 'sīrén', meaning: '개인, 사적인' },
  { hanzi: '思考', pinyin: 'sīkǎo', meaning: '사고하다, 깊이 생각하다' },
  { hanzi: '思想', pinyin: 'sīxiǎng', meaning: '사상' },
  { hanzi: '撕', pinyin: 'sī', meaning: '찢다' },
  { hanzi: '寺庙', pinyin: 'sìmiào', meaning: '사원, 절' },
  { hanzi: '宿舍', pinyin: 'sùshè', meaning: '기숙사' },
  { hanzi: '随时', pinyin: 'suíshí', meaning: '수시로, 언제든지' },
  { hanzi: '碎', pinyin: 'suì', meaning: '부서지다, 깨지다' },
  { hanzi: '损失', pinyin: 'sǔnshī', meaning: '손실' },
  { hanzi: '缩短', pinyin: 'suōduǎn', meaning: '단축하다' },
  { hanzi: '缩小', pinyin: 'suōxiǎo', meaning: '축소하다' },
  { hanzi: '所', pinyin: 'suǒ', meaning: '곳, 채 (건물을 세는 단위)' },
  { hanzi: '所谓', pinyin: 'suǒwèi', meaning: '이른바' },
  { hanzi: '锁', pinyin: 'suǒ', meaning: '자물쇠, 잠그다' },
  { hanzi: '塔', pinyin: 'tǎ', meaning: '탑' },
  { hanzi: '台阶', pinyin: 'táijiē', meaning: '계단, 층계' },
  { hanzi: '太极拳', pinyin: 'tàijíquán', meaning: '태극권' },
  { hanzi: '太太', pinyin: 'tàitai', meaning: '부인, 아내' },
  { hanzi: '谈判', pinyin: 'tánpàn', meaning: '협상하다' },
  { hanzi: '坦率', pinyin: 'tǎnshuài', meaning: '솔직하다' },
  { hanzi: '烫', pinyin: 'tàng', meaning: '데다, 뜨겁다, 파마하다' },
  { hanzi: '逃', pinyin: 'táo', meaning: '도망치다' },
  { hanzi: '逃避', pinyin: 'táobì', meaning: '도피하다' },
  { hanzi: '桃', pinyin: 'táo', meaning: '복숭아' },
  { hanzi: '套', pinyin: 'tào', meaning: '세트, 씌우다' },
  { hanzi: '特殊', pinyin: 'tèshū', meaning: '특수하다' },
  { hanzi: '特意', pinyin: 'tèyì', meaning: '특별히, 일부러' },
  { hanzi: '特征', pinyin: 'tèzhēng', meaning: '특징' },
  { hanzi: '疼爱', pinyin: 'téngài', meaning: '매우 귀여워하다' },
  { hanzi: '提', pinyin: 'tí', meaning: '들다, 제기하다' },
  { hanzi: '提倡', pinyin: 'tíchàng', meaning: '제창하다' },
  { hanzi: '提纲', pinyin: 'tígāng', meaning: '요점, 개요' },
  { hanzi: '提问', pinyin: 'tíwèn', meaning: '질문하다' },
  { hanzi: '题目', pinyin: 'tímù', meaning: '제목, 문제' },
  { hanzi: '体会', pinyin: 'tǐhuì', meaning: '체득하다, 느끼다' },
  { hanzi: '体积', pinyin: 'tǐjī', meaning: '부피' },
  { hanzi: '体贴', pinyin: 'tǐtiē', meaning: '자상하게 돌보다' },
  { hanzi: '体现', pinyin: 'tǐxiàn', meaning: '구현하다, 드러내다' },
  { hanzi: '体验', pinyin: 'tǐyàn', meaning: '체험하다' },
  { hanzi: '天空', pinyin: 'tiānkōng', meaning: '하늘' },
  { hanzi: '天真', pinyin: 'tiānzhēn', meaning: '천진하다, 순진하다' },
  { hanzi: '田野', pinyin: 'tiányě', meaning: '들판' },
  { hanzi: '挑战', pinyin: 'tiǎozhàn', meaning: '도전하다' },
  { hanzi: '通常', pinyin: 'tōngcháng', meaning: '보통, 통상' },
  { hanzi: '通讯', pinyin: 'tōngxùn', meaning: '통신' },
  { hanzi: '同时', pinyin: 'tóngshí', meaning: '동시에' },
  { hanzi: '铜', pinyin: 'tóng', meaning: '구리' },
  { hanzi: '统一', pinyin: 'tǒngyī', meaning: '통일하다' },
  { hanzi: '统治', pinyin: 'tǒngzhì', meaning: '통치하다' },
  { hanzi: '痛苦', pinyin: 'tòngkǔ', meaning: '고통스럽다' },
  { hanzi: '痛快', pinyin: 'tòngkuài', meaning: '통쾌하다, 즐겁다' },
  { hanzi: '投资', pinyin: 'tóuzī', meaning: '투자하다' },
  { hanzi: '透明', pinyin: 'tòumíng', meaning: '투명하다' },
  { hanzi: '突出', pinyin: 'tūchū', meaning: '두드러지다' },
  { hanzi: '土地', pinyin: 'tǔdì', meaning: '토지, 땅' },
  { hanzi: '土豆', pinyin: 'tǔdòu', meaning: '감자' },
  { hanzi: '吐', pinyin: 'tǔ', meaning: '토하다, 뱉다' },
  { hanzi: '兔子', pinyin: 'tùzi', meaning: '토끼' },
  { hanzi: '团', pinyin: 'tuán', meaning: '단체, 뭉치' },
  { hanzi: '推辞', pinyin: 'tuīcí', meaning: '사양하다' },
  { hanzi: '推广', pinyin: 'tuīguǎng', meaning: '보급하다, 확대하다' },
  { hanzi: '推荐', pinyin: 'tuījiàn', meaning: '추천하다' },
  { hanzi: '退', pinyin: 'tuì', meaning: '물러나다, 반환하다' },
  { hanzi: '退步', pinyin: 'tuìbù', meaning: '퇴보하다' },
  { hanzi: '退休', pinyin: 'tuìxiū', meaning: '퇴직하다, 은퇴하다' },
  { hanzi: '歪', pinyin: 'wāi', meaning: '비뚤다' },
  { hanzi: '外交', pinyin: 'wàijiāo', meaning: '외교' },
  { hanzi: '弯', pinyin: 'wān', meaning: '굽다, 구부리다' },
  { hanzi: '完美', pinyin: 'wánměi', meaning: '완벽하다' },
  { hanzi: '完善', pinyin: 'wánshàn', meaning: '완벽하다, 완비하다' },
  { hanzi: '完整', pinyin: 'wánzhěng', meaning: '완전하다' },
  { hanzi: '玩具', pinyin: 'wánjù', meaning: '장난감' },
  { hanzi: '万一', pinyin: 'wànyī', meaning: '만일' },
  { hanzi: '王子', pinyin: 'wángzǐ', meaning: '왕자' },
  { hanzi: '往返', pinyin: 'wǎngfǎn', meaning: '왕복하다' },
  { hanzi: '危害', pinyin: 'wēihài', meaning: '해치다, 위해' },
  { hanzi: '威胁', pinyin: 'wēixié', meaning: '위협하다' },
  { hanzi: '微笑', pinyin: 'wēixiào', meaning: '미소' },
  { hanzi: '围巾', pinyin: 'wéijīn', meaning: '목도리, 스카프' },
  { hanzi: '围绕', pinyin: 'wéirào', meaning: '둘러싸다' },
  { hanzi: '违反', pinyin: 'wéifǎn', meaning: '위반하다' },
  { hanzi: '唯一', pinyin: 'wéiyī', meaning: '유일하다' },
  { hanzi: '维护', pinyin: 'wéihù', meaning: '유지하고 보호하다' },
  { hanzi: '伟大', pinyin: 'wěidà', meaning: '위대하다' },
  { hanzi: '尾巴', pinyin: 'wěiba', meaning: '꼬리' },
  { hanzi: '委屈', pinyin: 'wěiqu', meaning: '억울하다' },
  { hanzi: '委托', pinyin: 'wěituō', meaning: '위탁하다' },
  { hanzi: '卫生间', pinyin: 'wèishēngjiān', meaning: '화장실' },
  { hanzi: '未必', pinyin: 'wèibì', meaning: '반드시 ~한 것은 아니다' },
  { hanzi: '未来', pinyin: 'wèilái', meaning: '미래' },
  { hanzi: '位置', pinyin: 'wèizhi', meaning: '위치' },
  { hanzi: '胃', pinyin: 'wèi', meaning: '위 (신체)' },
  { hanzi: '温暖', pinyin: 'wēnnuǎn', meaning: '따뜻하다' },
  { hanzi: '温柔', pinyin: 'wēnróu', meaning: '온유하다, 부드럽다' },
  { hanzi: '文件', pinyin: 'wénjiàn', meaning: '문서, 파일' },
  { hanzi: '文具', pinyin: 'wénjù', meaning: '문구' },
  { hanzi: '文明', pinyin: 'wénmíng', meaning: '문명' },
  { hanzi: '文学', pinyin: 'wénxué', meaning: '문학' },
  { hanzi: '闻', pinyin: 'wén', meaning: '냄새를 맡다' },
  { hanzi: '吻', pinyin: 'wěn', meaning: '키스하다, 입맞춤' },
  { hanzi: '稳定', pinyin: 'wěndìng', meaning: '안정되다' },
  { hanzi: '问候', pinyin: 'wènhòu', meaning: '안부를 묻다' },
  { hanzi: '卧室', pinyin: 'wòshì', meaning: '침실' },
  { hanzi: '屋子', pinyin: 'wūzi', meaning: '방, 집' },
  { hanzi: '无奈', pinyin: 'wúnài', meaning: '어찌할 도리가 없다' },
  { hanzi: '无数', pinyin: 'wúshù', meaning: '무수하다' },
  { hanzi: '武器', pinyin: 'wǔqì', meaning: '무기' },
  { hanzi: '武术', pinyin: 'wǔshù', meaning: '무술' },
  { hanzi: '物理', pinyin: 'wùlǐ', meaning: '물리' },
  { hanzi: '物质', pinyin: 'wùzhì', meaning: '물질' },
  { hanzi: '雾', pinyin: 'wù', meaning: '안개' },
  { hanzi: '吸收', pinyin: 'xīshōu', meaning: '흡수하다' },
  { hanzi: '戏剧', pinyin: 'xìjù', meaning: '연극, 희극' },
  { hanzi: '系', pinyin: 'xì', meaning: '매다, 관계되다, 학과' },
  { hanzi: '系领带', pinyin: 'xìlǐngdài', meaning: '넥타이를 매다' },
  { hanzi: '系统', pinyin: 'xìtǒng', meaning: '시스템, 체계' },
  { hanzi: '细节', pinyin: 'xìjié', meaning: '세부 사항, 디테일' },
  { hanzi: '瞎', pinyin: 'xiā', meaning: '눈이 멀다, 함부로' },
  { hanzi: '下载', pinyin: 'xiàzǎi', meaning: '다운로드하다' },
  { hanzi: '吓', pinyin: 'xià', meaning: '놀라게 하다, 겁주다' },
  { hanzi: '鲜艳', pinyin: 'xiānyàn', meaning: '(색이) 산뜻하고 아름답다' },
  { hanzi: '显得', pinyin: 'xiǎnde', meaning: '~처럼 보이다' },
  { hanzi: '显然', pinyin: 'xiǎnrán', meaning: '분명하다, 명백하다' },
  { hanzi: '显示', pinyin: 'xiǎnshì', meaning: '보여 주다, 디스플레이' },
  { hanzi: '县', pinyin: 'xiàn', meaning: '현 (행정 구역)' },
  { hanzi: '现金', pinyin: 'xiànjīn', meaning: '현금' },
  { hanzi: '现实', pinyin: 'xiànshí', meaning: '현실' },
  { hanzi: '现象', pinyin: 'xiànxiàng', meaning: '현상' },
  { hanzi: '相处', pinyin: 'xiāngchǔ', meaning: '함께 지내다' },
  { hanzi: '相当', pinyin: 'xiāngdāng', meaning: '상당하다, 꽤' },
  { hanzi: '相对', pinyin: 'xiāngduì', meaning: '상대적으로' },
  { hanzi: '相关', pinyin: 'xiāngguān', meaning: '관련되다' },
  { hanzi: '相似', pinyin: 'xiāngsì', meaning: '닮다, 비슷하다' },
  { hanzi: '享受', pinyin: 'xiǎngshòu', meaning: '누리다, 즐기다' },
  { hanzi: '想念', pinyin: 'xiǎngniàn', meaning: '그리워하다' },
  { hanzi: '想象', pinyin: 'xiǎngxiàng', meaning: '상상하다' },
  { hanzi: '项', pinyin: 'xiàng', meaning: '항목' },
  { hanzi: '项链', pinyin: 'xiàngliàn', meaning: '목걸이' },
  { hanzi: '项目', pinyin: 'xiàngmù', meaning: '항목, 프로젝트' },
  { hanzi: '象棋', pinyin: 'xiàngqí', meaning: '중국 장기' },
  { hanzi: '象征', pinyin: 'xiàngzhēng', meaning: '상징' },
  { hanzi: '橡皮', pinyin: 'xiàngpí', meaning: '지우개' },
  { hanzi: '消费', pinyin: 'xiāofèi', meaning: '소비하다' },
  { hanzi: '消化', pinyin: 'xiāohuà', meaning: '소화하다' },
  { hanzi: '消灭', pinyin: 'xiāomiè', meaning: '소멸시키다, 없애다' },
  { hanzi: '消失', pinyin: 'xiāoshī', meaning: '사라지다' },
  { hanzi: '销售', pinyin: 'xiāoshòu', meaning: '판매하다' },
  { hanzi: '小吃', pinyin: 'xiǎochī', meaning: '간식' },
  { hanzi: '小伙子', pinyin: 'xiǎohuǒzi', meaning: '젊은이' },
  { hanzi: '小麦', pinyin: 'xiǎomài', meaning: '밀' },
  { hanzi: '小气', pinyin: 'xiǎoqì', meaning: '인색하다, 쩨쩨하다' },
  { hanzi: '小偷', pinyin: 'xiǎotōu', meaning: '도둑' },
  { hanzi: '孝顺', pinyin: 'xiàoshùn', meaning: '효도하다' },
  { hanzi: '效率', pinyin: 'xiàolǜ', meaning: '효율' },
  { hanzi: '歇', pinyin: 'xiē', meaning: '쉬다' },
  { hanzi: '协调', pinyin: 'xiétiáo', meaning: '조화롭다, 조정하다' },
  { hanzi: '斜', pinyin: 'xié', meaning: '비스듬하다' },
  { hanzi: '心理', pinyin: 'xīnlǐ', meaning: '심리' },
  { hanzi: '心脏', pinyin: 'xīnzàng', meaning: '심장' },
  { hanzi: '欣赏', pinyin: 'xīnshǎng', meaning: '감상하다, 마음에 들어 하다' },
  { hanzi: '信封', pinyin: 'xìnfēng', meaning: '편지 봉투' },
  { hanzi: '信号', pinyin: 'xìnhào', meaning: '신호' },
  { hanzi: '信息', pinyin: 'xìnxī', meaning: '정보, 메시지' },
  { hanzi: '行动', pinyin: 'xíngdòng', meaning: '행동하다' },
  { hanzi: '行人', pinyin: 'xíngrén', meaning: '행인' },
  { hanzi: '行为', pinyin: 'xíngwéi', meaning: '행위' },
  { hanzi: '行业', pinyin: 'hángyè', meaning: '업종, 업계' },
  { hanzi: '形成', pinyin: 'xíngchéng', meaning: '형성하다' },
  { hanzi: '形容', pinyin: 'xíngróng', meaning: '형용하다, 묘사하다' },
  { hanzi: '形式', pinyin: 'xíngshì', meaning: '형식' },
  { hanzi: '形势', pinyin: 'xíngshì', meaning: '형세, 정세' },
  { hanzi: '形象', pinyin: 'xíngxiàng', meaning: '이미지, 형상' },
  { hanzi: '形状', pinyin: 'xíngzhuàng', meaning: '형상, 모양' },
  { hanzi: '幸亏', pinyin: 'xìngkuī', meaning: '다행히' },
  { hanzi: '幸运', pinyin: 'xìngyùn', meaning: '행운' },
  { hanzi: '性质', pinyin: 'xìngzhì', meaning: '성질' },
  { hanzi: '兄弟', pinyin: 'xiōngdì', meaning: '형제' },
  { hanzi: '胸', pinyin: 'xiōng', meaning: '가슴' },
  { hanzi: '雄伟', pinyin: 'xióngwěi', meaning: '웅장하다' },
  { hanzi: '休闲', pinyin: 'xiūxián', meaning: '레저, 한가롭게 지내다' },
  { hanzi: '修改', pinyin: 'xiūgǎi', meaning: '수정하다' },
  { hanzi: '虚心', pinyin: 'xūxīn', meaning: '겸허하다' },
  { hanzi: '叙述', pinyin: 'xùshù', meaning: '서술하다' },
  { hanzi: '宣布', pinyin: 'xuānbù', meaning: '선포하다, 발표하다' },
  { hanzi: '宣传', pinyin: 'xuānchuán', meaning: '선전하다, 홍보하다' },
  { hanzi: '选举', pinyin: 'xuǎnjǔ', meaning: '선거하다' },
  { hanzi: '学期', pinyin: 'xuéqī', meaning: '학기' },
  { hanzi: '学术', pinyin: 'xuéshù', meaning: '학술' },
  { hanzi: '学问', pinyin: 'xuéwèn', meaning: '학문' },
  { hanzi: '寻找', pinyin: 'xúnzhǎo', meaning: '찾다' },
  { hanzi: '询问', pinyin: 'xúnwèn', meaning: '문의하다' },
  { hanzi: '迅速', pinyin: 'xùnsù', meaning: '신속하다' },
  { hanzi: '训练', pinyin: 'xùnliàn', meaning: '훈련하다' },
  { hanzi: '延长', pinyin: 'yáncháng', meaning: '연장하다' },
  { hanzi: '严肃', pinyin: 'yánsù', meaning: '엄숙하다, 진지하다' },
  { hanzi: '宴会', pinyin: 'yànhuì', meaning: '연회' },
  { hanzi: '阳台', pinyin: 'yángtái', meaning: '베란다, 발코니' },
  { hanzi: '痒', pinyin: 'yǎng', meaning: '가렵다' },
  { hanzi: '样式', pinyin: 'yàngshì', meaning: '양식, 스타일' },
  { hanzi: '腰', pinyin: 'yāo', meaning: '허리' },
  { hanzi: '摇', pinyin: 'yáo', meaning: '흔들다' },
  { hanzi: '咬', pinyin: 'yǎo', meaning: '물다, 깨물다' },
  { hanzi: '要不', pinyin: 'yàobù', meaning: '그렇지 않으면' },
  { hanzi: '要是', pinyin: 'yàoshi', meaning: '만약 ~라면' },
  { hanzi: '业务', pinyin: 'yèwù', meaning: '업무' },
  { hanzi: '业余', pinyin: 'yèyú', meaning: '여가의, 아마추어' },
  { hanzi: '夜', pinyin: 'yè', meaning: '밤' },
  { hanzi: '液体', pinyin: 'yètǐ', meaning: '액체' },
  { hanzi: '一辈子', pinyin: 'yībèizi', meaning: '한평생' },
  { hanzi: '一旦', pinyin: 'yīdàn', meaning: '일단 ~하면' },
  { hanzi: '一路', pinyin: 'yīlù', meaning: '도중, 가는 길 내내' },
  { hanzi: '一致', pinyin: 'yīzhì', meaning: '일치하다' },
  { hanzi: '依然', pinyin: 'yīrán', meaning: '여전히' },
  { hanzi: '移动', pinyin: 'yídòng', meaning: '이동하다' },
  { hanzi: '移民', pinyin: 'yímín', meaning: '이민하다' },
  { hanzi: '遗憾', pinyin: 'yíhàn', meaning: '유감스럽다' },
  { hanzi: '疑问', pinyin: 'yíwèn', meaning: '의문' },
  { hanzi: '乙', pinyin: 'yǐ', meaning: '을 (둘째)' },
  { hanzi: '以及', pinyin: 'yǐjí', meaning: '및, 그리고' },
  { hanzi: '以来', pinyin: 'yǐlái', meaning: '이래, 이후' },
  { hanzi: '义务', pinyin: 'yìwù', meaning: '의무' },
  { hanzi: '议论', pinyin: 'yìlùn', meaning: '의논하다, 논의하다' },
  { hanzi: '意外', pinyin: 'yìwài', meaning: '의외, 뜻밖의 사고' },
  { hanzi: '意义', pinyin: 'yìyì', meaning: '의의, 의미' },
  { hanzi: '因而', pinyin: 'yīnér', meaning: '그러므로' },
  { hanzi: '因素', pinyin: 'yīnsù', meaning: '요소' },
  { hanzi: '银', pinyin: 'yín', meaning: '은' },
  { hanzi: '应付', pinyin: 'yìngfu', meaning: '대처하다, 대충 해치우다' },
  { hanzi: '应聘', pinyin: 'yìngpìn', meaning: '지원하다, 응빙하다' },
  { hanzi: '应用', pinyin: 'yìngyòng', meaning: '응용하다' },
  { hanzi: '英俊', pinyin: 'yīngjùn', meaning: '잘생기다' },
  { hanzi: '英雄', pinyin: 'yīngxióng', meaning: '영웅' },
  { hanzi: '迎接', pinyin: 'yíngjiē', meaning: '맞이하다' },
  { hanzi: '营养', pinyin: 'yíngyǎng', meaning: '영양' },
  { hanzi: '营业', pinyin: 'yíngyè', meaning: '영업하다' },
  { hanzi: '影子', pinyin: 'yǐngzi', meaning: '그림자' },
  { hanzi: '硬币', pinyin: 'yìngbì', meaning: '동전' },
  { hanzi: '硬件', pinyin: 'yìngjiàn', meaning: '하드웨어' },
  { hanzi: '拥抱', pinyin: 'yōngbào', meaning: '포옹하다' },
  { hanzi: '拥挤', pinyin: 'yōngjǐ', meaning: '붐비다, 혼잡하다' },
  { hanzi: '勇气', pinyin: 'yǒngqì', meaning: '용기' },
  { hanzi: '用途', pinyin: 'yòngtú', meaning: '용도' },
  { hanzi: '优惠', pinyin: 'yōuhuì', meaning: '특혜, 할인' },
  { hanzi: '优美', pinyin: 'yōuměi', meaning: '우아하고 아름답다' },
  { hanzi: '优势', pinyin: 'yōushì', meaning: '우세, 장점' },
  { hanzi: '悠久', pinyin: 'yōujiǔ', meaning: '유구하다' },
  { hanzi: '犹豫', pinyin: 'yóuyù', meaning: '망설이다' },
  { hanzi: '邮局', pinyin: 'yóujú', meaning: '우체국' },
  { hanzi: '油炸', pinyin: 'yóuzhá', meaning: '기름에 튀기다' },
  { hanzi: '游览', pinyin: 'yóulǎn', meaning: '유람하다, 관광하다' },
  { hanzi: '有利', pinyin: 'yǒulì', meaning: '유리하다' },
  { hanzi: '幼儿园', pinyin: 'yòuéryuán', meaning: '유치원' },
  { hanzi: '娱乐', pinyin: 'yúlè', meaning: '오락, 엔터테인먼트' },
  { hanzi: '与其', pinyin: 'yǔqí', meaning: '~하느니 (차라리)' },
  { hanzi: '宇宙', pinyin: 'yǔzhòu', meaning: '우주' },
  { hanzi: '语气', pinyin: 'yǔqì', meaning: '어투, 말투' },
  { hanzi: '玉米', pinyin: 'yùmǐ', meaning: '옥수수' },
  { hanzi: '预报', pinyin: 'yùbào', meaning: '예보' },
  { hanzi: '预订', pinyin: 'yùdìng', meaning: '예약하다' },
  { hanzi: '预防', pinyin: 'yùfáng', meaning: '예방하다' },
  { hanzi: '元旦', pinyin: 'Yuándàn', meaning: '양력 설날' },
  { hanzi: '原料', pinyin: 'yuánliào', meaning: '원료' },
  { hanzi: '原则', pinyin: 'yuánzé', meaning: '원칙' },
  { hanzi: '缘故', pinyin: 'yuángù', meaning: '연고, 까닭' },
  { hanzi: '愿望', pinyin: 'yuànwàng', meaning: '소망, 희망' },
  { hanzi: '晕', pinyin: 'yūn', meaning: '어지럽다' },
  { hanzi: '运气', pinyin: 'yùnqi', meaning: '운, 운수' },
  { hanzi: '运输', pinyin: 'yùnshū', meaning: '운송하다' },
  { hanzi: '运用', pinyin: 'yùnyòng', meaning: '운용하다, 활용하다' },
  { hanzi: '灾害', pinyin: 'zāihài', meaning: '재해' },
  { hanzi: '再三', pinyin: 'zàisān', meaning: '재삼, 거듭' },
  { hanzi: '赞成', pinyin: 'zànchéng', meaning: '찬성하다' },
  { hanzi: '赞美', pinyin: 'zànměi', meaning: '찬미하다' },
  { hanzi: '糟糕', pinyin: 'zāogāo', meaning: '엉망이다, 아뿔싸' },
  { hanzi: '造成', pinyin: 'zàochéng', meaning: '초래하다, 야기하다' },
  { hanzi: '则', pinyin: 'zé', meaning: '~하면 (곧), 규칙' },
  { hanzi: '责备', pinyin: 'zébèi', meaning: '책망하다' },
  { hanzi: '摘', pinyin: 'zhāi', meaning: '따다, 떼다' },
  { hanzi: '粘贴', pinyin: 'zhāntiē', meaning: '붙이다' },
  { hanzi: '展开', pinyin: 'zhǎnkāi', meaning: '펼치다, 전개하다' },
  { hanzi: '展览', pinyin: 'zhǎnlǎn', meaning: '전람하다, 전시' },
  { hanzi: '占线', pinyin: 'zhànxiàn', meaning: '통화 중이다' },
  { hanzi: '战争', pinyin: 'zhànzhēng', meaning: '전쟁' },
  { hanzi: '长途', pinyin: 'chángtú', meaning: '장거리' },
  { hanzi: '涨', pinyin: 'zhǎng', meaning: '(물가·수위가) 오르다' },
  { hanzi: '掌握', pinyin: 'zhǎngwò', meaning: '장악하다, 숙달하다' },
  { hanzi: '账户', pinyin: 'zhànghù', meaning: '계좌' },
  { hanzi: '招待', pinyin: 'zhāodài', meaning: '접대하다' },
  { hanzi: '召开', pinyin: 'zhàokāi', meaning: '(회의를) 열다' },
  { hanzi: '照常', pinyin: 'zhàocháng', meaning: '평소대로' },
  { hanzi: '哲学', pinyin: 'zhéxué', meaning: '철학' },
  { hanzi: '着凉', pinyin: 'zháoliáng', meaning: '감기에 걸리다' },
  { hanzi: '针对', pinyin: 'zhēnduì', meaning: '겨누다, 대상으로 하다' },
  { hanzi: '珍惜', pinyin: 'zhēnxī', meaning: '소중히 여기다' },
  { hanzi: '真理', pinyin: 'zhēnlǐ', meaning: '진리' },
  { hanzi: '真实', pinyin: 'zhēnshí', meaning: '진실하다' },
  { hanzi: '诊断', pinyin: 'zhěnduàn', meaning: '진단하다' },
  { hanzi: '枕头', pinyin: 'zhěntou', meaning: '베개' },
  { hanzi: '阵', pinyin: 'zhèn', meaning: '한바탕, 잠시' },
  { hanzi: '振动', pinyin: 'zhèndòng', meaning: '진동하다' },
  { hanzi: '争论', pinyin: 'zhēnglùn', meaning: '논쟁하다' },
  { hanzi: '争取', pinyin: 'zhēngqǔ', meaning: '쟁취하다' },
  { hanzi: '征求', pinyin: 'zhēngqiú', meaning: '구하다, 모집하다' },
  { hanzi: '挣钱', pinyin: 'zhèngqián', meaning: '돈을 벌다' },
  { hanzi: '睁', pinyin: 'zhēng', meaning: '(눈을) 뜨다' },
  { hanzi: '整个', pinyin: 'zhěnggè', meaning: '전체의, 온' },
  { hanzi: '整体', pinyin: 'zhěngtǐ', meaning: '전체' },
  { hanzi: '正', pinyin: 'zhèng', meaning: '바르다, 마침' },
  { hanzi: '证件', pinyin: 'zhèngjiàn', meaning: '증명서' },
  { hanzi: '证据', pinyin: 'zhèngjù', meaning: '증거' },
  { hanzi: '政策', pinyin: 'zhèngcè', meaning: '정책' },
  { hanzi: '政府', pinyin: 'zhèngfǔ', meaning: '정부' },
  { hanzi: '政治', pinyin: 'zhèngzhì', meaning: '정치' },
  { hanzi: '支', pinyin: 'zhī', meaning: '지탱하다, 자루 (가늘고 긴 것)' },
  { hanzi: '支票', pinyin: 'zhīpiào', meaning: '수표' },
  { hanzi: '执行', pinyin: 'zhíxíng', meaning: '집행하다' },
  { hanzi: '执照', pinyin: 'zhízhào', meaning: '면허증' },
  { hanzi: '直', pinyin: 'zhí', meaning: '곧다, 줄곧' },
  { hanzi: '指导', pinyin: 'zhǐdǎo', meaning: '지도하다' },
  { hanzi: '指挥', pinyin: 'zhǐhuī', meaning: '지휘하다' },
  { hanzi: '至今', pinyin: 'zhìjīn', meaning: '지금까지' },
  { hanzi: '至于', pinyin: 'zhìyú', meaning: '~에 관해서는' },
  { hanzi: '制定', pinyin: 'zhìdìng', meaning: '제정하다' },
  { hanzi: '制度', pinyin: 'zhìdù', meaning: '제도' },
  { hanzi: '制作', pinyin: 'zhìzuò', meaning: '제작하다' },
  { hanzi: '治疗', pinyin: 'zhìliáo', meaning: '치료하다' },
  { hanzi: '秩序', pinyin: 'zhìxù', meaning: '질서' },
  { hanzi: '智慧', pinyin: 'zhìhuì', meaning: '지혜' },
  { hanzi: '中介', pinyin: 'zhōngjiè', meaning: '중개' },
  { hanzi: '中心', pinyin: 'zhōngxīn', meaning: '중심' },
  { hanzi: '中旬', pinyin: 'zhōngxún', meaning: '중순' },
  { hanzi: '钟', pinyin: 'zhōng', meaning: '시계, 종' },
  { hanzi: '重', pinyin: 'zhòng', meaning: '무겁다' },
  { hanzi: '重复', pinyin: 'chóngfù', meaning: '중복하다, 반복하다' },
  { hanzi: '重量', pinyin: 'zhòngliàng', meaning: '중량' },
  { hanzi: '周到', pinyin: 'zhōudào', meaning: '세심하다, 빈틈없다' },
  { hanzi: '竹子', pinyin: 'zhúzi', meaning: '대나무' },
  { hanzi: '逐步', pinyin: 'zhúbù', meaning: '점차' },
  { hanzi: '主持', pinyin: 'zhǔchí', meaning: '주관하다, 사회를 보다' },
  { hanzi: '主观', pinyin: 'zhǔguān', meaning: '주관적이다' },
  { hanzi: '主人', pinyin: 'zhǔrén', meaning: '주인' },
  { hanzi: '主席', pinyin: 'zhǔxí', meaning: '주석, 의장' },
  { hanzi: '主张', pinyin: 'zhǔzhāng', meaning: '주장하다' },
  { hanzi: '煮', pinyin: 'zhǔ', meaning: '삶다, 끓이다' },
  { hanzi: '嘱咐', pinyin: 'zhǔfù', meaning: '분부하다, 당부하다' },
  { hanzi: '注册', pinyin: 'zhùcè', meaning: '등록하다' },
  { hanzi: '祝福', pinyin: 'zhùfú', meaning: '축복하다' },
  { hanzi: '抓紧', pinyin: 'zhuājǐn', meaning: '꽉 쥐다, 서두르다' },
  { hanzi: '专家', pinyin: 'zhuānjiā', meaning: '전문가' },
  { hanzi: '专心', pinyin: 'zhuānxīn', meaning: '전념하다' },
  { hanzi: '转变', pinyin: 'zhuǎnbiàn', meaning: '바뀌다, 전환하다' },
  { hanzi: '转告', pinyin: 'zhuǎngào', meaning: '전달하다' },
  { hanzi: '装', pinyin: 'zhuāng', meaning: '싣다, 설치하다, ~인 척하다' },
  { hanzi: '装饰', pinyin: 'zhuāngshì', meaning: '장식하다' },
  { hanzi: '状况', pinyin: 'zhuàngkuàng', meaning: '상황' },
  { hanzi: '状态', pinyin: 'zhuàngtài', meaning: '상태' },
  { hanzi: '追求', pinyin: 'zhuīqiú', meaning: '추구하다' },
  { hanzi: '咨询', pinyin: 'zīxún', meaning: '자문하다, 상담하다' },
  { hanzi: '姿势', pinyin: 'zīshì', meaning: '자세' },
  { hanzi: '资格', pinyin: 'zīgé', meaning: '자격' },
  { hanzi: '资金', pinyin: 'zījīn', meaning: '자금' },
  { hanzi: '资料', pinyin: 'zīliào', meaning: '자료' },
  { hanzi: '资源', pinyin: 'zīyuán', meaning: '자원' },
  { hanzi: '紫', pinyin: 'zǐ', meaning: '자주색, 보라색' },
  { hanzi: '字幕', pinyin: 'zìmù', meaning: '자막' },
  { hanzi: '自从', pinyin: 'zìcóng', meaning: '~부터, ~이래' },
  { hanzi: '自动', pinyin: 'zìdòng', meaning: '자동' },
  { hanzi: '自豪', pinyin: 'zìháo', meaning: '자랑스럽다' },
  { hanzi: '自觉', pinyin: 'zìjué', meaning: '자각하다, 자발적이다' },
  { hanzi: '自私', pinyin: 'zìsī', meaning: '이기적이다' },
  { hanzi: '自信', pinyin: 'zìxìn', meaning: '자신감 있다' },
  { hanzi: '自由', pinyin: 'zìyóu', meaning: '자유' },
  { hanzi: '自愿', pinyin: 'zìyuàn', meaning: '자원하다' },
  { hanzi: '宗教', pinyin: 'zōngjiào', meaning: '종교' },
  { hanzi: '综合', pinyin: 'zōnghé', meaning: '종합하다' },
  { hanzi: '总裁', pinyin: 'zǒngcái', meaning: '총재' },
  { hanzi: '总共', pinyin: 'zǒnggòng', meaning: '모두, 합계' },
  { hanzi: '总理', pinyin: 'zǒnglǐ', meaning: '총리' },
  { hanzi: '总算', pinyin: 'zǒngsuàn', meaning: '마침내, 겨우' },
  { hanzi: '总统', pinyin: 'zǒngtǒng', meaning: '대통령' },
  { hanzi: '总之', pinyin: 'zǒngzhī', meaning: '요컨대' },
  { hanzi: '阻止', pinyin: 'zǔzhǐ', meaning: '저지하다' },
  { hanzi: '组合', pinyin: 'zǔhé', meaning: '조합하다' },
  { hanzi: '祖国', pinyin: 'zǔguó', meaning: '조국' },
  { hanzi: '祖先', pinyin: 'zǔxiān', meaning: '선조, 조상' },
  { hanzi: '最初', pinyin: 'zuìchū', meaning: '최초' },
  { hanzi: '罪犯', pinyin: 'zuìfàn', meaning: '범인, 죄인' },
  { hanzi: '醉', pinyin: 'zuì', meaning: '취하다' },
  { hanzi: '尊敬', pinyin: 'zūnjìng', meaning: '존경하다' },
  { hanzi: '遵守', pinyin: 'zūnshǒu', meaning: '준수하다' },
  { hanzi: '作品', pinyin: 'zuòpǐn', meaning: '작품' },
  { hanzi: '作为', pinyin: 'zuòwéi', meaning: '~으로서, 행위' },
  { hanzi: '作文', pinyin: 'zuòwén', meaning: '작문' },
];
