const hsk3Words = [
  { hanzi: "阿姨", pinyin: "āyí", meaning: "아주머니, 이모" },
  { hanzi: "啊", pinyin: "a", meaning: "아 (감탄사)" },
  { hanzi: "矮", pinyin: "ǎi", meaning: "작다, 낮다" },
  { hanzi: "爱好", pinyin: "àihào", meaning: "취미" },
  { hanzi: "安静", pinyin: "ānjìng", meaning: "조용하다" },
  { hanzi: "把", pinyin: "bǎ", meaning: "~을/를 (처치문)" },
  { hanzi: "班", pinyin: "bān", meaning: "반, 학급" },
  { hanzi: "搬", pinyin: "bān", meaning: "이사하다, 옮기다" },
  { hanzi: "办法", pinyin: "bànfǎ", meaning: "방법" },
  { hanzi: "办公室", pinyin: "bàngōngshì", meaning: "사무실" },
  { hanzi: "半", pinyin: "bàn", meaning: "반 (절반)" },
  { hanzi: "帮忙", pinyin: "bāngmáng", meaning: "돕다" },
  { hanzi: "包", pinyin: "bāo", meaning: "가방, 싸다" },
  { hanzi: "饱", pinyin: "bǎo", meaning: "배부르다" },
  { hanzi: "北方", pinyin: "běifāng", meaning: "북방, 북쪽" },
  { hanzi: "被", pinyin: "bèi", meaning: "~에게 ~당하다" },
  { hanzi: "鼻子", pinyin: "bízi", meaning: "코" },
  { hanzi: "比较", pinyin: "bǐjiào", meaning: "비교적, 비교하다" },
  { hanzi: "比赛", pinyin: "bǐsài", meaning: "시합, 경기" },
  { hanzi: "笔记本", pinyin: "bǐjìběn", meaning: "노트북, 공책" },
  { hanzi: "必须", pinyin: "bìxū", meaning: "반드시 ~해야 한다" },
  { hanzi: "变化", pinyin: "biànhuà", meaning: "변화하다" },
  { hanzi: "别人", pinyin: "biérén", meaning: "다른 사람" },
  { hanzi: "冰箱", pinyin: "bīngxiāng", meaning: "냉장고" },
  { hanzi: "不但", pinyin: "búdàn", meaning: "~뿐만 아니라" },
  { hanzi: "而且", pinyin: "érqiě", meaning: "게다가" },
  { hanzi: "菜单", pinyin: "càidān", meaning: "메뉴판" },
  { hanzi: "参加", pinyin: "cānjiā", meaning: "참가하다" },
  { hanzi: "草", pinyin: "cǎo", meaning: "풀" },
  { hanzi: "层", pinyin: "céng", meaning: "층" },
  { hanzi: "差", pinyin: "chà", meaning: "부족하다, 차이가 나다" },
  { hanzi: "长", pinyin: "zhǎng", meaning: "자라다, 생기다" },
  { hanzi: "超市", pinyin: "chāoshì", meaning: "슈퍼마켓" },
  { hanzi: "衬衫", pinyin: "chènshān", meaning: "셔츠" },
  { hanzi: "成绩", pinyin: "chéngjì", meaning: "성적" },
  { hanzi: "城市", pinyin: "chéngshì", meaning: "도시" },
  { hanzi: "迟到", pinyin: "chídào", meaning: "지각하다" },
  { hanzi: "出现", pinyin: "chūxiàn", meaning: "출현하다, 나타나다" },
  { hanzi: "除了", pinyin: "chúle", meaning: "~을 제외하고" },
  { hanzi: "船", pinyin: "chuán", meaning: "배 (선박)" },
  { hanzi: "春", pinyin: "chūn", meaning: "봄" },
  { hanzi: "词典", pinyin: "cídiǎn", meaning: "사전" },
  { hanzi: "聪明", pinyin: "cōngming", meaning: "똑똑하다" },
  { hanzi: "打扫", pinyin: "dǎsǎo", meaning: "청소하다" },
  { hanzi: "打算", pinyin: "dǎsuàn", meaning: "계획, ~할 작정이다" },
  { hanzi: "带", pinyin: "dài", meaning: "지니다, 데리고 가다" },
  { hanzi: "担心", pinyin: "dānxīn", meaning: "걱정하다" },
  { hanzi: "蛋糕", pinyin: "dàngāo", meaning: "케이크" },
  { hanzi: "当然", pinyin: "dāngrán", meaning: "당연히" },
  { hanzi: "地", pinyin: "de", meaning: "하게 (부사어 형태를 만드는 조사)" },
  { hanzi: "灯", pinyin: "dēng", meaning: "등, 램프" },
  { hanzi: "地方", pinyin: "dìfang", meaning: "장소, 곳" },
  { hanzi: "地铁", pinyin: "dìtiě", meaning: "지하철" },
  { hanzi: "地图", pinyin: "dìtú", meaning: "지도" },
  { hanzi: "电梯", pinyin: "diàntī", meaning: "엘리베이터" },
  { hanzi: "电子邮件", pinyin: "diànzǐ yóujiàn", meaning: "이메일" },
  { hanzi: "东", pinyin: "dōng", meaning: "동쪽" },
  { hanzi: "冬", pinyin: "dōng", meaning: "겨울" },
  { hanzi: "动物园", pinyin: "dòngwùyuán", meaning: "동물원" },
  { hanzi: "短", pinyin: "duǎn", meaning: "짧다" },
  { hanzi: "段", pinyin: "duàn", meaning: "단락, 구간" },
  { hanzi: "锻炼", pinyin: "duànliàn", meaning: "단련하다, 운동하다" },
  { hanzi: "多么", pinyin: "duōme", meaning: "얼마나" },
  { hanzi: "饿", pinyin: "è", meaning: "배고프다" },
  { hanzi: "耳朵", pinyin: "ěrduo", meaning: "귀" },
  { hanzi: "发烧", pinyin: "fāshāo", meaning: "열이 나다" },
  { hanzi: "发现", pinyin: "fāxiàn", meaning: "발견하다" },
  { hanzi: "方便", pinyin: "fāngbiàn", meaning: "편리하다" },
  { hanzi: "放", pinyin: "fàng", meaning: "놓다, 두다" },
  { hanzi: "放心", pinyin: "fàngxīn", meaning: "안심하다" },
  { hanzi: "分", pinyin: "fēn", meaning: "나누다, 분 (돈)" },
  { hanzi: "复习", pinyin: "fùxí", meaning: "복습하다" },
  { hanzi: "附近", pinyin: "fùjìn", meaning: "근처, 부근" },
  { hanzi: "干净", pinyin: "gānjìng", meaning: "깨끗하다" },
  { hanzi: "敢", pinyin: "gǎn", meaning: "감히 ~하다" },
  { hanzi: "感冒", pinyin: "gǎnmào", meaning: "감기에 걸리다" },
  { hanzi: "刚才", pinyin: "gāngcái", meaning: "방금, 막" },
  { hanzi: "跟", pinyin: "gēn", meaning: "~와, 따라가다" },
  { hanzi: "根据", pinyin: "gēnjù", meaning: "근거하여" },
  { hanzi: "更", pinyin: "gèng", meaning: "더욱" },
  { hanzi: "故事", pinyin: "gùshi", meaning: "이야기" },
  { hanzi: "刮风", pinyin: "guāfēng", meaning: "바람이 불다" },
  { hanzi: "关", pinyin: "guān", meaning: "닫다, 끄다" },
  { hanzi: "关系", pinyin: "guānxi", meaning: "관계" },
  { hanzi: "关心", pinyin: "guānxīn", meaning: "관심을 갖다" },
  { hanzi: "关于", pinyin: "guānyú", meaning: "~에 관하여" },
  { hanzi: "国家", pinyin: "guójiā", meaning: "국가" },
  { hanzi: "果汁", pinyin: "guǒzhī", meaning: "과일 주스" },
  { hanzi: "过去", pinyin: "guòqù", meaning: "과거" },
  { hanzi: "还是", pinyin: "háishì", meaning: "여전히, A 아니면 B" },
  { hanzi: "害怕", pinyin: "hàipà", meaning: "무서워하다" },
  { hanzi: "航班", pinyin: "hángbān", meaning: "항공편" },
  { hanzi: "黑板", pinyin: "hēibǎn", meaning: "칠판" },
  { hanzi: "后来", pinyin: "hòulái", meaning: "그 후, 나중에" },
  { hanzi: "护照", pinyin: "hùzhào", meaning: "여권" },
  { hanzi: "花", pinyin: "huā", meaning: "꽃, (돈/시간을) 쓰다" },
  { hanzi: "画", pinyin: "huà", meaning: "그리다, 그림" },
  { hanzi: "坏", pinyin: "huài", meaning: "나쁘다, 고장나다" },
  { hanzi: "环境", pinyin: "huánjìng", meaning: "환경" },
  { hanzi: "换", pinyin: "huàn", meaning: "바꾸다" },
  { hanzi: "黄", pinyin: "huáng", meaning: "노랗다" },
  { hanzi: "会议", pinyin: "huìyì", meaning: "회의" },
  { hanzi: "或者", pinyin: "huòzhě", meaning: "혹은" },
  { hanzi: "几乎", pinyin: "jīhū", meaning: "거의" },
  { hanzi: "机会", pinyin: "jīhuì", meaning: "기회" },
  { hanzi: "极", pinyin: "jí", meaning: "극도로, 매우" },
  { hanzi: "记得", pinyin: "jìde", meaning: "기억하다" },
  { hanzi: "季节", pinyin: "jìjié", meaning: "계절" },
  { hanzi: "检查", pinyin: "jiǎnchá", meaning: "검사하다" },
  { hanzi: "简单", pinyin: "jiǎndān", meaning: "간단하다" },
  { hanzi: "健康", pinyin: "jiànkāng", meaning: "건강" },
  { hanzi: "见面", pinyin: "jiànmiàn", meaning: "만나다" },
  { hanzi: "讲", pinyin: "jiǎng", meaning: "말하다, 강연하다" },
  { hanzi: "教", pinyin: "jiāo", meaning: "가르치다" },
  { hanzi: "脚", pinyin: "jiǎo", meaning: "발" },
  { hanzi: "角", pinyin: "jiǎo", meaning: "지아오 (돈 단위)" },
  { hanzi: "接", pinyin: "jiē", meaning: "받다, 마중하다" },
  { hanzi: "街道", pinyin: "jiēdào", meaning: "거리" },
  { hanzi: "节目", pinyin: "jiémù", meaning: "프로그램" },
  { hanzi: "节日", pinyin: "jiérì", meaning: "명절" },
  { hanzi: "结婚", pinyin: "jiéhūn", meaning: "결혼하다" },
  { hanzi: "结束", pinyin: "jiéshù", meaning: "끝나다" },
  { hanzi: "解决", pinyin: "jiějué", meaning: "해결하다" },
  { hanzi: "借", pinyin: "jiè", meaning: "빌리다" },
  { hanzi: "经常", pinyin: "jīngcháng", meaning: "자주" },
  { hanzi: "经过", pinyin: "jīngguò", meaning: "거치다, 지나가다" },
  { hanzi: "经理", pinyin: "jīnglǐ", meaning: "매니저, 사장" },
  { hanzi: "久", pinyin: "jiǔ", meaning: "오래다" },
  { hanzi: "旧", pinyin: "jiù", meaning: "낡다" },
  { hanzi: "句子", pinyin: "jùzi", meaning: "문장" },
  { hanzi: "决定", pinyin: "juédìng", meaning: "결정하다" },
  { hanzi: "可爱", pinyin: "kě'ài", meaning: "귀엽다" },
  { hanzi: "渴", pinyin: "kě", meaning: "목마르다" },
  { hanzi: "刻", pinyin: "kè", meaning: "15분" },
  { hanzi: "客人", pinyin: "kèrén", meaning: "손님" },
  { hanzi: "空调", pinyin: "kōngtiáo", meaning: "에어컨" },
  { hanzi: "口", pinyin: "kǒu", meaning: "입, 식구" },
  { hanzi: "哭", pinyin: "kū", meaning: "울다" },
  { hanzi: "裤子", pinyin: "kùzi", meaning: "바지" },
  { hanzi: "筷子", pinyin: "kuàizi", meaning: "젓가락" },
  { hanzi: "蓝", pinyin: "lán", meaning: "파랗다" },
  { hanzi: "老", pinyin: "lǎo", meaning: "늙다, 오래되다" },
  { hanzi: "离开", pinyin: "líkāi", meaning: "떠나다" },
  { hanzi: "礼物", pinyin: "lǐwù", meaning: "선물" },
  { hanzi: "历史", pinyin: "lìshǐ", meaning: "역사" },
  { hanzi: "脸", pinyin: "liǎn", meaning: "얼굴" },
  { hanzi: "练习", pinyin: "liànxí", meaning: "연습하다" },
  { hanzi: "辆", pinyin: "liàng", meaning: "대 (차량 양사)" },
  { hanzi: "聊天", pinyin: "liáotiān", meaning: "채팅하다, 잡담하다" },
  { hanzi: "了解", pinyin: "liǎojiě", meaning: "이해하다, 알아보다" },
  { hanzi: "邻居", pinyin: "línjū", meaning: "이웃" },
  { hanzi: "留学", pinyin: "liúxué", meaning: "유학하다" },
  { hanzi: "楼", pinyin: "lóu", meaning: "건물, 층" },
  { hanzi: "绿", pinyin: "lǜ", meaning: "초록색" },
  { hanzi: "马", pinyin: "mǎ", meaning: "말 (동물)" },
  { hanzi: "马上", pinyin: "mǎshàng", meaning: "곧, 즉시" },
  { hanzi: "满意", pinyin: "mǎnyì", meaning: "만족하다" },
  { hanzi: "帽子", pinyin: "màozi", meaning: "모자" },
  { hanzi: "米", pinyin: "mǐ", meaning: "미터" },
  { hanzi: "面包", pinyin: "miànbāo", meaning: "빵" },
  { hanzi: "明白", pinyin: "míngbai", meaning: "이해하다, 명백하다" },
  { hanzi: "拿", pinyin: "ná", meaning: "들다, 잡다" },
  { hanzi: "奶奶", pinyin: "nǎinai", meaning: "할머니" },
  { hanzi: "南", pinyin: "nán", meaning: "남쪽" },
  { hanzi: "难", pinyin: "nán", meaning: "어렵다" },
  { hanzi: "难过", pinyin: "nánguò", meaning: "슬프다" },
  { hanzi: "年级", pinyin: "niánjí", meaning: "학년" },
  { hanzi: "年轻", pinyin: "niánqīng", meaning: "젊다" },
  { hanzi: "鸟", pinyin: "niǎo", meaning: "새" },
  { hanzi: "努力", pinyin: "nǔlì", meaning: "노력하다" },
  { hanzi: "爬山", pinyin: "páshān", meaning: "등산하다" },
  { hanzi: "盘子", pinyin: "pánzi", meaning: "접시" },
  { hanzi: "胖", pinyin: "pàng", meaning: "뚱뚱하다" },
  { hanzi: "皮鞋", pinyin: "píxié", meaning: "구두" },
  { hanzi: "啤酒", pinyin: "píjiǔ", meaning: "맥주" },
  { hanzi: "普通话", pinyin: "pǔtōnghuà", meaning: "표준어" },
  { hanzi: "其实", pinyin: "qíshí", meaning: "사실은" },
  { hanzi: "其他", pinyin: "qítā", meaning: "기타, 다른" },
  { hanzi: "奇怪", pinyin: "qíguài", meaning: "이상하다" },
  { hanzi: "骑", pinyin: "qí", meaning: "타다 (자전거, 말)" },
  { hanzi: "起飞", pinyin: "qǐfēi", meaning: "이륙하다" },
  { hanzi: "清楚", pinyin: "qīngchu", meaning: "분명하다" },
  { hanzi: "秋", pinyin: "qiū", meaning: "가을" },
  { hanzi: "裙子", pinyin: "qúnzi", meaning: "치마" },
  { hanzi: "然后", pinyin: "ránhòu", meaning: "연후에, 그리고 나서" },
  { hanzi: "热情", pinyin: "rèqíng", meaning: "열정적이다" },
  { hanzi: "认为", pinyin: "rènwéi", meaning: "생각하다, 여기다" },
  { hanzi: "认真", pinyin: "rènzhēn", meaning: "진지하다" },
  { hanzi: "容易", pinyin: "róngyì", meaning: "쉽다" },
  { hanzi: "如果", pinyin: "rúguǒ", meaning: "만약" },
  { hanzi: "伞", pinyin: "sǎn", meaning: "우산" },
  { hanzi: "上网", pinyin: "shàngwǎng", meaning: "인터넷을 하다" },
  { hanzi: "生气", pinyin: "shēngqì", meaning: "화내다" },
  { hanzi: "声音", pinyin: "shēngyīn", meaning: "소리" },
  { hanzi: "世界", pinyin: "shìjiè", meaning: "세계" },
  { hanzi: "试", pinyin: "shì", meaning: "시험해 보다, 시도하다" },
  { hanzi: "瘦", pinyin: "shòu", meaning: "마르다" },
  { hanzi: "叔叔", pinyin: "shūshu", meaning: "삼촌, 아저씨" },
  { hanzi: "舒服", pinyin: "shūfu", meaning: "편안하다" },
  { hanzi: "树", pinyin: "shù", meaning: "나무" },
  { hanzi: "数学", pinyin: "shùxué", meaning: "수학" },
  { hanzi: "刷牙", pinyin: "shuāyá", meaning: "양치질하다" },
  { hanzi: "双", pinyin: "shuāng", meaning: "쌍, 켤레" },
  { hanzi: "水平", pinyin: "shuǐpíng", meaning: "수준" },
  { hanzi: "司机", pinyin: "sījī", meaning: "기사" },
  { hanzi: "太阳", pinyin: "tàiyáng", meaning: "태양" },
  { hanzi: "特别", pinyin: "tèbié", meaning: "특별하다" },
  { hanzi: "疼", pinyin: "téng", meaning: "아프다" },
  { hanzi: "提高", pinyin: "tígāo", meaning: "향상시키다" },
  { hanzi: "体育", pinyin: "tǐyù", meaning: "체육" },
  { hanzi: "甜", pinyin: "tián", meaning: "달다" },
  { hanzi: "条", pinyin: "tiáo", meaning: "조 (길고 가느다란 것을 세는 양사)" },
  { hanzi: "同事", pinyin: "tóngshì", meaning: "동료" },
  { hanzi: "同意", pinyin: "tóngyì", meaning: "동의하다" },
  { hanzi: "头发", pinyin: "tóufa", meaning: "머리카락" },
  { hanzi: "突然", pinyin: "tūrán", meaning: "갑자기" },
  { hanzi: "图书馆", pinyin: "túshūguǎn", meaning: "도서관" },
  { hanzi: "腿", pinyin: "tuǐ", meaning: "다리" },
  { hanzi: "完成", pinyin: "wánchéng", meaning: "완성하다" },
  { hanzi: "碗", pinyin: "wǎn", meaning: "그릇" },
  { hanzi: "万", pinyin: "wàn", meaning: "만" },
  { hanzi: "忘记", pinyin: "wàngjì", meaning: "잊다" },
  { hanzi: "为", pinyin: "wèi", meaning: "~을 위하여" },
  { hanzi: "为了", pinyin: "wèile", meaning: "~하기 위하여" },
  { hanzi: "位", pinyin: "wèi", meaning: "분 (사람을 높여 부르는 양사)" },
  { hanzi: "文化", pinyin: "wénhuà", meaning: "문화" },
  { hanzi: "西", pinyin: "xī", meaning: "서쪽" },
  { hanzi: "习惯", pinyin: "xíguàn", meaning: "습관" },
  { hanzi: "洗手间", pinyin: "xǐshǒujiān", meaning: "화장실" },
  { hanzi: "洗澡", pinyin: "xǐzǎo", meaning: "목욕하다" },
  { hanzi: "夏", pinyin: "xià", meaning: "여름" },
  { hanzi: "先", pinyin: "xiān", meaning: "먼저" },
  { hanzi: "相信", pinyin: "xiāngxìn", meaning: "믿다" },
  { hanzi: "香蕉", pinyin: "xiāngjiāo", meaning: "바나나" },
  { hanzi: "向", pinyin: "xiàng", meaning: "~을 향하여" },
  { hanzi: "像", pinyin: "xiàng", meaning: "닮다" },
  { hanzi: "小心", pinyin: "xiǎoxīn", meaning: "조심하다" },
  { hanzi: "校长", pinyin: "xiàozhǎng", meaning: "교장" },
  { hanzi: "新闻", pinyin: "xīnwén", meaning: "뉴스" },
  { hanzi: "新鲜", pinyin: "xīnxiān", meaning: "신선하다" },
  { hanzi: "信用卡", pinyin: "xìnyòngkǎ", meaning: "신용카드" },
  { hanzi: "行李箱", pinyin: "xínglǐxiāng", meaning: "여행 가방" },
  { hanzi: "熊猫", pinyin: "xióngmāo", meaning: "판다" },
  { hanzi: "需要", pinyin: "xūyào", meaning: "필요하다" },
  { hanzi: "选择", pinyin: "xuǎnzé", meaning: "선택하다" },
  { hanzi: "要求", pinyin: "yāoqiú", meaning: "요구하다" },
  { hanzi: "爷爷", pinyin: "yéye", meaning: "할아버지" },
  { hanzi: "一定", pinyin: "yídìng", meaning: "반드시" },
  { hanzi: "一共", pinyin: "yígòng", meaning: "모두 합해서" },
  { hanzi: "一会儿", pinyin: "yíhuìr", meaning: "잠시" },
  { hanzi: "一样", pinyin: "yíyàng", meaning: "같다" },
  { hanzi: "一般", pinyin: "yìbān", meaning: "보통, 일반적이다" },
  { hanzi: "一边", pinyin: "yìbiān", meaning: "한편으로" },
  { hanzi: "一直", pinyin: "yìzhí", meaning: "줄곧" },
  { hanzi: "以前", pinyin: "yǐqián", meaning: "이전" },
  { hanzi: "音乐", pinyin: "yīnyuè", meaning: "음악" },
  { hanzi: "银行", pinyin: "yínháng", meaning: "은행" },
  { hanzi: "饮料", pinyin: "yǐnliào", meaning: "음료수" },
  { hanzi: "应该", pinyin: "yīnggāi", meaning: "마땅히 ~해야 한다" },
  { hanzi: "影响", pinyin: "yǐngxiǎng", meaning: "영향" },
  { hanzi: "用", pinyin: "yòng", meaning: "사용하다" },
  { hanzi: "游戏", pinyin: "yóuxì", meaning: "게임" },
  { hanzi: "有名", pinyin: "yǒumíng", meaning: "유명하다" },
  { hanzi: "又", pinyin: "yòu", meaning: "또" },
  { hanzi: "遇到", pinyin: "yùdào", meaning: "만나다, 마주치다" },
  { hanzi: "元", pinyin: "yuán", meaning: "원 (돈 단위)" },
  { hanzi: "愿意", pinyin: "yuànyì", meaning: "원하다, 기꺼이 ~하다" },
  { hanzi: "月亮", pinyin: "yuèliang", meaning: "달" },
  { hanzi: "越", pinyin: "yuè", meaning: "점점" },
  { hanzi: "站", pinyin: "zhàn", meaning: "서다, 역" },
  { hanzi: "张", pinyin: "zhāng", meaning: "장 (종이를 세는 양사)" },
  { hanzi: "照顾", pinyin: "zhàogù", meaning: "돌보다" },
  { hanzi: "照片", pinyin: "zhàopiàn", meaning: "사진" },
  { hanzi: "照相机", pinyin: "zhàoxiàngjī", meaning: "카메라" },
  { hanzi: "只", pinyin: "zhǐ", meaning: "단지, 오직" },
  { hanzi: "中间", pinyin: "zhōngjiān", meaning: "중간" },
  { hanzi: "中文", pinyin: "Zhōngwén", meaning: "중국어" },
  { hanzi: "终于", pinyin: "zhōngyú", meaning: "마침내" },
  { hanzi: "种", pinyin: "zhǒng", meaning: "종류" },
  { hanzi: "重要", pinyin: "zhòngyào", meaning: "중요하다" },
  { hanzi: "周末", pinyin: "zhōumò", meaning: "주말" },
  { hanzi: "主要", pinyin: "zhǔyào", meaning: "주요하다" },
  { hanzi: "注意", pinyin: "zhùyì", meaning: "주의하다" },
  { hanzi: "着急", pinyin: "zháojí", meaning: "조급하다" },
  { hanzi: "自己", pinyin: "zìjǐ", meaning: "자기, 자신" },
  { hanzi: "总是", pinyin: "zǒngshì", meaning: "늘, 항상" },
  { hanzi: "嘴", pinyin: "zuǐ", meaning: "입" },
  { hanzi: "最后", pinyin: "zuìhòu", meaning: "최후, 마지막" },
  { hanzi: "最近", pinyin: "zuìjìn", meaning: "최근" },
  { hanzi: "作业", pinyin: "zuòyè", meaning: "숙제" }
];
