const hsk6Words = [
  { hanzi: '哎哟', pinyin: 'āiyō', meaning: '아이고 (감탄사)' },
  { hanzi: '挨', pinyin: 'ái', meaning: '견디다, 당하다' },
  { hanzi: '癌症', pinyin: 'áizhèng', meaning: '암 (질병)' },
  { hanzi: '爱不释手', pinyin: 'àibúshìshǒu', meaning: '너무 좋아서 손에서 놓지 못하다' },
  { hanzi: '爱戴', pinyin: 'àidài', meaning: '추앙하다, 존경하고 사랑하다' },
  { hanzi: '暧昧', pinyin: 'àimèi', meaning: '애매하다, 모호하다' },
  { hanzi: '安宁', pinyin: 'ānníng', meaning: '안녕, 평온하다' },
  { hanzi: '安详', pinyin: 'ānxiáng', meaning: '차분하다, 평온하다' },
  { hanzi: '安置', pinyin: 'ānzhì', meaning: '안치하다, 배치하다' },
  { hanzi: '按摩', pinyin: 'ànmó', meaning: '안마하다' },
  { hanzi: '案件', pinyin: 'ànjiàn', meaning: '안건, 사건' },
  { hanzi: '案例', pinyin: 'ànlì', meaning: '사례, 판례' },
  { hanzi: '暗示', pinyin: 'ànshì', meaning: '암시하다' },
  { hanzi: '昂贵', pinyin: 'ángguì', meaning: '비싸다, 값비싸다' },
  { hanzi: '凹凸', pinyin: 'āotū', meaning: '요철, 울퉁불퉁하다' },
  { hanzi: '熬', pinyin: 'áo', meaning: '오래 끓이다, 참고 견디다' },
  { hanzi: '奥秘', pinyin: 'àomì', meaning: '오비, 비밀' },
  { hanzi: '巴不得', pinyin: 'bābùdé', meaning: '간절히 바라다' },
  { hanzi: '巴结', pinyin: 'bājié', meaning: '아첨하다, 비위를 맞추다' },
  { hanzi: '扒', pinyin: 'bā', meaning: '긁다, 파헤치다' },
  { hanzi: '疤', pinyin: 'bā', meaning: '흉터' },
  { hanzi: '拔苗助长', pinyin: 'bámiáozhùzhǎng', meaning: '조급하게 굴어 오히려 일을 망치다 (발묘조장)' },
  { hanzi: '把关', pinyin: 'bǎguān', meaning: '관문을 지키다, 심사하다' },
  { hanzi: '把手', pinyin: 'bǎshou', meaning: '손잡이' },
  { hanzi: '霸道', pinyin: 'bàdào', meaning: '패도, 횡포하다' },
  { hanzi: '罢工', pinyin: 'bàgōng', meaning: '파업하다' },
  { hanzi: '掰', pinyin: 'bāi', meaning: '쪼개다, 꺾어 떼다' },
  { hanzi: '百分点', pinyin: 'bǎifēndiǎn', meaning: '퍼센트 포인트' },
  { hanzi: '摆脱', pinyin: 'bǎituō', meaning: '벗어나다, 빠져나오다' },
  { hanzi: '拜访', pinyin: 'bàifǎng', meaning: '방문하다' },
  { hanzi: '拜年', pinyin: 'bàinián', meaning: '새해 인사를 하다' },
  { hanzi: '拜托', pinyin: 'bàituō', meaning: '부탁하다' },
  { hanzi: '败坏', pinyin: 'bàihuài', meaning: '망치다, 훼손하다' },
  { hanzi: '颁布', pinyin: 'bānbù', meaning: '반포하다, 공포하다' },
  { hanzi: '颁发', pinyin: 'bānfā', meaning: '수여하다, 발급하다' },
  { hanzi: '斑', pinyin: 'bān', meaning: '반점, 얼룩' },
  { hanzi: '版本', pinyin: 'bǎnběn', meaning: '판본, 버전' },
  { hanzi: '半途而废', pinyin: 'bàntú\'érfèi', meaning: '중도에 그만두다 (반도이폐)' },
  { hanzi: '扮演', pinyin: 'bànyǎn', meaning: '역할을 맡다' },
  { hanzi: '伴随', pinyin: 'bànsuí', meaning: '수반하다, 동반하다' },
  { hanzi: '伴侣', pinyin: 'bànlǚ', meaning: '반려자' },
  { hanzi: '绑架', pinyin: 'bǎngjià', meaning: '납치하다' },
  { hanzi: '榜样', pinyin: 'bǎngyàng', meaning: '모범, 본보기' },
  { hanzi: '磅', pinyin: 'bàng', meaning: '파운드 (무게 단위)' },
  { hanzi: '包庇', pinyin: 'bāobì', meaning: '감싸다, 비호하다' },
  { hanzi: '包袱', pinyin: 'bāofu', meaning: '보따리, 마음의 짐' },
  { hanzi: '包围', pinyin: 'bāowéi', meaning: '포위하다' },
  { hanzi: '包装', pinyin: 'bāozhuāng', meaning: '포장하다' },
  { hanzi: '饱和', pinyin: 'bǎohé', meaning: '포화 상태' },
  { hanzi: '饱经沧桑', pinyin: 'bǎojīngcāngsāng', meaning: '세상 풍파를 다 겪다' },
  { hanzi: '保管', pinyin: 'bǎoguǎn', meaning: '보관하다' },
  { hanzi: '保密', pinyin: 'bǎomì', meaning: '비밀을 유지하다' },
  { hanzi: '保姆', pinyin: 'bǎomǔ', meaning: '보모' },
  { hanzi: '保守', pinyin: 'bǎoshǒu', meaning: '보수적이다' },
  { hanzi: '保卫', pinyin: 'bǎowèi', meaning: '보위하다, 지키다' },
  { hanzi: '保养', pinyin: 'bǎoyǎng', meaning: '보양하다, 관리하다' },
  { hanzi: '保障', pinyin: 'bǎozhàng', meaning: '보장하다' },
  { hanzi: '保重', pinyin: 'bǎozhòng', meaning: '몸조심하다' },
  { hanzi: '抱负', pinyin: 'bàofù', meaning: '포부' },
  { hanzi: '抱怨', pinyin: 'bàoyuàn', meaning: '불평하다, 원망하다' },
  { hanzi: '暴发', pinyin: 'bàofā', meaning: '갑자기 일어나다, 폭발하다' },
  { hanzi: '暴力', pinyin: 'bàolì', meaning: '폭력' },
  { hanzi: '暴露', pinyin: 'bàolù', meaning: '폭로하다, 드러나다' },
  { hanzi: '曝光', pinyin: 'bàoguāng', meaning: '노출되다, 폭로되다' },
  { hanzi: '爆发', pinyin: 'bàofā', meaning: '폭발하다 (화산, 감정)' },
  { hanzi: '爆炸', pinyin: 'bàozhà', meaning: '폭발하다' },
  { hanzi: '悲哀', pinyin: 'bēi\'āi', meaning: '비애, 슬프다' },
  { hanzi: '悲惨', pinyin: 'bēicǎn', meaning: '비참하다' },
  { hanzi: '卑鄙', pinyin: 'bēibǐ', meaning: '비열하다' },
  { hanzi: '北极', pinyin: 'běijí', meaning: '북극' },
  { hanzi: '贝壳', pinyin: 'bèiké', meaning: '조개껍데기' },
  { hanzi: '备份', pinyin: 'bèifèn', meaning: '백업하다' },
  { hanzi: '备忘录', pinyin: 'bèiwànglù', meaning: '비망록, 메모' },
  { hanzi: '背叛', pinyin: 'bèipàn', meaning: '배반하다' },
  { hanzi: '背诵', pinyin: 'bèisòng', meaning: '암송하다' },
  { hanzi: '被动', pinyin: 'bèidòng', meaning: '수동적이다' },
  { hanzi: '被告', pinyin: 'bèigào', meaning: '피고' },
  { hanzi: '奔波', pinyin: 'bēnbō', meaning: '분주히 돌아다니다' },
  { hanzi: '奔驰', pinyin: 'bēnchí', meaning: '질주하다' },
  { hanzi: '本能', pinyin: 'běnnéng', meaning: '본능' },
];
