const hsk5Words = [
  { hanzi: '哎', pinyin: 'āi', meaning: '어머나 (감탄사)' },
  { hanzi: '爱护', pinyin: 'àihù', meaning: '아끼고 보호하다' },
  { hanzi: '爱惜', pinyin: 'àixī', meaning: '소중히 여기다' },
  { hanzi: '爱心', pinyin: 'àixīn', meaning: '사랑하는 마음' },
  { hanzi: '安慰', pinyin: 'ānwèi', meaning: '위로하다' },
  { hanzi: '安装', pinyin: 'ānzhuāng', meaning: '설치하다' },
  { hanzi: '岸', pinyin: 'àn', meaning: '기슭, 언덕' },
  { hanzi: '暗', pinyin: 'àn', meaning: '어둡다' },
  { hanzi: '熬夜', pinyin: 'áoyè', meaning: '밤을 새우다' },
  { hanzi: '把握', pinyin: 'bǎwò', meaning: '잡다, 파악하다' },
  { hanzi: '摆', pinyin: 'bǎi', meaning: '배열하다, 놓다' },
  { hanzi: '办理', pinyin: 'bànlǐ', meaning: '처리하다' },
  { hanzi: '傍晚', pinyin: 'bàngwǎn', meaning: '저녁 무렵' },
  { hanzi: '包裹', pinyin: 'bāoguǒ', meaning: '소포' },
  { hanzi: '包含', pinyin: 'bāohán', meaning: '포함하다' },
  { hanzi: '包括', pinyin: 'bāokuò', meaning: '포함하다' },
  { hanzi: '薄', pinyin: 'báo', meaning: '얇다' },
  { hanzi: '宝贝', pinyin: 'bǎobèi', meaning: '보배, 귀염둥이' },
  { hanzi: '宝贵', pinyin: 'bǎoguì', meaning: '귀중하다' },
  { hanzi: '保持', pinyin: 'bǎochí', meaning: '유지하다' },
  { hanzi: '保存', pinyin: 'bǎocún', meaning: '보존하다' },
  { hanzi: '保留', pinyin: 'bǎoliú', meaning: '보류하다' },
  { hanzi: '保险', pinyin: 'bǎoxiǎn', meaning: '보험' },
  { hanzi: '报到', pinyin: 'bàodào', meaning: '도착을 알리다, 등록하다' },
  { hanzi: '报道', pinyin: 'bàodào', meaning: '보도하다' },
  { hanzi: '报告', pinyin: 'bàogào', meaning: '보고하다' },
  { hanzi: '报社', pinyin: 'bàoshè', meaning: '신문사' },
  { hanzi: '抱怨', pinyin: 'bàoyuàn', meaning: '원망하다, 불평하다' },
  { hanzi: '悲观', pinyin: 'bēiguān', meaning: '비관적이다' },
  { hanzi: '背', pinyin: 'bèi', meaning: '등, 업다' },
  { hanzi: '背景', pinyin: 'běijǐng', meaning: '배경' },
  { hanzi: '被子', pinyin: 'bèizi', meaning: '이불' },
  { hanzi: '本科', pinyin: 'běnkē', meaning: '학부 (대학)' },
  { hanzi: '本领', pinyin: 'běnlǐng', meaning: '능력, 솜씨' },
  { hanzi: '本质', pinyin: 'běnzhì', meaning: '본질' },
  { hanzi: '比例', pinyin: 'bǐlì', meaning: '비례, 비율' },
  { hanzi: '彼此', pinyin: 'bǐcǐ', meaning: '피차, 서로' },
  { hanzi: '必然', pinyin: 'bìrán', meaning: '필연적이다' },
  { hanzi: '必要', pinyin: 'bìyào', meaning: '필요하다' },
  { hanzi: '毕竟', pinyin: 'bìjìng', meaning: '어쨌든, 결국' },
  { hanzi: '避免', pinyin: 'bìmiǎn', meaning: '피하다' },
  { hanzi: '编辑', pinyin: 'biānjí', meaning: '편집하다' },
  { hanzi: '鞭炮', pinyin: 'biānpào', meaning: '폭죽' },
  { hanzi: '便', pinyin: 'biàn', meaning: '곧, 편하다' },
  { hanzi: '辩论', pinyin: 'biànlùn', meaning: '변론하다' },
  { hanzi: '标点', pinyin: 'biāodiǎn', meaning: '구두점' },
  { hanzi: '标志', pinyin: 'biāozhì', meaning: '상징, 표지' },
  { hanzi: '表达', pinyin: 'biǎodá', meaning: '표현하다' },
  { hanzi: '表面', pinyin: 'biǎomiàn', meaning: '표면' },
  { hanzi: '表明', pinyin: 'biǎomíng', meaning: '분명하게 나타내다' },
  { hanzi: '表情', pinyin: 'biǎoqíng', meaning: '표정' },
  { hanzi: '表现', pinyin: 'biǎoxiàn', meaning: '표현하다, 태도' },
  { hanzi: '冰激凌', pinyin: 'bīngjīlíng', meaning: '아이스크림' },
  { hanzi: '病毒', pinyin: 'bìngdú', meaning: '바이러스' },
  { hanzi: '玻璃', pinyin: 'bōli', meaning: '유리' },
  { hanzi: '播放', pinyin: 'bōfàng', meaning: '방송하다' },
  { hanzi: '脖子', pinyin: 'bózi', meaning: '목' },
  { hanzi: '博物馆', pinyin: 'bówùguǎn', meaning: '박물관' },
  { hanzi: '补充', pinyin: 'bǔchōng', meaning: '보충하다' },
  { hanzi: '不安', pinyin: 'bù\'ān', meaning: '불안하다' },
  { hanzi: '不得了', pinyin: 'bùdéliǎo', meaning: '큰일 났다' },
  { hanzi: '不断', pinyin: 'búduàn', meaning: '끊임없이' },
  { hanzi: '不见得', pinyin: 'bújiànde', meaning: '반드시 ~한 것은 아니다' },
  { hanzi: '不耐烦', pinyin: 'búnàifán', meaning: '귀찮다, 성가시다' },
  { hanzi: '不要紧', pinyin: 'búyàojǐn', meaning: '괜찮다, 문제없다' },
  { hanzi: '布', pinyin: 'bù', meaning: '천, 직물' },
  { hanzi: '步骤', pinyin: 'bùzhòu', meaning: '절차, 단계' },
  { hanzi: '部门', pinyin: 'bùmén', meaning: '부서, 부문' },
  { hanzi: '财产', pinyin: 'cáichǎn', meaning: '재산' },
  { hanzi: '采访', pinyin: 'cǎifǎng', meaning: '취재하다' },
  { hanzi: '采取', pinyin: 'cǎiqǔ', meaning: '채택하다' },
  { hanzi: '彩虹', pinyin: 'cǎihóng', meaning: '무지개' },
  { hanzi: '踩', pinyin: 'cǎi', meaning: '밟다' },
  { hanzi: '参考', pinyin: 'cānkǎo', meaning: '참고하다' },
  { hanzi: '参与', pinyin: 'cānyù', meaning: '참여하다' },
  { hanzi: '惭愧', pinyin: 'cánkuì', meaning: '부끄럽다' },
  { hanzi: '操场', pinyin: 'cāochǎng', meaning: '운동장' },
  { hanzi: '操心', pinyin: 'cāoxīn', meaning: '애태우다, 신경 쓰다' },
];
